//
// Created by Yu Liang on 10/13/22.
//

#ifndef MYSQL_GLOBAL_ERRMSGS_INIT_H
#define MYSQL_GLOBAL_ERRMSGS_INIT_H

inline const char*** ret_errmsgs()
{

  static const char *errmsg_list_0[] = {
      "hashchk",
      "isamchk",
      "NO",
      "YES",
      "Can\'t create file \'%-.200s\' (errno: %M)",
      "Can\'t create table %`s.%`s (errno: %M)",
      "Can\'t create database \'%-.192s\' (errno: %M)",
      "Can\'t create database \'%-.192s\'; database exists",
      "Can\'t drop database \'%-.192s\'; database doesn\'t exist",
      "Error dropping database (can\'t delete \'%-.192s\', errno: %M)",
      "Error dropping database (can\'t rmdir \'%-.192s\', errno: %M)",
      "Error on delete of \'%-.192s\' (errno: %M)",
      "Can\'t read record in system table",
      "Can\'t get status of \'%-.200s\' (errno: %M)",
      "Can\'t get working directory (errno: %M)",
      "Can\'t lock file (errno: %M)",
      "Can\'t open file: \'%-.200s\' (errno: %M)",
      "Can\'t find file: \'%-.200s\' (errno: %M)",
      "Can\'t read dir of \'%-.192s\' (errno: %M)",
      "Can\'t change dir to \'%-.192s\' (errno: %M)",
      "Record has changed since last read in table \'%-.192s\'",
      "Disk full (%s); waiting for someone to free some space... (errno: %M)",
      "Can\'t write; duplicate key in table \'%-.192s\'",
      "Error on close of \'%-.192s\' (errno: %M)",
      "Error reading file \'%-.200s\' (errno: %M)",
      "Error on rename of \'%-.210s\' to \'%-.210s\' (errno: %M)",
      "Error writing file \'%-.200s\' (errno: %M)",
      "\'%-.192s\' is locked against change",
      "Sort aborted",
      "View \'%-.192s\' doesn\'t exist for \'%-.192s\'",
      "Got error %M from storage engine %s",
      "Storage engine %s of the table %`s.%`s doesn\'t have this option",
      "Can\'t find record in \'%-.192s\'",
      "Incorrect information in file: \'%-.200s\'",
      "Index for table \'%-.200s\' is corrupt; try to repair it",
      "Old key file for table \'%-.192s\'; repair it!",
      "Table \'%-.192s\' is read only",
      "Out of memory; restart server and try again (needed %d bytes)",
      "Out of sort memory, consider increasing server sort buffer size",
      "Unexpected EOF found when reading file \'%-.192s\' (errno: %M)",
      "Too many connections",
      "Out of memory.",
      "Can\'t get hostname for your address",
      "Bad handshake",
      "Access denied for user \'%s\'@\'%s\' to database \'%-.192s\'",
      "Access denied for user \'%s\'@\'%s\' (using password: %s)",
      "No database selected",
      "Unknown command",
      "Column \'%-.192s\' cannot be null",
      "Unknown database \'%-.192s\'",
      "Table \'%-.192s\' already exists",
      "Unknown table \'%-.100T\'",
      "Column \'%-.192s\' in %-.192s is ambiguous",
      "Server shutdown in progress",
      "Unknown column \'%-.192s\' in \'%-.192s\'",
      "\'%-.192s\' isn\'t in GROUP BY",
      "Can\'t group on \'%-.192s\'",
      "Statement has sum functions and columns in same statement",
      "Column count doesn\'t match value count",
      "Identifier name \'%-.100T\' is too long",
      "Duplicate column name \'%-.192s\'",
      "Duplicate key name \'%-.192s\'",
      "Duplicate entry \'%-.192T\' for key %d",
      "Incorrect column specifier for column \'%-.192s\'",
      "%s near \'%-.80T\' at line %d",
      "Query was empty",
      "Not unique table/alias: \'%-.192s\'",
      "Invalid default value for \'%-.192s\'",
      "Multiple primary key defined",
      "Too many keys specified; max %d keys allowed",
      "Too many key parts specified; max %d parts allowed",
      "Specified key was too long; max key length is %d bytes",
      "Key column \'%-.192s\' doesn\'t exist in table",
      "BLOB column %`s can\'t be used in key specification in the %s table",
      "Column length too big for column \'%-.192s\' (max = %lu); use BLOB or TEXT instead",
      "Incorrect table definition; there can be only one auto column and it must be defined as a key",
      "Could not delete gtid domain. Reason: %s.",
      "%s (initiated by: %s): Normal shutdown",
      "%s: Got signal %d. Aborting!\n",
      "%s: Shutdown complete\n",
      "%s: Forcing close of thread %ld  user: \'%-.48s\'\n",
      "Can\'t create IP socket",
      "Table \'%-.192s\' has no index like the one used in CREATE INDEX; recreate the table",
      "Field separator argument is not what is expected; check the manual",
      "You can\'t use fixed rowlength with BLOBs; please use \'fields terminated by\'",
      "The file \'%-.128s\' must be in the database directory or be readable by all",
      "File \'%-.200s\' already exists",
      "Records: %ld  Deleted: %ld  Skipped: %ld  Warnings: %ld",
      "Records: %ld  Duplicates: %ld",
      "Incorrect prefix key; the used key part isn\'t a string, the used length is longer than the key part, or the storage engine doesn\'t support ique prefix keys",
      "You can\'t delete all columns with ALTER TABLE; use DROP TABLE instead",
      "Can\'t DROP %s %`-.192s; check that it exists",
      "Records: %ld  Duplicates: %ld  Warnings: %ld",
      "Table \'%-.192s\' is specified twice, both as a target for \'%s\' and as a separate source for data",
      "Unknown thread id: %lu",
      "You are not owner of thread %lld",
      "No tables used",
      "Too many strings for column %-.192s and SET",
      "Can\'t generate a unique log-filename %-.200s.(1-999)\n",
      "Table \'%-.192s\' was locked with a READ lock and can\'t be updated",
      "Table \'%-.192s\' was not locked with LOCK TABLES",
      "You should never see it",
      "Incorrect database name \'%-.100T\'",
      "Incorrect table name \'%-.100s\'",
      "The SELECT would examine more than MAX_JOIN_SIZE rows; check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if the SELECT is ay",
      "Unknown error",
      "Unknown procedure \'%-.192s\'",
      "Incorrect parameter count to procedure \'%-.192s\'",
      "Incorrect parameters to procedure \'%-.192s\'",
      "Unknown table \'%-.192s\' in %-.32s",
      "Column \'%-.192s\' specified twice",
      "Invalid use of group function",
      "Table \'%-.192s\' uses an extension that doesn\'t exist in this MariaDB version",
      "A table must have at least 1 column",
      "The table \'%-.192s\' is full",
      "Unknown character set: \'%-.64s\'",
      "Too many tables; MariaDB can only use %d tables in a join",
      "Too many columns",
      "Row size too large. The maximum row size for the used table type, not counting BLOBs, is %ld. This includes storage overhead, check the nual. You have to change some columns to TEXT or BLOBs",
      "Thread stack overrun:  Used: %ld of a %ld stack.  Use \'mariadbd --thread_stack=#\' to specify a bigger stack if needed",
      "Cross dependency found in OUTER JOIN; examine your ON conditions",
      "Table handler doesn\'t support NULL in given index. Please change column \'%-.192s\' to be NOT NULL or use another handler",
      "Can\'t load function \'%-.192s\'",
      "Can\'t initialize function \'%-.192s\'; %-.80s",
      "No paths allowed for shared library",
      "Function \'%-.192s\' already exists",
      "Can\'t open shared library \'%-.192s\' (errno: %d, %-.128s)",
      "Can\'t find symbol \'%-.128s\' in library",
      "Function \'%-.192s\' is not defined",
      "Host \'%-.64s\' is blocked because of many connection errors; unblock with \'mariadb-admin flush-hosts\'",
      "Host \'%-.64s\' is not allowed to connect to this MariaDB server",
      "You are using MariaDB as an anonymous user and anonymous users are not allowed to modify user settings",
      "You must have privileges to update tables in the mysql database to be able to change passwords for others",
      "Can\'t find any matching row in the user table",
      "Rows matched: %ld  Changed: %ld  Warnings: %ld",
      "Can\'t create a new thread (errno %M); if you are not out of available memory, you can consult the manual for a possible OS-dependent g",
      "Column count doesn\'t match value count at row %lu",
      "Can\'t reopen table: \'%-.192s\'",
      "Invalid use of NULL value",
      "Regex error \'%s\'",
      "Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause",
      "There is no such grant defined for user \'%-.48s\' on host \'%-.64s\'",
      "%-.100T command denied to user \'%s\'@\'%s\' for table \'%-.192s\'",
      "%-.32s command denied to user \'%s\'@\'%s\' for column \'%-.192s\' in table \'%-.192s\'",
      "Illegal GRANT/REVOKE command; please consult the manual to see which privileges can be used",
      "The host or user argument to GRANT is too long",
      "Table \'%-.192s.%-.192s\' doesn\'t exist",
      "There is no such grant defined for user \'%-.48s\' on host \'%-.64s\' on table \'%-.192s\'",
      "The used command is not allowed with this MariaDB version",
      "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use",
      "Delayed insert thread couldn\'t get requested lock for table %-.192s",
      "Too many delayed threads in use",
      "Aborted connection %ld to db: \'%-.192s\' user: \'%-.48s\' (%-.64s)",
      "Got a packet bigger than \'max_allowed_packet\' bytes",
      "Got a read error from the connection pipe",
      "Got an error from fcntl()",
      "Got packets out of order",
      "Couldn\'t uncompress communication packet",
      "Got an error reading communication packets",
      "Got timeout reading communication packets",
      "Got an error writing communication packets",
      "Got timeout writing communication packets",
      "Result string is longer than \'max_allowed_packet\' bytes",
      "Storage engine %s doesn\'t support BLOB/TEXT columns",
      "Storage engine %s doesn\'t support AUTO_INCREMENT columns",
      "INSERT DELAYED can\'t be used with table \'%-.192s\' because it is locked with LOCK TABLES",
      "Incorrect column name \'%-.100s\'",
      "The storage engine %s can\'t index column %`s",
      "Unable to open underlying table which is differently defined or of non-MyISAM type or doesn\'t exist",
      "Can\'t write, because of unique constraint, to table \'%-.192s\'",
      "BLOB/TEXT column \'%-.192s\' used in key specification without a key length",
      "All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead",
      "Result consisted of more than one row",
      "This table type requires a primary key",
      "This version of MariaDB is not compiled with RAID support",
      "You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column",
      "Key \'%-.192s\' doesn\'t exist in table \'%-.192s\'",
      "Can\'t open table",
      "The storage engine for the table doesn\'t support %s",
      "You are not allowed to execute this command in a transaction",
      "Got error %M during COMMIT",
      "Got error %M during ROLLBACK",
      "Got error %M during FLUSH_LOGS",
      "Got error %M during CHECKPOINT",
      "Aborted connection %lld to db: \'%-.192s\' user: \'%-.48s\' host: \'%-.64s\' (%-.64s)",
      "You should never see it",
      "Binlog closed, cannot RESET MASTER",
      "Failed rebuilding the index of  dumped table \'%-.192s\'",
      "Error from master: \'%-.64s\'",
      "Net error reading from master",
      "Net error writing to master",
      "Can\'t find FULLTEXT index matching the column list",
      "Can\'t execute the given command because you have active locked tables or an active transaction",
      "Unknown system variable \'%-.*s\'",
      "Table \'%-.192s\' is marked as crashed and should be repaired",
      "Table \'%-.192s\' is marked as crashed and last (automatic?) repair failed",
      "Some non-transactional changed tables couldn\'t be rolled back",
      "Multi-statement transaction required more than \'max_binlog_cache_size\' bytes of storage; increase this mariadbd variable and try again",
      "This operation cannot be performed as you have a running slave \'%2$*1$s\'; run STOP SLAVE \'%2$*1$s\' first",
      "This operation requires a running slave; configure slave and do START SLAVE",
      "The server is not configured as slave; fix in config file or with CHANGE MASTER TO",
      "Could not initialize master info structure for \'%.*s\'; more error messages can be found in the MariaDB error log",
      "Could not create slave thread; check system resources",
      "User %-.64s already has more than \'max_user_connections\' active connections",
      "You may only use constant expressions in this statement",
      "Lock wait timeout exceeded; try restarting transaction",
      "The total number of locks exceeds the lock table size",
      "Update locks cannot be acquired during a READ UNCOMMITTED transaction",
      "DROP DATABASE not allowed while thread is holding global read lock",
      "CREATE DATABASE not allowed while thread is holding global read lock",
      "Incorrect arguments to %s",
      "\'%s\'@\'%s\' is not allowed to create new users",
      "Incorrect table definition; all MERGE tables must be in the same database",
      "Deadlock found when trying to get lock; try restarting transaction",
      "The storage engine %s doesn\'t support FULLTEXT indexes",
      "Cannot add foreign key constraint for `%s`",
      "Cannot add or update a child row: a foreign key constraint fails",
      "Cannot delete or update a parent row: a foreign key constraint fails",
      "Error connecting to master: %-.128s",
      "Error running query on master: %-.128s",
      "Error when executing command %s: %-.128s",
      "Incorrect usage of %s and %s",
      "The used SELECT statements have a different number of columns",
      "Can\'t execute the query because you have a conflicting read lock",
      "Mixing of transactional and non-transactional tables is disabled",
      "Option \'%s\' used twice in statement",
      "User \'%-.64s\' has exceeded the \'%s\' resource (current value: %ld)",
      "Access denied; you need (at least one of) the %-.128s privilege(s) for this operation",
      "Variable \'%-.64s\' is a SESSION variable and can\'t be used with SET GLOBAL",
      "Variable \'%-.64s\' is a GLOBAL variable and should be set with SET GLOBAL",
      "Variable \'%-.64s\' doesn\'t have a default value",
      "Variable \'%-.64s\' can\'t be set to the value of \'%-.200T\'",
      "Incorrect argument type to variable \'%-.64s\'",
      "Variable \'%-.64s\' can only be set, not read",
      "Incorrect usage/placement of \'%s\'",
      "This version of MariaDB doesn\'t yet support \'%s\'",
      "Got fatal error %d from master when reading data from binary log: \'%-.320s\'",
      "Slave SQL thread ignored the query because of replicate-*-table rules",
      "Variable \'%-.192s\' is a %s variable",
      "Incorrect foreign key definition for \'%-.192s\': %s",
      "Key reference and table reference don\'t match",
      "Operand should contain %d column(s)",
      "Subquery returns more than 1 row",
      "Unknown prepared statement handler (%.*s) given to %s",
      "Help database is corrupt or does not exist",
      "Cyclic reference on subqueries",
      "Converting column \'%s\' from %s to %s",
      "Reference \'%-.64s\' not supported (%s)",
      "Every derived table must have its own alias",
      "Select %u was reduced during optimization",
      "Table \'%-.192s\' from one of the SELECTs cannot be used in %-.32s",
      "Client does not support authentication protocol requested by server; consider upgrading MariaDB client",
      "All parts of a SPATIAL index must be NOT NULL",
      "COLLATION \'%s\' is not valid for CHARACTER SET \'%s\'",
      "Slave is already running",
      "Slave already has been stopped",
      "Uncompressed data size too large; the maximum size is %d (probably, length of uncompressed data was corrupted)",
      "ZLIB: Not enough memory",
      "ZLIB: Not enough room in the output buffer (probably, length of uncompressed data was corrupted)",
      "ZLIB: Input data corrupted",
      "Row %u was cut by %s)",
      "Row %lu doesn\'t contain data for all columns",
      "Row %lu was truncated; it contained more data than there were input columns",
      "Column set to default value; NULL supplied to NOT NULL column \'%s\' at row %lu",
      "Out of range value for column \'%s\' at row %lu",
      "Data truncated for column \'%s\' at row %lu",
      "Using storage engine %s for table \'%s\'",
      "Illegal mix of collations (%s,%s) and (%s,%s) for operation \'%s\'",
      "Cannot drop one or more of the requested users",
      "Can\'t revoke all privileges for one or more of the requested users",
      "Illegal mix of collations (%s,%s), (%s,%s), (%s,%s) for operation \'%s\'",
      "Illegal mix of collations for operation \'%s\'",
      "Variable \'%-.64s\' is not a variable component (can\'t be used as XXXX.variable_name)",
      "Unknown collation: \'%-.64s\'",
      "SSL parameters in CHANGE MASTER are ignored because this MariaDB slave was compiled without SSL support; they can be used later if riaDB slave with SSL is started",
      "Server is running in --secure-auth mode, but \'%s\'@\'%s\' has a password in the old format; please change the password to the w format",
      "Field or reference \'%-.192s%s%-.192s%s%-.192s\' of SELECT #%d was resolved in SELECT #%d",
      "Incorrect parameter or combination of parameters for START SLAVE UNTIL",
      "It is recommended to use --skip-slave-start when doing step-by-step replication with START SLAVE UNTIL; otherwise, you will get problems if u get an unexpected slave\'s mariadbd restart",
      "SQL thread is not to be started so UNTIL options are ignored",
      "Incorrect index name \'%-.100s\'",
      "Incorrect catalog name \'%-.100s\'",
      "Query cache failed to set size %llu; new query cache size is %lu",
      "Column \'%-.192s\' cannot be part of FULLTEXT index",
      "Unknown key cache \'%-.100s\'",
      "MariaDB is started in --skip-name-resolve mode; you must restart it without this switch for this grant to work",
      "Unknown storage engine \'%s\'",
      "\'%s\' is deprecated and will be removed in a future release. Please use %s instead",
      "The target table %-.100s of the %s is not updatable",
      "The \'%s\' feature is disabled; you need MariaDB built with \'%s\' to have it working",
      "The MariaDB server is running with the %s option so it cannot execute this statement",
      "Column \'%-.100s\' has duplicated value \'%-.64s\' in %s",
      "Truncated incorrect %-.32T value: \'%-.128T\'",
      "Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause",
      "Invalid ON UPDATE clause for \'%-.192s\' column",
      "This command is not supported in the prepared statement protocol yet",
      "Got error %d \'%-.200s\' from %s",
      "Got temporary error %d \'%-.200s\' from %s",
      "Unknown or incorrect time zone: \'%-.64s\'",
      "Invalid TIMESTAMP value in column \'%s\' at row %lu",
      "Invalid %s character string: \'%.64T\'",
      "Result of %s() was larger than max_allowed_packet (%ld) - truncated",
      "Conflicting declarations: \'%s%s\' and \'%s%s\'",
      "Can\'t create a %s from within another stored routine",
      "%s %s already exists",
      "%s %s does not exist",
      "Failed to DROP %s %s",
      "Failed to CREATE %s %s",
      "%s with no matching label: %s",
      "Redefining label %s",
      "End-label %s without match",
      "Referring to uninitialized variable %s",
      "PROCEDURE %s can\'t return a result set in the given context",
      "RETURN is only allowed in a FUNCTION",
      "%s is not allowed in stored procedures",
      "The update log is deprecated and replaced by the binary log; SET SQL_LOG_UPDATE has been ignored. This option will be removed in riaDB 5.6",
      "The update log is deprecated and replaced by the binary log; SET SQL_LOG_UPDATE has been translated to SET SQL_LOG_BIN. This tion will be removed in MariaDB 5.6",
      "Query execution was interrupted",
      "Incorrect number of arguments for %s %s; expected %u, got %u",
      "Undefined CONDITION: %s",
      "No RETURN found in FUNCTION %s",
      "FUNCTION %s ended without RETURN",
      "Cursor statement must be a SELECT",
      "Cursor SELECT must not have INTO",
      "Undefined CURSOR: %s",
      "Cursor is already open",
      "Cursor is not open",
      "Undeclared variable: %s",
      "Incorrect number of FETCH variables",
      "No data - zero rows fetched, selected, or processed",
      "Duplicate parameter: %s",
      "Duplicate variable: %s",
      "Duplicate condition: %s",
      "Duplicate cursor: %s",
      "Failed to ALTER %s %s",
      "Subquery value not supported",
      "%s is not allowed in stored function or trigger",
      "Variable or condition declaration after cursor or handler declaration",
      "Cursor declaration after handler declaration",
      "Case not found for CASE statement",
      "Configuration file \'%-.192s\' is too big",
      "Malformed file type header in file \'%-.192s\'",
      "Unexpected end of file while parsing comment \'%-.200s\'",
      "Error while parsing parameter \'%-.192s\' (line: \'%-.192s\')",
      "Unexpected end of file while skipping unknown parameter \'%-.192s\'",
      "ANALYZE/EXPLAIN/SHOW can not be issued; lacking privileges for underlying table",
      "File \'%-.192s\' has unknown type \'%-.64s\' in its header",
      "\'%-.192s.%-.192s\' is not of type \'%s\'",
      "Column \'%-.192s\' is not updatable",
      "View\'s SELECT contains a subquery in the FROM clause",
      "View\'s SELECT contains a \'%s\' clause",
      "View\'s SELECT contains a variable or parameter",
      "View\'s SELECT refers to a temporary table \'%-.192s\'",
      "View\'s SELECT and view\'s field list have different column counts",
      "View merge algorithm can\'t be used here for now (assumed undefined algorithm)",
      "View being updated does not have complete key of underlying table in it",
      "View \'%-.192s.%-.192s\' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them",
      "Can\'t drop or alter a %s from within another stored routine",
      "GOTO is not allowed in a stored procedure handler",
      "Trigger \'%s\' already exists",
      "Trigger does not exist",
      "Trigger\'s \'%-.192s\' is a view, temporary table or sequence",
      "Updating of %s row is not allowed in %strigger",
      "There is no %s row in %s trigger",
      "Field \'%-.192s\' doesn\'t have a default value",
      "Division by 0",
      "Incorrect %-.32s value: \'%-.128T\' for column `%.192s`.`%.192s`.`%.192s` at row %lu",
      "Illegal %s \'%-.192T\' value found during parsing",
      "CHECK OPTION on non-updatable view %`-.192s.%`-.192s",
      "CHECK OPTION failed %`-.192s.%`-.192s",
      "%-.32s command denied to user \'%s\'@\'%s\' for routine \'%-.192s\'",
      "Failed purging old relay logs: %s",
      "Password hash should be a %d-digit hexadecimal number",
      "Target log not found in binlog index",
      "I/O error reading log index file",
      "Server configuration does not permit binlog purge",
      "Failed on fseek()",
      "Fatal error during log purge",
      "A purgeable log is in use, will not purge",
      "Unknown error during log purge",
      "Failed initializing relay log position: %s",
      "You are not using binary logging",
      "The \'%-.64s\' syntax is reserved for purposes internal to the MariaDB server",
      "WSAStartup Failed",
      "Can\'t handle procedures with different groups yet",
      "Select must have a group with this procedure",
      "Can\'t use ORDER clause with this procedure",
      "Binary logging and replication forbid changing the global server %s",
      "Can\'t map file: %-.200s, errno: %M",
      "Wrong magic in %-.64s",
      "Prepared statement contains too many placeholders",
      "Key part \'%-.192s\' length cannot be 0",
      "View text checksum failed",
      "Can not modify more than one base table through a join view \'%-.192s.%-.192s\'",
      "Can not insert into join view \'%-.192s.%-.192s\' without fields list",
      "Can not delete from join view \'%-.192s.%-.192s\'",
      "Operation %s failed for %.256s",
      "XAER_NOTA: Unknown XID",
      "XAER_INVAL: Invalid arguments (or unsupported command)",
      "XAER_RMFAIL: The command cannot be executed when global transaction is in the  %.64s state",
      "XAER_OUTSIDE: Some work is done outside global transaction",
      "XAER_RMERR: Fatal error occurred in the transaction branch - check your data for consistency",
      "XA_RBROLLBACK: Transaction branch was rolled back",
      "There is no such grant defined for user \'%-.48s\' on host \'%-.64s\' on routine \'%-.192s\'",
      "Failed to grant EXECUTE and ALTER ROUTINE privileges",
      "Failed to revoke all privileges to dropped routine",
      "Data too long for column \'%s\' at row %lu",
      "Bad SQLSTATE: \'%s\'",
      "%s: ready for connections.\nVersion: \'%s\'  socket: \'%s\'  port: %d  %s",
      "Can\'t load value from file with fixed size rows to variable",
      "You are not allowed to create a user with GRANT",
      "Incorrect %-.32s value: \'%-.128T\' for function %-.32s",
      "Table definition has changed, please retry transaction",
      "Duplicate handler declared in the same block",
      "OUT or INOUT argument %d for routine %s is not a variable or NEW pseudo-variable in BEFORE trigger",
      "Not allowed to return a result set from a %s",
      "Cannot get geometry object from data you send to the GEOMETRY field",
      "A routine failed and has neither NO SQL nor READS SQL DATA in its declaration and binary logging is enabled; if non-transactional bles were updated, the binary log will miss their changes",
      "This function has none of DETERMINISTIC, NO SQL, or READS SQL DATA in its declaration and binary logging is enabled (you *might* want to e the less safe log_bin_trust_function_creators variable)",
      "You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe g_bin_trust_function_creators variable)",
      "You can\'t execute a prepared statement which has an open cursor associated with it. Reset the statement to re-execute it",
      "The statement (%lu) has no open cursor",
      "Explicit or implicit commit is not allowed in stored function or trigger",
      "Field of view \'%-.192s.%-.192s\' underlying table doesn\'t have a default value",
      "Recursive stored functions and triggers are not allowed",
      "Too big scale specified for \'%-.192s\'. Maximum is %u",
      "Too big precision specified for \'%-.192s\'. Maximum is %u",
      "For float(M,D), double(M,D) or decimal(M,D), M must be >= D (column \'%-.192s\')",
      "You can\'t combine write-locking of system tables with other tables or lock types",
      "Unable to connect to foreign data source: %.64s",
      "There was a problem processing the query on the foreign data source. Data source error: %-.64s",
      "The foreign data source you are trying to reference does not exist. Data source error:  %-.64s",
      "Can\'t create federated table. The data source connection string \'%-.64s\' is not in the correct format",
      "The data source connection string \'%-.64s\' is not in the correct format",
      "Can\'t create federated table. Foreign data src error:  %-.64s",
      "Trigger in wrong schema",
      "Thread stack overrun:  %ld bytes used of a %ld byte stack, and %ld bytes needed. Consider increasing the thread_stack system variable.",
      "Routine body for \'%-.100s\' is too long",
      "Cannot drop default keycache",
      "Display width out of range for \'%-.192s\' (max = %lu)",
      "XAER_DUPID: The XID already exists",
      "Datetime function: %-.32s field overflow",
      "Can\'t update table \'%-.192s\' in stored function/trigger because it is already used by statement which invoked this ored function/trigger",
      "The definition of table \'%-.192s\' prevents operation %-.192s on table \'%-.192s\'",
      "The prepared statement contains a stored routine call that refers to that same statement. It\'s not allowed to execute a prepared statement in ch a recursive manner",
      "Not allowed to set autocommit from a stored function or trigger",
      "Invalid definer",
      "View \'%-.192s\'.\'%-.192s\' has no definer information (old table format). Current user is used as definer. Please recreate the view!",
      "You need the SUPER privilege for creation view with \'%-.192s\'@\'%-.192s\' definer",
      "The user specified as a definer (\'%-.64s\'@\'%-.64s\') does not exist",
      "Changing schema from \'%-.192s\' to \'%-.192s\' is not allowed",
      "Cannot delete or update a parent row: a foreign key constraint fails (%.192s)",
      "Cannot add or update a child row: a foreign key constraint fails (%.192s)",
      "Variable \'%-.64s\' must be quoted with `...`, or renamed",
      "No definer attribute for trigger \'%-.192s\'.\'%-.192s\'. The trigger will be activated under the authorization of the invoker, which may have sufficient privileges. Please recreate the trigger",
      "\'%-.192s\' has an old format, you should re-create the \'%s\' object(s)",
      "Recursive limit %d (as set by the max_sp_recursion_depth variable) was exceeded for routine %.192s",
      "Failed to load routine %-.192s (internal code %d). For more details, run SHOW WARNINGS",
      "Incorrect routine name \'%-.192s\'",
      "Upgrade required. Please do \"REPAIR %s %`s\" or dump/reload to fix it!",
      "AGGREGATE is not supported for stored functions",
      "Can\'t create more than max_prepared_stmt_count statements (current value: %u)",
      "%`s.%`s contains view recursion",
      "Non-grouping field \'%-.192s\' is used in %-.64s clause",
      "The storage engine %s doesn\'t support SPATIAL indexes",
      "Triggers can not be created on system tables",
      "Leading spaces are removed from name \'%s\'",
      "Failed to read auto-increment value from storage engine",
      "user name",
      "host name",
      "String \'%-.70T\' is too long for %s (should be no longer than %d)",
      "The target table %-.100s of the %s is not insertable-into",
      "Table \'%-.64s\' is differently defined or of non-MyISAM type or doesn\'t exist",
      "Too high level of nesting for select",
      "Name \'%-.64s\' has become \'\'",
      "First character of the FIELDS TERMINATED string is ambiguous; please use non-optional and non-empty FIELDS ENCLOSED BY",
      "Cannot create foreign server \'%s\' as it already exists",
      "The foreign server name you are trying to reference does not exist. Data source error:  %-.64s",
      "Table storage engine \'%-.64s\' does not support the create option \'%.64s\'",
      "Syntax error: %-.64s PARTITIONING requires definition of VALUES %-.64s for each partition",
      "Only %-.64s PARTITIONING can use VALUES %-.64s in partition definition",
      "MAXVALUE can only be used in last partition definition",
      "Subpartitions can only be hash partitions and by key",
      "Must define subpartitions on all partitions if on one partition",
      "Wrong number of partitions defined, mismatch with previous setting",
      "Wrong number of subpartitions defined, mismatch with previous setting",
      "Constant, random or timezone-dependent expressions in (sub)partitioning function are not allowed",
      "Expression in %s must be constant",
      "Field in list of fields for partition function not found in table",
      "List of fields is only allowed in KEY partitions",
      "The partition info in the frm file is not consistent with what can be written into the frm file",
      "The %-.192s function returns the wrong type",
      "For %-.64s partitions each partition must be defined",
      "VALUES LESS THAN value must be strictly increasing for each partition",
      "VALUES value must be of same type as partition function",
      "Multiple definition of same constant in list partitioning",
      "Partitioning can not be used stand-alone in query",
      "The mix of handlers in the partitions is not allowed in this version of MariaDB",
      "For the partitioned engine it is necessary to define all %-.64s",
      "Too many partitions (including subpartitions) were defined",
      "It is only possible to mix RANGE/LIST partitioning with HASH/KEY partitioning for subpartitioning",
      "Failed to create specific handler file",
      "A BLOB field is not allowed in partition function",
      "A %-.192s must include all columns in the table\'s partitioning function",
      "Number of %-.64s = 0 is not an allowed value",
      "Partition management on a not partitioned table is not possible",
      "Partitioned tables do not support %s",
      "Wrong partition name or partition list",
      "Cannot remove all partitions, use DROP TABLE instead",
      "COALESCE PARTITION can only be used on HASH/KEY partitions",
      "REORGANIZE PARTITION can only be used to reorganize partitions not to change their numbers",
      "REORGANIZE PARTITION without parameters can only be used on auto-partitioned tables using HASH PARTITIONs",
      "%-.64s PARTITION can only be used on RANGE/LIST partitions",
      "Trying to Add partition(s) with wrong number of subpartitions",
      "At least one partition must be added",
      "At least one partition must be coalesced",
      "More partitions to reorganize than there are partitions",
      "Duplicate partition name %-.192s",
      "It is not allowed to shut off binlog on this command",
      "When reorganizing a set of partitions they must be in consecutive order",
      "Reorganize of range partitions cannot change total ranges except for last partition where it can extend the range",
      "Partition function not supported in this version for this handler",
      "Partition state cannot be defined from CREATE/ALTER TABLE",
      "The %-.64s handler only supports 32 bit integers in VALUES",
      "Plugin \'%-.192s\' is not loaded",
      "Incorrect %-.32s value: \'%-.128T\'",
      "Table has no partition for value %-.64s",
      "It is not allowed to specify %s more than once",
      "Failed to create %s",
      "Failed to drop %s",
      "The handler doesn\'t support autoextend of tablespaces",
      "A size parameter was incorrectly specified, either number or on the form 10M",
      "The size number was correct but we don\'t allow the digit part to be more than 2 billion",
      "Failed to alter: %s",
      "Writing one row to the row-based binary log failed",
      "Table definition on master and slave does not match: %s",
      "Slave running with --log-slave-updates must use row-based binary logging to be able to replicate row-based binary log events",
      "Event \'%-.192s\' already exists",
      "Failed to store event %s. Error code %M from storage engine",
      "Unknown event \'%-.192s\'",
      "Failed to alter event \'%-.192s\'",
      "Failed to drop %s",
      "INTERVAL is either not positive or too big",
      "ENDS is either invalid or before STARTS",
      "Event execution time is in the past. Event has been disabled",
      "Failed to open mysql.event",
      "No datetime expression provided",
      "You should never see it",
      "You should never see it",
      "Failed to delete the event from mysql.event",
      "Error during compilation of event\'s body",
      "Same old and new event name",
      "Data for column \'%s\' too long",
      "Cannot drop index \'%-.192s\': needed in a foreign key constraint",
      "The syntax \'%s\' is deprecated and will be removed in MariaDB %s. Please use %s instead",
      "You can\'t write-lock a log table. Only read access is possible",
      "You can\'t use locks with log tables",
      "You should never see it",
      "Column count of mysql.%s is wrong. Expected %d, found %d. Created with MariaDB %d, now running %d. Please use riadb-upgrade to fix this error",
      "Cannot switch out of the row-based binary log format when the session has open temporary tables",
      "Cannot change the binary logging format inside a stored function or trigger",
      "You should never see it",
      "Cannot create temporary table with partitions",
      "Partition constant is out of partition function domain",
      "This partition function is not allowed",
      "Error in DDL log",
      "Not allowed to use NULL value in VALUES LESS THAN",
      "Incorrect partition name",
      "Transaction characteristics can\'t be changed while a transaction is in progress",
      "ALTER TABLE causes auto_increment resequencing, resulting in duplicate entry \'%-.192T\' for key \'%-.192s\'",
      "Internal scheduler error %d",
      "Error during starting/stopping of the scheduler. Error code %M",
      "Engine cannot be used in partitioned tables",
      "Cannot activate \'%-.64s\' log",
      "The server was not built with row-based replication",
      "Decoding of base64 string failed",
      "Recursion of EVENT DDL statements is forbidden when body is present",
      "Cannot proceed, because event scheduler is disabled",
      "Only integers allowed as number here",
      "Storage engine %s cannot be used for log tables",
      "You cannot \'%s\' a log table if logging is enabled",
      "Cannot rename \'%s\'. When logging enabled, rename to/from log table must rename two tables: the log table to an archive table and other table back to \'%s\'",
      "Incorrect parameter count in the call to native function \'%-.192s\'",
      "Incorrect parameters in the call to native function \'%-.192s\'",
      "Incorrect parameters in the call to stored function \'%-.192s\'",
      "This function \'%-.192s\' has the same name as a native function",
      "Duplicate entry \'%-.64T\' for key \'%-.192s\'",
      "Too many files opened, please execute the command again",
      "Event execution time is in the past and ON COMPLETION NOT PRESERVE is set. The event was dropped immediately after creation",
      "Event execution time is in the past and ON COMPLETION NOT PRESERVE is set. The event was not changed. Specify a time in the ture",
      "The incident %s occurred on the master. Message: %-.64s",
      "Table has no partition for some existing values",
      "Unsafe statement written to the binary log using statement format since BINLOG_FORMAT = STATEMENT. %s",
      "Fatal error: %s",
      "Relay log read failure: %s",
      "Relay log write failure: %s",
      "Failed to create %s",
      "Master command %s failed: %s",
      "Binary logging not possible. Message: %s",
      "View %`s.%`s has no creation context",
      "Creation context of view %`s.%`s is invalid",
      "Creation context of stored routine %`s.%`s is invalid",
      "Corrupted TRG file for table %`s.%`s",
      "Triggers for table %`s.%`s have no creation context",
      "Trigger creation context of table %`s.%`s is invalid",
      "Creation context of event %`s.%`s is invalid",
      "Cannot open table for trigger %`s.%`s",
      "Cannot create stored routine %`s. Check warnings",
      "You should never see it",
      "The BINLOG statement of type %s was not preceded by a format description BINLOG statement",
      "Corrupted replication event was detected",
      "Invalid column reference (%-.64s) in LOAD DATA",
      "Being purged log %s was not found",
      "XA_RBTIMEOUT: Transaction branch was rolled back: took too long",
      "XA_RBDEADLOCK: Transaction branch was rolled back: deadlock was detected",
      "Prepared statement needs to be re-prepared",
      "DELAYED option not supported for table \'%-.192s\'",
      "There is no master connection \'%.*s\'",
      "<%-.64s> option ignored",
      "Built-in plugins cannot be deleted",
      "Plugin is busy and will be uninstalled on shutdown",
      "%s variable \'%s\' is read-only. Use SET %s to assign the value",
      "Storage engine %s does not support rollback for this statement. Transaction rolled back and must be restarted",
      "Unexpected master\'s heartbeat data: %s",
      "The requested value for the heartbeat period is either negative or exceeds the maximum allowed (%u seconds)",
      "You should never see it",
      "Error in parsing conflict function. Message: %-.64s",
      "Write to exceptions table failed. Message: %-.128s\"",
      "Comment for table \'%-.64s\' is too long (max = %u)",
      "Comment for field \'%-.64s\' is too long (max = %u)",
      "FUNCTION %s does not exist. Check the \'Function Name Parsing and Resolution\' section in the Reference Manual",
      "Database",
      "Table",
      "Partition",
      "Subpartition",
      "Temporary",
      "Renamed",
      "Too many active concurrent transactions",
      "Non-ASCII separator arguments are not fully supported",
      "debug sync point wait timed out",
      "debug sync point hit limit reached",
      "Duplicate condition information item \'%s\'",
      "Unhandled user-defined warning condition",
      "Unhandled user-defined not found condition",
      "Unhandled user-defined exception condition",
      "RESIGNAL when handler not active",
      "SIGNAL/RESIGNAL can only use a CONDITION defined with SQLSTATE",
      "Data truncated for condition item \'%s\'",
      "Data too long for condition item \'%s\'",
      "Unknown locale: \'%-.64s\'",
      "The requested server id %d clashes with the slave startup option --replicate-same-server-id",
      "Query cache is disabled; set query_cache_type to ON or DEMAND to enable it",
      "Duplicate partition field name \'%-.192s\'",
      "Inconsistency in usage of column lists for partitioning",
      "Partition column values of incorrect type",
      "Too many fields in \'%-.192s\'",
      "Cannot use MAXVALUE as value in VALUES IN",
      "Cannot have more than one value for this type of %-.64s partitioning",
      "Row expressions in VALUES IN only allowed for multi-field column partitioning",
      "Field \'%-.192s\' is of a not allowed type for this type of partitioning",
      "The total length of the partitioning fields is too large",
      "Cannot execute statement: impossible to write to binary log since both row-incapable engines and statement-incapable engines e involved",
      "Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = ROW and at least one table uses a storage gine limited to statement-based logging",
      "Cannot execute statement: impossible to write to binary log since statement is unsafe, storage engine is limited to atement-based logging, and BINLOG_FORMAT = MIXED. %s",
      "Cannot execute statement: impossible to write to binary log since statement is in row format and at least one table uses storage engine limited to statement-based logging",
      "Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a orage engine limited to row-based logging.%s",
      "Cannot execute statement: impossible to write to binary log since statement is in row format and BINLOG_FORMAT = ATEMENT",
      "Cannot execute statement: impossible to write to binary log since more than one engine is involved and at ast one engine is self-logging",
      "The statement is unsafe because it uses a LIMIT clause. This is unsafe because the set of rows included cannot be predicted",
      "The statement is unsafe because it uses INSERT DELAYED. This is unsafe because the times when rows are inserted cannot be edicted",
      "The statement is unsafe because it uses the general log, slow query log, or performance_schema table(s). This is unsafe because stem tables may differ on slaves",
      "Statement is unsafe because it invokes a trigger or a stored function that inserts into an AUTO_INCREMENT column. Inserted lues cannot be logged correctly",
      "Statement is unsafe because it uses a UDF which may not return the same value on the slave",
      "Statement is unsafe because it uses a system variable that may have a different value on the slave",
      "Statement is unsafe because it uses a system function that may return a different value on the slave",
      "Statement is unsafe because it accesses a non-transactional table after accessing a transactional table within the same ansaction",
      "%s Statement: %s",
      "Column %d of table \'%-.192s.%-.192s\' cannot be converted from type \'%-.50s\' to type \'%-.50s\'",
      "Can\'t create conversion table for table \'%-.192s.%-.192s\'",
      "Cannot modify @@session.binlog_format inside a transaction",
      "The path specified for %.64T is too long",
      "\'%s\' is deprecated and will be removed in a future release",
      "Native table \'%-.64s\'.\'%-.64s\' has the wrong structure",
      "Invalid performance_schema usage",
      "Table \'%s\'.\'%s\' was skipped since its definition is being modified by concurrent DDL statement",
      "Cannot modify @@session.binlog_direct_non_transactional_updates inside a transaction",
      "Cannot change the binlog direct flag inside a stored function or trigger",
      "A SPATIAL index may only contain a geometrical type column",
      "Comment for index \'%-.64s\' is too long (max = %lu)",
      "Wait on a lock was aborted due to a pending exclusive lock",
      "%s value is out of range in \'%s\'",
      "A variable of a non-integer based type in LIMIT clause",
      "Mixing self-logging and non-self-logging engines in a statement is unsafe",
      "Statement accesses nontransactional table as well as transactional or temporary table, and writes to any of them",
      "Cannot modify @@session.sql_log_bin inside a transaction",
      "Cannot change the sql_log_bin inside a stored function or trigger",
      "Failed to read from the .par file",
      "VALUES value for partition \'%-.64s\' must have type INT",
      "Access denied for user \'%s\'@\'%s\'",
      "SET PASSWORD is ignored for users authenticating via %s plugin",
      "GRANT with IDENTIFIED WITH is illegal because the user %-.*s already exists",
      "Cannot truncate a table referenced in a foreign key constraint (%.192s)",
      "Plugin \'%s\' is force_plus_permanent and can not be unloaded",
      "The requested value for the heartbeat period is less than 1 millisecond. The value is reset to 0, meaning that artbeating will effectively be disabled",
      "The requested value for the heartbeat period exceeds the value of `slave_net_timeout\' seconds. A sensible value for e period should be less than the timeout",
      "Multi-row statements required more than \'max_binlog_stmt_cache_size\' bytes of storage.",
      "Primary key/partition key update is not allowed since the table is updated both as \'%-.192s\' and \'%-.192s\'",
      "Table rebuild required. Please do \"ALTER TABLE %`s FORCE\" or dump/reload to fix it!",
      "The value of \'%s\' should be no less than the value of \'%s\'",
      "Index column size too large. The maximum column size is %lu bytes",
      "Trigger \'%-.64s\' has an error in its body: \'%-.256s\'",
      "Unknown trigger has an error in its body: \'%-.256s\'",
      "Index %s is corrupted",
      "Undo log record is too big",
      "INSERT IGNORE... SELECT is unsafe because the order in which rows are retrieved by the SELECT determines which (if any) ws are ignored. This order cannot be predicted and may differ on master and the slave",
      "INSERT... SELECT... ON DUPLICATE KEY UPDATE is unsafe because the order in which rows are retrieved by the SELECT termines which (if any) rows are updated. This order cannot be predicted and may differ on master and the slave",
      "REPLACE... SELECT is unsafe because the order in which rows are retrieved by the SELECT determines which (if any) rows are placed. This order cannot be predicted and may differ on master and the slave",
      "CREATE... IGNORE SELECT is unsafe because the order in which rows are retrieved by the SELECT determines which (if any) ws are ignored. This order cannot be predicted and may differ on master and the slave",
      "CREATE... REPLACE SELECT is unsafe because the order in which rows are retrieved by the SELECT determines which (if any) ws are replaced. This order cannot be predicted and may differ on master and the slave",
      "UPDATE IGNORE is unsafe because the order in which rows are updated determines which (if any) rows are ignored. This order cannot  predicted and may differ on master and the slave",
      "You should never see it",
      "You should never see it",
      "Statements writing to a table with an auto-increment column after selecting from another table are unsafe because the order  which rows are retrieved determines what (if any) rows will be written. This order cannot be predicted and may differ on master and the slave",
      "CREATE TABLE... SELECT...  on a table with an auto-increment column is unsafe because the order in which rows are trieved by the SELECT determines which (if any) rows are inserted. This order cannot be predicted and may differ on master and the slave",
      "INSERT... ON DUPLICATE KEY UPDATE  on a table with more than one UNIQUE KEY is unsafe",
      "You should never see it",
      "Not allowed for system-versioned table %`s.%`s",
      "INSERT into autoincrement field which is not the first part in the composed primary key is unsafe",
      "Cannot load from %s.%s. The table is probably corrupted",
      "The requested value %lu for the master delay exceeds the maximum %lu",
      "Only Format_description_log_event and row events are allowed in BINLOG statements (but %s was provided)",
      "Non matching attribute \'%-.64s\' between partition and table",
      "Table to exchange with partition is partitioned: \'%-.64s\'",
      "Table to exchange with partition is temporary: \'%-.64s\'",
      "Subpartitioned table, use subpartition instead of partition",
      "Unknown partition \'%-.64s\' in table \'%-.64s\'",
      "Tables have different definitions",
      "Found a row that does not match the partition",
      "Option binlog_cache_size (%lu) is greater than max_binlog_cache_size (%lu); setting binlog_cache_size equal to x_binlog_cache_size",
      "Cannot use %-.64s access on index \'%-.64s\' due to type or collation conversion on field \'%-.64s\'",
      "Table to exchange with partition has foreign key references: \'%-.64s\'",
      "Key value \'%-.192s\' was not found in table \'%-.192s.%-.192s\'",
      "Too long value for \'%s\'",
      "Replication event checksum verification failed while reading from network",
      "Replication event checksum verification failed while reading from a log file",
      "Option binlog_stmt_cache_size (%lu) is greater than max_binlog_stmt_cache_size (%lu); setting binlog_stmt_cache_size ual to max_binlog_stmt_cache_size",
      "Can\'t update table \'%-.192s\' while \'%-.192s\' is being created",
      "PARTITION () clause on non partitioned table",
      "Found a row not matching the given partition set",
      "You should never see it",
      "Failure while changing the type of replication repository: %s",
      "The creation of some temporary tables could not be rolled back",
      "Some temporary tables were dropped, but these operations could not be rolled back",
      "%s is not supported in multi-threaded slave mode. %s",
      "The number of modified databases exceeds the maximum %d; the database names will not be included in the replication event tadata",
      "Cannot execute the current event group in the parallel mode. Encountered event %s, relay-log name %s, position %s which prevents execution  this event group in parallel mode. Reason: %s",
      "%s",
      "FULLTEXT index is not supported for partitioned tables",
      "Invalid condition number",
      "Sending passwords in plain text without SSL/TLS is extremely insecure",
      "Storing MariaDB user name or password information in the master.info repository is not secure and is therefore not recommended. Please e the MariaDB Manual for more about this issue and possible alternatives",
      "Foreign key constraint for table \'%.192s\', record \'%-.192s\' would lead to a duplicate entry in table \'%.192s\', key %.192s\'",
      "Foreign key constraint for table \'%.192s\', record \'%-.192s\' would lead to a duplicate entry in a child table",
      "Setting authentication options is not possible when only the Slave SQL Thread is being started",
      "The table does not have FULLTEXT index to support this query",
      "The system variable %.200s cannot be set in stored functions or triggers",
      "The system variable %.200s cannot be set when there is an ongoing transaction",
      "The system variable @@SESSION.GTID_NEXT has the value %.200s, which is not listed in @@SESSION.GTID_NEXT_LIST",
      "When @@SESSION.GTID_NEXT_LIST == NULL, the system variable @@SESSION.GTID_NEXT cannot change side a transaction",
      "The statement \'SET %.200s\' cannot invoke a stored function",
      "The system variable @@SESSION.GTID_NEXT cannot be \'AUTOMATIC\' when @@SESSION.GTID_NEXT_LIST is n-NULL",
      "Skipping transaction %.200s because it has already been executed and logged",
      "Malformed GTID set specification \'%.200s\'",
      "Malformed GTID set encoding",
      "Malformed GTID specification \'%.200s\'",
      "Impossible to generate Global Transaction Identifier: the integer component reached the maximal value. Restart the server with a new rver_uuid",
      "Parameters MASTER_LOG_FILE, MASTER_LOG_POS, RELAY_LOG_FILE and RELAY_LOG_POS cannot be set when MASTER_AUTO_POSITION is active",
      "CHANGE MASTER TO MASTER_AUTO_POSITION = 1 can only be executed when GTID_MODE = ON",
      "Cannot execute statements with implicit commit inside a transaction when GTID_NEXT != AUTOMATIC or ID_NEXT_LIST != NULL",
      "GTID_MODE = ON or GTID_MODE = UPGRADE_STEP_2 requires ENFORCE_GTID_CONSISTENCY = 1",
      "GTID_MODE = ON or UPGRADE_STEP_1 or UPGRADE_STEP_2 requires --log-bin and --log-slave-updates",
      "GTID_NEXT cannot be set to UUID:NUMBER when GTID_MODE = OFF",
      "GTID_NEXT cannot be set to ANONYMOUS when GTID_MODE = ON",
      "GTID_NEXT_LIST cannot be set to a non-NULL value when GTID_MODE = OFF",
      "Found a Gtid_log_event or Previous_gtids_log_event when GTID_MODE = OFF",
      "When ENFORCE_GTID_CONSISTENCY = 1, updates to non-transactional tables can only be done in either autocommitted statements  single-statement transactions, and never in the same statement as updates to transactional tables",
      "CREATE TABLE ... SELECT is forbidden when ENFORCE_GTID_CONSISTENCY = 1",
      "When ENFORCE_GTID_CONSISTENCY = 1, the statements CREATE TEMPORARY TABLE and DROP TEMPORARY TABLE can  executed in a non-transactional context only, and require that AUTOCOMMIT = 1",
      "The value of GTID_MODE can only change one step at a time: OFF <-> UPGRADE_STEP_1 <-> UPGRADE_STEP_2 <-> ON. Also te that this value must be stepped up or down simultaneously on all servers; see the Manual for instructions.",
      "The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing IDs that the slave requires",
      "GTID_NEXT cannot be changed by a client that owns a GTID. The client owns %s. Ownership is released on COMMIT or LLBACK",
      "Unknown %s format name: \'%s\'",
      "Cannot execute statement in a READ ONLY transaction",
      "Comment for table partition \'%-.64s\' is too long (max = %lu)",
      "Slave is not configured or failed to initialize properly. You must at least set --server-id to enable either a master or a slave. ditional error messages can be found in the MariaDB error log",
      "InnoDB presently supports one FULLTEXT index creation at a time",
      "Cannot create FULLTEXT index on temporary InnoDB table",
      "Column \'%-.192s\' is of wrong type for an InnoDB FULLTEXT index",
      "Index \'%-.192s\' is of wrong type for an InnoDB FULLTEXT index",
      "Creating index \'%-.192s\' required more than \'innodb_online_alter_log_max_size\' bytes of modification log. Please try again",
      "Unknown ALGORITHM \'%s\'",
      "Unknown LOCK type \'%s\'",
      "CHANGE MASTER cannot be executed when the slave was stopped with an error or killed in MTS mode. Consider using RESET AVE or START SLAVE UNTIL",
      "Cannot recover after SLAVE errored out in parallel execution mode. Additional error messages can be found in the MariaDB error log",
      "Cannot clean up worker info tables. Additional error messages can be found in the MariaDB error log",
      "Column count of %s.%s is wrong. Expected %d, found %d. The table is probably corrupted",
      "Slave must silently retry current transaction",
      "You should never see it",
      "Schema mismatch (%s)",
      "Table %-.192s in system tablespace",
      "IO Read error: (%lu, %s) %s",
      "IO Write error: (%lu, %s) %s",
      "Tablespace is missing for table \'%-.192s\'",
      "Tablespace for table \'%-.192s\' exists. Please DISCARD the tablespace before IMPORT",
      "Tablespace has been discarded for table %`s",
      "Internal error: %-.192s",
      "ALTER TABLE \'%-.192s\' IMPORT TABLESPACE failed with error %lu : \'%s\'",
      "Index corrupt: %s",
      "YEAR(%lu) column type is deprecated. Creating YEAR(4) column instead",
      "Your password does not satisfy the current policy requirements (%s)",
      "You must SET PASSWORD before executing this statement",
      "Failed to add the foreign key constraint. Missing index for constraint \'%s\' in the foreign table \'%s\'",
      "Failed to add the foreign key constraint. Missing index for constraint \'%s\' in the referenced table \'%s\'",
      "Failed to add the foreign key constraint \'%s\' to system tables",
      "Failed to open the referenced table \'%s\'",
      "Failed to add the foreign key constraint on table \'%s\'. Incorrect options in FOREIGN KEY constraint \'%s\'",
      "Duplicate %s constraint name \'%s\'",
      "The password hash doesn\'t have the expected format. Check if the correct password algorithm is being used with the PASSWORD() function",
      "Cannot drop column \'%-.192s\': needed in a foreign key constraint \'%-.192s\'",
      "Cannot drop column \'%-.192s\': needed in a foreign key constraint \'%-.192s\' of table %-.192s",
      "Column \'%-.192s\' cannot be NOT NULL: needed in a foreign key constraint \'%-.192s\' SET NULL",
      "Duplicate index %`s. This is deprecated and will be disallowed in a future release",
      "Cannot change column \'%-.192s\': used in a foreign key constraint \'%-.192s\'",
      "Cannot change column \'%-.192s\': used in a foreign key constraint \'%-.192s\' of table \'%-.192s\'",
      "Cannot delete rows from table which is parent in a foreign key constraint \'%-.192s\' of table \'%-.192s\'",
      "Malformed communication packet",
      "Running in read-only mode",
      "When GTID_NEXT is set to a GTID, you must explicitly set it again after a COMMIT or ROLLBACK. If you see this error message in e slave SQL thread, it means that a table in the current transaction is transactional on the master and non-transactional on the slave. In a client connection, it means at you executed SET GTID_NEXT before a transaction and forgot to set GTID_NEXT to a different identifier or to \'AUTOMATIC\' after COMMIT or ROLLBACK. Current GTID_NEXT is %s\'",
      "The system variable %.200s cannot be set in stored procedures",
      "GTID_PURGED can only be set when GTID_MODE = ON",
      "GTID_PURGED can only be set when GTID_EXECUTED is empty",
      "GTID_PURGED can only be set when there are no ongoing transactions (not even in other clients)",
      "GTID_PURGED was changed from \'%s\' to \'%s\'",
      "GTID_EXECUTED was changed from \'%s\' to \'%s\'",
      "Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT, and both replicated and non plicated tables are written to",
      "%s is not supported for this operation. Try %s",
      "%s is not supported. Reason: %s. Try %s",
      "COPY algorithm requires a lock",
      "Partition specific operations do not yet support LOCK/ALGORITHM",
      "Columns participating in a foreign key are renamed",
      "Cannot change column type",
      "Adding foreign keys needs foreign_key_checks=OFF",
      "Creating unique indexes with IGNORE requires COPY algorithm to remove duplicate rows",
      "Dropping a primary key is not allowed without also adding a new primary key",
      "Adding an auto-increment column requires a lock",
      "Cannot replace hidden FTS_DOC_ID with a user-visible one",
      "Cannot drop or rename FTS_DOC_ID",
      "Fulltext index creation requires a lock",
      "sql_slave_skip_counter can not be set when the server is running with GTID_MODE = ON. Instead, for each ansaction that you want to skip, generate an empty transaction with the same GTID as the transaction",
      "Duplicate entry for key \'%-.192s\'",
      "Long database name and identifier for object resulted in path length exceeding %d characters. Path: \'%s\'",
      "cannot convert NULL to non-constant DEFAULT",
      "Your password has expired. To log in you must change it using a client that supports expired passwords",
      "Found a row in wrong partition %s",
      "Cannot schedule event %s, relay-log name %s, position %s to Worker thread because its size %lu exceeds %lu of ave_pending_jobs_size_max",
      "Cannot CREATE FULLTEXT INDEX WITH PARSER on InnoDB table",
      "The binary log file \'%s\' is logically corrupted: %s",
      "file %s was not purged because it was being read by %d thread(s), purged only %d out of %d files",
      "file %s was not purged because it is the active log file",
      "Auto-increment value in UPDATE conflicts with internally generated values",
      "Row events are not logged for %s statements that modify BLACKHOLE tables in row format. Table(s): \'%-.192s\'",
      "Slave failed to initialize master info structure from the repository",
      "Slave failed to initialize relay log info structure from the repository",
      "Access denied trying to change to user \'%-.48s\'@\'%-.64s\' (using password: %s). Disconnecting",
      "InnoDB is in read only mode",
      "STOP SLAVE command execution is incomplete: Slave SQL thread got the stop signal, thread is busy, SQL thread will stop once the rrent task is complete",
      "STOP SLAVE command execution is incomplete: Slave IO thread got the stop signal, thread is busy, IO thread will stop once the rrent task is complete",
      "Operation cannot be performed. The table \'%-.64s.%-.64s\' is missing, corrupt or contains bad data",
      "Temporary file write failure",
      "Upgrade index name failed, please use create index(alter table) algorithm copy to rebuild index",
      "\"",
      "\"",
      "Function or expression \'%s\' cannot be used in the %s clause of %`s",
      "\"",
      "Primary key cannot be defined upon a generated column",
      "Key/Index cannot be defined on a virtual generated column",
      "Cannot define foreign key with %s clause on a generated column",
      "The value specified for generated column \'%s\' in table \'%s\' has been ignored",
      "This is not yet supported for generated columns",
      "\"",
      "\"",
      "%s storage engine does not support generated columns",
      "Unknown option \'%-.64s\'",
      "Incorrect value \'%-.64T\' for option \'%-.64s\'",
      "You should never see it",
      "You should never see it",
      "You should never see it",
      "Got overflow when converting \'%-.128s\' to %-.32s. Value truncated",
      "Truncated value \'%-.128s\' when converting to %-.32s",
      "Encountered illegal value \'%-.128s\' when converting to %-.32s",
      "Encountered illegal format of dynamic column string",
      "Dynamic column implementation limit reached",
      "Illegal value used as argument of dynamic column function",
      "Dynamic column contains unknown character set",
      "At least one of the \'in_to_exists\' or \'materialization\' optimizer_switch flags must be \'on\'",
      "Query cache is disabled (resize or similar command in progress); repeat this command later",
      "Query cache is globally disabled and you can\'t enable it only for this session",
      "View \'%-.192s\'.\'%-.192s\' ORDER BY clause ignored because there is other ORDER BY clause already",
      "Connection was killed",
      "You should never see it",
      "Cannot modify @@session.skip_replication inside a transaction",
      "Cannot modify @@session.skip_replication inside a stored function or trigger",
      "Query execution was interrupted. The query examined at least %llu rows, which exceeds LIMIT ROWS EXAMINED (%llu). The query sult may be incomplete",
      "Table \'%-.192s.%-.192s\' doesn\'t exist in engine",
      "Target is not executing an operation with a query plan",
      "Connection \'%.*s\' conflicts with existing connection \'%.*s\'",
      "Master \'%.*s\': ",
      "Can\'t %s SLAVE \'%.*s\'",
      "SLAVE \'%.*s\' started",
      "SLAVE \'%.*s\' stopped",
      "Engine %s failed to discover table %`-.192s.%`-.192s with \'%s\'",
      "Failed initializing replication GTID state",
      "Could not parse GTID list",
      "Could not update replication slave gtid state",
      "GTID %u-%u-%llu and %u-%u-%llu conflict (duplicate domain id %u)",
      "Failed to open %s.%s",
      "Connecting slave requested to start from GTID %u-%u-%llu, which is not in the master\'s binlog",
      "Failed to load replication slave GTID position from table %s.%s",
      "Specified GTID %u-%u-%llu conflicts with the binary log which contains a more recent GTID %u-%u-%llu. If STER_GTID_POS=CURRENT_POS is used, the binlog position will override the new value of @@gtid_slave_pos",
      "Specified value for @@gtid_slave_pos contains no value for replication domain %u. This conflicts with the binary log which ntains GTID %u-%u-%llu. If MASTER_GTID_POS=CURRENT_POS is used, the binlog position will override the new value of @@gtid_slave_pos",
      "START SLAVE UNTIL master_gtid_pos requires that slave is using GTID",
      "An attempt was made to binlog GTID %u-%u-%llu which would create an out-of-order sequence number with existing GTID %u-%u-%llu, and id strict mode is enabled",
      "The binlog on the master is missing the GTID %u-%u-%llu requested by the slave (even though a subsequent sequence number does ist), and GTID strict mode is enabled",
      "Unexpected GTID received from master after reconnect. This normally indicates that the master server was replaced without starting the slave threads. %s",
      "Cannot modify @@session.gtid_domain_id or @@session.gtid_seq_no inside a transaction",
      "Cannot modify @@session.gtid_domain_id or @@session.gtid_seq_no inside a stored function or trigger",
      "Connecting slave requested to start from GTID %u-%u-%llu, which is not in the master\'s binlog. Since the master\'s binlog ntains GTIDs with higher sequence numbers, it probably means that the slave has diverged due to executing extra erroneous transactions",
      "This operation is not allowed if any GTID has been logged to the binary log. Run RESET MASTER first to erase the log",
      "Unknown query id: %lld",
      "Bad base64 data as position %u",
      "Invalid role specification %`s",
      "The current user is invalid",
      "Cannot grant role \'%s\' to: %s",
      "Cannot revoke role \'%s\' from: %s",
      "Cannot change @@slave_parallel_threads while another change is in progress",
      "Commit failed due to failure of an earlier commit on which this one depends",
      "\'%-.192s\' is a view",
      "When using parallel replication and GTID with multiple replication domains, @@sql_slave_skip_counter can not be used. Instead, setting gtid_slave_pos explicitly can be used to skip to after a given GTID position",
      "The definition for table %`s is too big",
      "Plugin \'%-.192s\' already installed",
      "Query execution was interrupted (max_statement_time exceeded)",
      "%s does not support subqueries or stored functions",
      "The system variable %.200s cannot be set in SET STATEMENT.",
      "You should never see it",
      "Can\'t create user \'%-.64s\'@\'%-.64s\'; it already exists",
      "Can\'t drop user \'%-.64s\'@\'%-.64s\'; it doesn\'t exist",
      "Can\'t create role \'%-.64s\'; it already exists",
      "Can\'t drop role \'%-.64s\'; it doesn\'t exist",
      "Cannot convert \'%s\' character 0x%-.64s to \'%s\'",
      "Incorrect default value \'%-.128T\' for column \'%.192s\'",
      "You are not owner of query %lu",
      "Engine-independent statistics are not collected for column \'%s\'",
      "Aggregate function \'%-.192s)\' of SELECT #%d belongs to SELECT #%d",
      "<%-.64s> option ignored for InnoDB partition",
      "File %s is corrupted",
      "Query partially completed on the master (error on master: %d) and was aborted. There is a chance that your master is inconsistent at this int. If you are sure that your master is ok, run this query manually on the slave and then restart the slave with SET GLOBAL SQL_SLAVE_SKIP_COUNTER=1; START SLAVE;. ery:\'%s\'",
      "Query caused different errors on master and slave. Error on master: message (format)=\'%s\' error code=%d; Error on slave:actual ssage=\'%s\', error code=%d. Default database:\'%s\'. Query:\'%s\'",
      "Storage engine for table \'%s\'.\'%s\' is not loaded.",
      "GET STACKED DIAGNOSTICS when handler not active",
      "%s is no longer supported. The statement was converted to %s.",
      "Statement is unsafe because it uses a fulltext parser plugin which may not return the same value on the slave.",
      "Cannot DISCARD/IMPORT tablespace associated with temporary table",
      "Foreign key cascade delete/update exceeds max depth of %d.",
      "Column count of %s.%s is wrong. Expected %d, found %d. Created with MariaDB %d, now running %d. Please use riadb-upgrade to fix this error.",
      "Trigger %s.%s.%s does not have CREATED attribute.",
      "Referenced trigger \'%s\' for the given action time and event type does not exist.",
      "EXPLAIN FOR CONNECTION command is supported only for SELECT/UPDATE/INSERT/DELETE/REPLACE",
      "Invalid size for column \'%-.192s\'.",
      "Table storage engine \'%-.64s\' found required create option missing",
      "Out of memory in storage engine \'%-.64s\'.",
      "The password for anonymous user cannot be expired.",
      "This operation cannot be performed with a running slave sql thread; run STOP SLAVE SQL_THREAD first",
      "Cannot create FULLTEXT index on materialized subquery",
      "Undo Log error: %s",
      "Invalid argument for logarithm",
      "This operation cannot be performed with a running slave io thread; run STOP SLAVE IO_THREAD FOR CHANNEL \'%s\' first.",
      "This operation may not be safe when the slave has temporary tables. The tables will be kept open until the server restarts  until the tables are deleted by any replicated DROP statement. Suggest to wait until slave_open_temp_tables = 0.",
      "CHANGE MASTER TO with a MASTER_LOG_FILE clause but no MASTER_LOG_POS clause may not be safe. The old position value may not  valid for the new binary log file.",
      "Query execution was interrupted, maximum statement execution time exceeded",
      "Select is not a read only statement, disabling timer",
      "Duplicate entry \'%-.192s\'.",
      "\'%s\' mode no longer has any effect. Use STRICT_ALL_TABLES or STRICT_TRANS_TABLES instead.",
      "Expression #%u of ORDER BY contains aggregate function and applies to a UNION",
      "Expression #%u of ORDER BY contains aggregate function and applies to the result of a non-aggregated query",
      "Slave worker has stopped after at least one previous worker encountered an error when slave-preserve-commit-order was abled. To preserve commit order, the last transaction executed by this thread has not been committed. When restarting the slave after fixing any failed threads, you should x this worker as well.",
      "slave_preserve_commit_order is not supported %s.",
      "The server is currently in offline mode",
      "Binary geometry function %s given two geometries of different srids: %u and %u, which should have been identical.",
      "Calling geometry function %s with unsupported types of arguments.",
      "Unknown GIS error occurred in function %s.",

  };

  static const char *errmsg_list_1[]= {
      "Unknown exception caught in GIS function %s.",
      "Invalid GIS data provided to function %s.",
      "The geometry has no data in function %s.",
      "Unable to calculate centroid because geometry is empty in function %s.",
      "Geometry overlay calculation error: geometry data is invalid in function %s.",
      "Geometry turn info calculation error: geometry data is invalid in function %s.",
      "Analysis procedures of intersection points interrupted unexpectedly in function %s.",
      "Unknown exception thrown in function %s.",
      "Memory allocation error: %-.256s in function %s.",
      "Domain error: %-.256s in function %s.",
      "Length error: %-.256s in function %s.",
      "Invalid argument error: %-.256s in function %s.",
      "Out of range error: %-.256s in function %s.",
      "Overflow error: %-.256s in function %s.",
      "Range error: %-.256s in function %s.",
      "Underflow error: %-.256s in function %s.",
      "Logic error: %-.256s in function %s.",
      "Runtime error: %-.256s in function %s.",
      "Unknown exception: %-.384s in function %s.",
      "Geometry byte string must be little endian.",
      "The password provided for the replication user exceeds the maximum length of 32 characters",
      "Incorrect user-level lock name \'%-.192s\'.",
      "Deadlock found when trying to get user-level lock; try rolling back transaction/releasing locks and restarting lock acquisition.",
      "REPLACE cannot be executed as it requires deleting rows that are not in the view",
      "Do not support online operation on table with GIS index",
      "This error never happens",
      "This error never happens",
      "WITH column list and SELECT field list have different column counts",
      "Too many WITH elements in WITH clause",
      "Duplicate query name %`-.64s in WITH clause",
      "No anchors for recursive WITH element \'%s\'",
      "Unacceptable mutual recursion with anchored table \'%s\'",
      "Reference to recursive WITH table \'%s\' in materialized derived",
      "Restrictions imposed on recursive definitions are violated for table \'%s\'",
      "Window specification with name \'%s\' is not defined",
      "Multiple window specifications with the same name \'%s\'",
      "Window specification referencing another one \'%s\' cannot contain partition list",
      "Referenced window specification \'%s\' already contains order list",
      "Referenced window specification \'%s\' cannot contain window frame",
      "Unacceptable combination of window frame bound specifications",
      "Window function is allowed only in SELECT list and ORDER BY clause",
      "Window function is not allowed in window specification",
      "Window frame is not allowed with \'%s\'",
      "No order list in window specification for \'%s\'",
      "RANGE-type frame requires ORDER BY clause with single sort key",
      "Integer is required for ROWS-type frame",
      "Numeric datatype is required for RANGE-type frame",
      "Frame exclusion is not supported yet",
      "This window function may not have a window frame",
      "Argument of NTILE must be greater than 0",
      "CONSTRAINT %`s failed for %`-.192s.%`-.192s",
      "Expression in the %s clause is too big",
      "Got an error evaluating stored expression %s",
      "Got an error when calculating default value for %`s",
      "Expression for field %`-.64s is referring to uninitialized field %`s",
      "Only one DEFAULT partition allowed",
      "Referenced trigger \'%s\' for the given action time and event type does not exist",
      "Default/ignore value is not supported for such parameter usage",
      "Only row based replication supported for bulk operations",
      "Uncompress the compressed binlog failed",
      "Broken JSON string in argument %d to function \'%s\' at position %d",
      "Character disallowed in JSON in argument %d to function \'%s\' at position %d",
      "Unexpected end of JSON text in argument %d to function \'%s\'",
      "Syntax error in JSON text in argument %d to function \'%s\' at position %d",
      "Incorrect escaping in JSON text in argument %d to function \'%s\' at position %d",
      "Limit of %d on JSON nested structures depth is reached in argument %d to function \'%s\' at position %d",
      "Unexpected end of JSON path in argument %d to function \'%s\'",
      "Syntax error in JSON path in argument %d to function \'%s\' at position %d",
      "Limit of %d on JSON path depth is reached in argument %d to function \'%s\' at position %d",
      "Wildcards or range in JSON path not allowed in argument %d to function \'%s\'",
      "JSON path should end with an array identifier in argument %d to function \'%s\'",
      "Argument 2 to function \'%s\' must be \"one\" or \"all\".",
      "InnoDB refuses to write tables with ROW_FORMAT=COMPRESSED or KEY_BLOCK_SIZE.",
      "Incorrect GeoJSON format specified for st_geomfromgeojson function.",
      "Incorrect GeoJSON format - too few points for linestring specified.",
      "Incorrect GeoJSON format - polygon not closed.",
      "Path expression \'$\' is not allowed in argument %d to function \'%s\'.",
      "A slave with the same server_uuid/server_id as this slave has connected to the master",
      "Flashback does not support %s %s",
      "Keys are out order during bulk load",
      "Bulk load rows overlap existing rows",
      "Can\'t execute updates on master with binlog_format != ROW.",
      "MyRocks supports only READ COMMITTED and REPEATABLE READ isolation levels. Please change from current isolation level %s",
      "When unique checking is disabled in MyRocks, INSERT,UPDATE,LOAD statements with clauses that update or replace the key (i.e. INSERT ON PLICATE KEY UPDATE, REPLACE) are not allowed. Query: %s",
      "Can\'t execute updates when you started a transaction with START TRANSACTION WITH CONSISTENT [ROCKSDB] SNAPSHOT.",
      "This transaction was rolled back and cannot be committed. Only supported operation is to roll it back, so all pending changes will be discarded. ease restart another transaction.",
      "MyRocks currently does not support ROLLBACK TO SAVEPOINT if modifying rows.",
      "Only REPEATABLE READ isolation level is supported for START TRANSACTION WITH CONSISTENT SNAPSHOT in RocksDB Storage gine.",
      "Unsupported collation on string indexed column %s.%s Use binary collation (%s).",
      "Table \'%s\' does not exist, but metadata information exists inside MyRocks. This is a sign of data inconsistency. Please check if \'%s.m\' exists, and try to restore it if it does not exist.",
      "Column family (\'%s\') flag (%d) is different from an existing flag (%d). Assign a new CF flag, or do not change existing CF flag.",
      "TTL duration (%s) in MyRocks must be an unsigned non-null 64-bit integer.",
      "Status error %d received from RocksDB: %s",
      "%s, Status error %d received from RocksDB: %s",
      "TTL support is currently disabled when table has a hidden PK.",
      "TTL column (%s) in MyRocks must be an unsigned non-null 64-bit integer, exist inside the table, and have an accompanying ttl duration.",
      "The per-index column family option has been deprecated",
      "MyRocks failed creating new key definitions during alter.",
      "MyRocks failed populating secondary key during alter.",
      "Window functions can not be used as arguments to group functions.",
      "OK packet too large",
      "Incorrect GeoJSON format - empty \'coordinates\' array.",
      "MyRocks doesn\'t currently support collations with \"No pad\" attribute.",
      "Illegal parameter data types %s and %s for operation \'%s\'",
      "Illegal parameter data type %s for operation \'%s\'",
      "Incorrect parameter count to cursor \'%-.192s\'",
      "Unknown structured system variable or ROW routine variable \'%-.*s\'",
      "Row variable \'%-.192s\' does not have a field \'%-.192s\'",
      "END identifier \'%-.192s\' does not match \'%-.192s\'",
      "Sequence \'%-.64s.%-.64s\' has run out",
      "Sequence \'%-.64s.%-.64s\' has out of range value for options",
      "Sequence \'%-.64s.%-.64s\' table structure is invalid (%s)",
      "Sequence \'%-.64s.%-.64s\' access error",
      "Sequences requires binlog_format mixed or row",
      "\'%-.64s.%-.64s\' is not a SEQUENCE",
      "\'%-.192s\' is not a SEQUENCE",
      "Unknown SEQUENCE: \'%-.300s\'",
      "Unknown VIEW: \'%-.300s\'",
      "Wrong INSERT into a SEQUENCE. One can only do single table INSERT into a sequence object (like with mariadb-dump).  If you want to ange the SEQUENCE, use ALTER SEQUENCE instead.",
      "At line %u in %s",
      "Subroutine \'%-.192s\' is declared in the package specification but is not defined in the package body",
      "Subroutine \'%-.192s\' has a forward declaration but is not defined",
      "Compressed column \'%-.192s\' can\'t be used in key specification",
      "Unknown compression method: %s",
      "The used table value constructor has a different number of values",
      "Field reference \'%-.192s\' can\'t be used in table value constructor",
      "Numeric datatype is required for %s function",
      "Argument to the %s function is not a constant for a partition",
      "Argument to the %s function does not belong to the range [0,1]",
      "%s function only accepts arguments that can be converted to numerical types",
      "Aggregate specific instruction (FETCH GROUP NEXT ROW) used in a wrong context",
      "Aggregate specific instruction(FETCH GROUP NEXT ROW) missing from the aggregate function",
      "Limit only accepts integer values",
      "Invisible column %`s must have a default value",
      "Rows matched: %ld  Changed: %ld  Inserted: %ld  Warnings: %ld",
      "%`s must be of type %s for system-versioned table %`s",
      "Transaction-precise system versioning for %`s is not supported",
      "You should never see it",
      "Wrong partitioning type, expected type: %`s",
      "Versioned table %`s.%`s: last HISTORY partition (%`s) is out of %s, need more HISTORY partitions",
      "Maybe missing parameters: %s",
      "Can only drop oldest partitions when rotating by INTERVAL",
      "You should never see it",
      "Partition %`s contains non-historical data",
      "Not allowed for system-versioned %`s.%`s. Change @@system_versioning_alter_history to proceed with ALTER.",
      "Not allowed for system-versioned %`s.%`s. Change to/from native system versioning engine is not supported.",
      "SYSTEM_TIME range selector is not allowed",
      "Conflicting FOR SYSTEM_TIME clauses in WITH RECURSIVE",
      "Table %`s must have at least one versioned column",
      "Table %`s is not system-versioned",
      "Wrong parameters for %`s: missing \'%s\'",
      "PERIOD FOR SYSTEM_TIME must use columns %`s and %`s",
      "Wrong parameters for partitioned %`s: wrong value for \'%s\'",
      "Wrong partitions for %`s: must have at least one HISTORY and exactly one last CURRENT",
      "TRX_ID %llu not found in `mysql.transaction_registry`",
      "Can not change system versioning field %`s",
      "Can not DROP SYSTEM VERSIONING for table %`s partitioned BY SYSTEM_TIME",
      "System-versioned tables in the %`s database are not supported",
      "Transaction registry is disabled",
      "Duplicate ROW %s column %`s",
      "Table %`s is already system-versioned",
      "You should never see it",
      "System-versioned tables do not support %s",
      "Transaction-precise system-versioned tables do not support partitioning by ROW START or ROW END",
      "The index file for table \'%-.192s\' is full",
      "The column %`s.%`s cannot be changed more than once in a single UPDATE statement",
      "Row with no elements is not allowed in table value constructor in this context",
      "SYSTEM_TIME partitions in table %`s does not support historical query",
      "%s index %`s does not support this operation",
      "Changing table options requires the table to be rebuilt",
      "Can\'t execute the command as you have a BACKUP STAGE active",
      "You must start backup with \"BACKUP STAGE START\"",
      "Backup stage \'%s\' is same or before current backup stage \'%s\'",
      "Backup stage \'%s\' failed",
      "Unknown backup stage: \'%s\'. Stage should be one of START, FLUSH, BLOCK_DDL, BLOCK_COMMIT or END",
      "User is blocked because of too many credential errors; unblock with \'FLUSH PRIVILEGES\'",
      "Access denied, this account is locked",
      "Application-time period table cannot be temporary",
      "Fields of PERIOD FOR %`s have different types",
      "Cannot specify more than one application-time period",
      "Period field %`s cannot be %s",
      "Period %`s is not found in table",
      "Column %`s used in period %`s specified in update SET list",
      "Can\'t DROP CONSTRAINT `%s`. Use DROP PERIOD `%s` for this",
      "Specified key part was too long; max key part length is %u bytes",
      "Comment for database \'%-.64s\' is too long (max = %u)",
      "Unknown data type: \'%-.64s\'",
      "Operator does not exists: \'%-.128s\'",
      "Table `%s.%s` history row start \'%s\' is later than row end \'%s\'",
      "%`s: STARTS is later than query time, first history partition may exceed INTERVAL value",
      "Galera replication not supported",
      "The used command is not allowed because the MariaDB server or client has disabled the local infile capability",
      "No secure transports are configured, unable to set --require_secure_transport=ON",
      "Slave SQL thread ignored the \'%s\' because table is shared",
      "AUTO_INCREMENT column %`s cannot be used in the UNIQUE index %`s",
      "Key %`s cannot explicitly include column %`s",
      "Key %`s cannot have WITHOUT OVERLAPS",
      "\'%-.128s\' is not allowed in this context",
      "Engine %s does not support rollback. Changes were committed during rollback call",
      "A primary key cannot be marked as IGNORE",
      "SKIP LOCKED makes this statement unsafe",
      "Field \'%s\' can\'t be set for JSON_TABLE \'%s\'.",
      "Every table function must have an alias.",
      "Can\'t store an array or an object in the scalar column \'%s\' of JSON_TABLE \'%s\'.",
      "Can\'t store multiple matches of the path in the column \'%s\' of JSON_TABLE \'%s\'.",
      "FETCH ... WITH TIES requires ORDER BY clause to be present",
      "Dropped orphan trigger \'%-.64s\', originally created for table: \'%-.192s\'",
      "Storage engine %s is disabled",
      "SFORMAT error: %s",
      "Convert partition is not supported for subpartitioned table.",
      "MariaDB tried to use the %s, but its provider plugin is not loaded",
      "Failed to parse histogram for table %s.%s: %s at offset %d.",
      "OUT or INOUT argument %d for function %s is not allowed here",
      "Replicated query \'%s\' table `%s.%s` can not be temporary",
      "Versioned table %`s.%`s: adding HISTORY partition(s) failed",
      "%s is implicitly changing the value of \'%s\' from \'%s\' to \'%s\'",
      "CHANGE MASTER TO option \'%s=%s\' is missing requirement %s",
      "Slave log event execution was interrupted (slave_max_statement_time exceeded)"
  };

  static const char **errmsg_list[] = {(const char**)errmsg_list_0, (const char**)errmsg_list_1};
  return (const char***)errmsg_list;
}

#endif // MYSQL_GLOBAL_ERRMSGS_INIT_H
