CREATE TABLE t (a INT, b INT, c INT, d INT, e INT, PRIMARY KEY(a, b, c, d), KEY(b, d)) ENGINE=myisam;
CREATE TEMPORARY TABLE a (a INT);
INSERT INTO a VALUES (10);
INSERT INTO a VALUES (9);
INSERT INTO a VALUES (8);
INSERT INTO a VALUES (7);
INSERT INTO a VALUES (6);
INSERT INTO a VALUES (5);
INSERT INTO a VALUES (4);
INSERT INTO a VALUES (3);
INSERT INTO a VALUES (2);
INSERT INTO a VALUES (1);
CREATE TEMPORARY TABLE b (a INT);
INSERT INTO b VALUES (5);
INSERT INTO b VALUES (4);
INSERT INTO b VALUES (3);
INSERT INTO b VALUES (2);
INSERT INTO b VALUES (1);
CREATE TEMPORARY TABLE c (a INT);
INSERT INTO c VALUES (5);
INSERT INTO c VALUES (4);
INSERT INTO c VALUES (3);
INSERT INTO c VALUES (2);
INSERT INTO c VALUES (1);
CREATE TEMPORARY TABLE d (a INT);
INSERT INTO d VALUES (10);
INSERT INTO d VALUES (9);
INSERT INTO d VALUES (8);
INSERT INTO d VALUES (7);
INSERT INTO d VALUES (6);
INSERT INTO d VALUES (5);
INSERT INTO d VALUES (4);
INSERT INTO d VALUES (3);
INSERT INTO d VALUES (2);
INSERT INTO d VALUES (1);
INSERT INTO t SELECT a.a, b.a, c.a, d.a, d.a FROM a, b, c, d ORDER BY a.a, b.a, c.a, d.a;
DROP TEMPORARY TABLE a, b, c, d;
ANALYZE TABLE t;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, d FROM t WHERE d < 2;
FLUSH STATUS;
SELECT b, d FROM t WHERE d < 2;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, d FROM t WHERE d < 2;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, d FROM t WHERE d < 2;
FLUSH STATUS;
SELECT b, d FROM t WHERE d < 2;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, d FROM t WHERE d < 2;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, d FROM t WHERE d < 2;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, d FROM t WHERE d < 2;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, d FROM t WHERE d < 2;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, d FROM t WHERE d > 4;
FLUSH STATUS;
SELECT b, d FROM t WHERE d > 4;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, d FROM t WHERE d > 4;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, d FROM t WHERE d > 4;
FLUSH STATUS;
SELECT b, d FROM t WHERE d > 4;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, d FROM t WHERE d > 4;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, d FROM t WHERE d > 4;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, d FROM t WHERE d > 4;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, d FROM t WHERE d > 4;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a = 5 AND d <= 3;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a = 5 AND d <= 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a = 5 AND d <= 3;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a = 5 AND d <= 3;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a = 5 AND d <= 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a = 5 AND d <= 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND d <= 3;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND d <= 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND d <= 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a = 5 AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a = 5 AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a = 5 AND d >= 98;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a = 5 AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a = 5 AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a = 5 AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND d >= 98;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
FLUSH STATUS;
SELECT a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
FLUSH STATUS;
SELECT a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a+1`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a+1`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a+1`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a+1`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND d < 3;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, c, d FROM t WHERE a = 5 AND d < 3;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND d < 3;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, c, d FROM t WHERE a = 5 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND d < 3;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a = b AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a = b AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a = b AND d >= 98;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a = b AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a = b AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a = b AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = b AND d >= 98;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = b AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = b AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT e FROM t WHERE a = 5 AND d <= 3;
FLUSH STATUS;
SELECT e FROM t WHERE a = 5 AND d <= 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT e FROM t WHERE a = 5 AND d <= 3;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT e FROM t WHERE a = 5 AND d <= 3;
FLUSH STATUS;
SELECT e FROM t WHERE a = 5 AND d <= 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT e FROM t WHERE a = 5 AND d <= 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `e` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `e` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ e FROM t WHERE a = 5 AND d <= 3;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ e FROM t WHERE a = 5 AND d <= 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ e FROM t WHERE a = 5 AND d <= 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `e` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `e` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT count(a), count(b), count(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT count(a), count(b), count(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT count(a), count(b), count(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT count(a), count(b), count(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT count(a), count(b), count(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT count(a), count(b), count(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `count(a)`,`count(b)`,`count(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `count(a)`,`count(b)`,`count(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ count(a), count(b), count(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ count(a), count(b), count(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ count(a), count(b), count(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `count(a)`,`count(b)`,`count(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `count(a)`,`count(b)`,`count(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT min(a), max(b), min(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT min(a), max(b), min(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT min(a), max(b), min(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT min(a), max(b), min(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT min(a), max(b), min(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT min(a), max(b), min(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `min(a)`,`max(b)`,`min(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `min(a)`,`max(b)`,`min(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ min(a), max(b), min(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ min(a), max(b), min(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ min(a), max(b), min(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `min(a)`,`max(b)`,`min(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `min(a)`,`max(b)`,`min(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT sum(a), sum(b), sum(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT sum(a), sum(b), sum(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT sum(a), sum(b), sum(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT sum(a), sum(b), sum(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT sum(a), sum(b), sum(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT sum(a), sum(b), sum(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `sum(a)`,`sum(b)`,`sum(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `sum(a)`,`sum(b)`,`sum(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ sum(a), avg(b), sum(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ sum(a), avg(b), sum(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ sum(a), avg(b), sum(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `sum(a)`,`avg(b)`,`sum(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `sum(a)`,`sum(b)`,`sum(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT count(*) FROM t WHERE d < 2;;
FLUSH STATUS;
SELECT count(*) FROM t WHERE d < 2;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT count(*) FROM t WHERE d < 2;;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT count(*) FROM t WHERE d < 2;;
FLUSH STATUS;
SELECT count(*) FROM t WHERE d < 2;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT count(*) FROM t WHERE d < 2;;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `count(*)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `count(*)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ count(*) FROM t WHERE d < 2;;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ count(*) FROM t WHERE d < 2;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ count(*) FROM t WHERE d < 2;;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `count(*)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `count(*)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = default;
DROP TABLE t;
