CALL mtr.add_suppression("option 'log_error_verbosity'");
CALL mtr.add_suppression("--verbose is for use with");
SET @old_log_error_verbosity= @@global.log_error_verbosity;
SET @old_log_timestamps     = @@global.log_timestamps;
SELECT @@global.log_error_verbosity;
SET GLOBAL log_error_verbosity=DEFAULT;
SELECT @@global.log_error_verbosity;
SET GLOBAL log_error_verbosity=0;
SELECT @@global.log_error_verbosity;
SET GLOBAL log_error_verbosity=4;
SELECT @@global.log_error_verbosity;
SET SESSION log_error_verbosity=DEFAULT;
CREATE USER mysqltest_1;
SET GLOBAL log_error_verbosity=1;
SET GLOBAL log_timestamps=SYSTEM;
show session status;
DROP USER mysqltest_1;
SET GLOBAL  init_connect='wombat;';
CREATE USER mysqltest_yeslog;
CREATE USER mysqltest_nolog;
SET GLOBAL  log_error_verbosity=2;
SET GLOBAL  log_error_verbosity=1;
show session status;
show session status;
DROP USER mysqltest_yeslog;
DROP USER mysqltest_nolog;
SET GLOBAL  init_connect='';
SET GLOBAL  log_error_verbosity=2;
SET GLOBAL  log_error_verbosity=3;
SET GLOBAL  log_error_verbosity=DEFAULT;
SELECT      @@global.log_timestamps;
SET GLOBAL  log_timestamps=UTC;
SELECT      @@global.log_timestamps;
SET GLOBAL  log_timestamps=SYSTEM;
SELECT      @@global.log_timestamps;
SET GLOBAL  log_timestamps=DEFAULT;
SELECT      @@global.log_timestamps;
SET GLOBAL log_error_verbosity = @old_log_error_verbosity;
SET GLOBAL log_timestamps      = @old_log_timestamps;
FLUSH LOGS;
