set @orig_sql_mode= @@sql_mode;
drop table if exists t1;
create table t1(f1 int);
insert into t1 values (5);
create user ssl_user1@localhost, ssl_user2@localhost, ssl_user3@localhost, ssl_user4@localhost, ssl_user5@localhost;
grant select on test.* to ssl_user1@localhost, ssl_user2@localhost, ssl_user3@localhost, ssl_user4@localhost, ssl_user5@localhost;
alter user ssl_user2@localhost require cipher "TLS_AES_256_GCM_SHA384";
alter user ssl_user3@localhost require cipher "TLS_AES_256_GCM_SHA384" AND SUBJECT "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client";
alter user ssl_user4@localhost require cipher "TLS_AES_256_GCM_SHA384" AND SUBJECT "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client" ISSUER "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA";
alter user ssl_user5@localhost require cipher "TLS_AES_256_GCM_SHA384" AND SUBJECT "xxx";
flush privileges;
SHOW STATUS LIKE 'Ssl_cipher';
select * from t1;
delete from t1;
SHOW STATUS LIKE 'Ssl_cipher';
select * from t1;
delete from t1;
SHOW STATUS LIKE 'Ssl_cipher';
select * from t1;
delete from t1;
SHOW STATUS LIKE 'Ssl_cipher';
select * from t1;
delete from t1;
drop user ssl_user1@localhost, ssl_user2@localhost, ssl_user3@localhost, ssl_user4@localhost, ssl_user5@localhost;
drop table t1;
DROP TABLE IF EXISTS thread_status;
DROP EVENT IF EXISTS event_status;
SELECT COUNT(*) = 1 FROM information_schema.processlist WHERE user = 'event_scheduler' AND command = 'Daemon';
CREATE EVENT event_status ON SCHEDULE AT NOW() ON COMPLETION NOT PRESERVE DO BEGIN CREATE TABLE thread_status SELECT variable_name, variable_value FROM performance_schema.session_status WHERE variable_name LIKE 'SSL_ACCEPTS' OR variable_name LIKE 'SSL_CALLBACK_CACHE_HITS'; END;
SELECT variable_name, variable_value FROM thread_status;
DROP TABLE thread_status;
CREATE TABLE t1(a int);
INSERT INTO t1 VALUES (1), (2);
DROP TABLE t1;
select 'is still running; no cipher request crashed the server' as result from dual;
CREATE USER bug42158@localhost REQUIRE X509;
GRANT SELECT ON test.* TO bug42158@localhost;
FLUSH PRIVILEGES;
SHOW STATUS LIKE 'Ssl_cipher';
DROP USER bug42158@localhost;
set sql_mode= @orig_sql_mode;
