SET PERSIST_ONLY ssl_ca = 'mohit';
CALL mtr.add_suppression('Failed to set up SSL because of the following SSL library error');
CALL mtr.add_suppression('Failed to initialize TLS for channel: mysql_main');
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
SELECT @@global.ssl_ca;
SHOW STATUS LIKE '%tls_ca';
SHOW STATUS LIKE 'ssl_cipher';
RESET PERSIST;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
