SET @@tmpdir= 'no/such/directory';
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
CALL mtr.add_suppression("Cannot create temporary merge file");
SET @@innodb_tmpdir= NULL;
CREATE TABLE test.t(a text);
ALTER TABLE test.t ADD fulltext(a);
DROP TABLE test.t;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
