CREATE USER u1@localhost IDENTIFIED BY 'foo';
CREATE USER u2@localhost IDENTIFIED BY 'foo';
CREATE ROLE r1, r2;
GRANT SYSTEM_VARIABLES_ADMIN ON *.* TO u1@localhost;
GRANT r1 TO u1@localhost;
GRANT r2 TO u2@localhost;
SET ROLE r1;
SET GLOBAL binlog_cache_size=100;
SET GLOBAL binlog_cache_size=DEFAULT;
SET ROLE r2;
SET GLOBAL binlog_cache_size=100;
DROP USER u1@localhost, u2@localhost;
DROP ROLE r2,r1;
