CREATE TABLE t (a INT PRIMARY KEY, b INT, FAMILY (a), FAMILY (b) );
INSERT INTO t VALUES (1,1);
CREATE INDEX foo ON t (b);
CREATE INDEX bar ON t (b, b);
INSERT INTO t VALUES (2,1);
CREATE UNIQUE INDEX bar ON t (b);
CREATE INDEX b_desc ON t (b DESC);
