CREATE TABLE foo (j INT);
BEGIN; ALTER TABLE foo ADD CONSTRAINT check_not_negative CHECK (j >= 0); ALTER TABLE foo RENAME COLUMN j TO i; COMMIT;
BEGIN; CREATE INDEX ON foo(i) WHERE i > 0; ALTER TABLE foo RENAME COLUMN i TO j; COMMIT;
INSERT INTO foo(j) VALUES (1);
SELECT j, k FROM foo;
