#pragma once
#ifndef __DEFINE_H__
#define __DEFINE_H__

#define ALLTYPE(V)                                                             \
  /* New one here!!! */         \
  V(kStmt)      \
  V(kToplevelStmt)      \
  V(kSchemaStmt)      \
  V(kRoutineBodyStmt)      \
  V(kAlterEventTrigStmt)      \
  V(kAlterCollationStmt)      \
  V(kAlterDatabaseStmt)      \
  V(kAlterDatabaseSetStmt)      \
  V(kAlterDomainStmt)      \
  V(kAlterEnumStmt)      \
  V(kAlterFdwStmt)      \
  V(kAlterForeignServerStmt)      \
  V(kAlterGroupStmt)      \
  V(kAlterObjectDependsStmt)      \
  V(kAlterObjectSchemaStmt)      \
  V(kAlterOwnerStmt)      \
  V(kAlterOperatorStmt)      \
  V(kAlterTypeStmt)      \
  V(kAlterSeqStmt)      \
  V(kAlterSystemStmt)      \
  V(kAlterTableStmt)      \
  V(kAlterTblSpcStmt)      \
  V(kAlterExtensionStmt)      \
  V(kAlterExtensionContentsStmt)      \
  V(kAlterCompositeTypeStmt)      \
  V(kAlterUserMappingStmt)      \
  V(kAlterRoleStmt)      \
  V(kAlterRoleSetStmt)      \
  V(kAlterPolicyStmt)      \
  V(kAlterStatsStmt)      \
  V(kAlterDefaultPrivilegesStmt)      \
  V(kDefACLAction)      \
  V(kAnalyzeStmt)      \
  V(kCallStmt)      \
  V(kClosePortalStmt)      \
  V(kClusterStmt)      \
  V(kCommentStmt)      \
  V(kConstraintsSetStmt)      \
  V(kCopyStmt)      \
  V(kCreateAsStmt)      \
  V(kCreateCastStmt)      \
  V(kCreateDomainStmt)      \
  V(kCreateExtensionStmt)      \
  V(kCreateGroupStmt)      \
  V(kCreateOpClassStmt)      \
  V(kCreateOpFamilyStmt)      \
  V(kAlterOpFamilyStmt)      \
  V(kCreatePLangStmt)      \
  V(kCreateSchemaStmt)      \
  V(kCreateSeqStmt)      \
  V(kCreateStmt)      \
  V(kCreateStatsStmt)      \
  V(kCreateTableSpaceStmt)      \
  V(kCreateFdwStmt)      \
  V(kCreateForeignServerStmt)      \
  V(kCreateForeignTableStmt)      \
  V(kCreateAssertionStmt)      \
  V(kCreateTransformStmt)      \
  V(kCreateTrigStmt)      \
  V(kCreateEventTrigStmt)      \
  V(kCreateUserStmt)      \
  V(kCreateUserMappingStmt)      \
  V(kCreateRoleStmt)      \
  V(kCreatePolicyStmt)      \
  V(kCreatedbStmt)      \
  V(kDeclareCursorStmt)      \
  V(kDefineStmt)      \
  V(kDeleteStmt)      \
  V(kDiscardStmt)      \
  V(kDoStmt)      \
  V(kDropOpClassStmt)      \
  V(kDropOpFamilyStmt)      \
  V(kDropStmt)      \
  V(kDropCastStmt)      \
  V(kDropRoleStmt)      \
  V(kDropdbStmt)      \
  V(kDropTableSpaceStmt)      \
  V(kDropTransformStmt)      \
  V(kDropUserMappingStmt)      \
  V(kExplainStmt)      \
  V(kFetchStmt)      \
  V(kGrantStmt)      \
  V(kGrantRoleStmt)      \
  V(kImportForeignSchemaStmt)      \
  V(kIndexStmt)      \
  V(kInsertStmt)      \
  V(kListenStmt)      \
  V(kLoadStmt)      \
  V(kLockStmt)      \
  V(kNotifyStmt)      \
  V(kExplainableStmt)      \
  V(kPreparableStmt)      \
  V(kCreateFunctionStmt)      \
  V(kAlterFunctionStmt)      \
  V(kReindexStmt)      \
  V(kRemoveAggrStmt)      \
  V(kRemoveFuncStmt)      \
  V(kRemoveOperStmt)      \
  V(kRenameStmt)      \
  V(kReturnStmt)      \
  V(kRevokeStmt)      \
  V(kRevokeRoleStmt)      \
  V(kRuleActionStmt)      \
  V(kRuleActionStmtOrEmpty)      \
  V(kRuleStmt)      \
  V(kSecLabelStmt)      \
  V(kSelectStmt)      \
  V(kTransactionStmt)      \
  V(kTransactionStmtLegacy)      \
  V(kTruncateStmt)      \
  V(kUnlistenStmt)      \
  V(kUpdateStmt)      \
  V(kVacuumStmt)      \
  V(kVariableResetStmt)      \
  V(kVariableSetStmt)      \
  V(kVariableShowStmt)      \
  V(kViewStmt)      \
  V(kCheckPointStmt)      \
  V(kCreateConversionStmt)      \
  V(kDeallocateStmt)      \
  V(kPrepareStmt)      \
  V(kExecuteStmt)      \
  V(kDropOwnedStmt)      \
  V(kReassignOwnedStmt)      \
  V(kAlterTSConfigurationStmt)      \
  V(kAlterTSDictionaryStmt)      \
  V(kCreateMatViewStmt)      \
  V(kRefreshMatViewStmt)      \
  V(kCreateAmStmt)      \
  V(kCreatePublicationStmt)      \
  V(kAlterPublicationStmt)      \
  V(kCreateSubscriptionStmt)      \
  V(kAlterSubscriptionStmt)      \
  V(kDropSubscriptionStmt)      \
  V(kSelectNoParens)      \
  V(kSelectWithParens)      \
  V(kSelectClause)      \
  V(kSimpleSelect)      \
  V(kValuesClause)      \
  V(kPLpgSQLExpr)      \
  V(kPLAssignStmt)      \
  V(kAlterColumnDefault)      \
  V(kOpclassItem)      \
  V(kOpclassDrop)      \
  V(kAlterUsing)      \
  V(kAddDrop)      \
  V(kOptAscDesc)      \
  V(kOptNullsOrder)      \
  V(kAlterTableCmd)      \
  V(kAlterTypeCmd)      \
  V(kOptCollateClause)      \
  V(kReplicaIdentity)      \
  V(kPartitionCmd)      \
  V(kIndexPartitionCmd)      \
  V(kAlterTableCmds)      \
  V(kAlterTypeCmds)      \
  V(kAlterIdentityColumnOptionList)      \
  V(kAlterIdentityColumnOption)      \
  V(kOptDropBehavior)      \
  V(kCreatedbOptList)      \
  V(kCreatedbOptItems)      \
  V(kCopyOptList)      \
  V(kTransactionModeList)      \
  V(kCreateExtensionOptList)      \
  V(kAlterExtensionOptList)      \
  V(kCreatedbOptItem)      \
  V(kCopyOptItem)      \
  V(kTransactionModeItem)      \
  V(kCreateExtensionOptItem)      \
  V(kAlterExtensionOptItem)      \
  V(kOptLock)      \
  V(kLockType)      \
  V(kCastContext)      \
  V(kUtilityOptionName)      \
  V(kUtilityOptionElem)      \
  V(kUtilityOptionList)      \
  V(kUtilityOptionArg)      \
  V(kDropOption)      \
  V(kOptOrReplace)      \
  V(kOptNo)      \
  V(kOptGrantGrantOption)      \
  V(kOptGrantAdminOption)      \
  V(kOptNowait)      \
  V(kOptIfExists)      \
  V(kOptWithData)      \
  V(kOptTransactionChain)      \
  V(kOptNowaitOrSkip)      \
  V(kOptRoleList)      \
  V(kAlterOptRoleList)      \
  V(kCreateOptRoleElem)      \
  V(kAlterOptRoleElem)      \
  V(kOptType)      \
  V(kForeignServerVersion)      \
  V(kOptForeignServerVersion)      \
  V(kOptInDatabase)      \
  V(kOptSchemaName)      \
  V(kOptSchemaEltList)      \
  V(kAmType)      \
  V(kTriggerForSpec)      \
  V(kTriggerForType)      \
  V(kTriggerActionTime)      \
  V(kTriggerEvents)      \
  V(kTriggerOneEvent)      \
  V(kTriggerFuncArg)      \
  V(kTriggerWhen)      \
  V(kTransitionRelName)      \
  V(kTransitionRowOrTable)      \
  V(kTransitionOldOrNew)      \
  V(kTriggerTransition)      \
  V(kEventTriggerWhenList)      \
  V(kEventTriggerValueList)      \
  V(kEventTriggerWhenItem)      \
  V(kEnableTrigger)      \
  V(kCopyFileName)      \
  V(kAccessMethodClause)      \
  V(kAttrName)      \
  V(kTableAccessMethodClause)      \
  V(kName)      \
  V(kCursorName)      \
  V(kFileName)      \
  V(kOptIndexName)      \
  V(kClusterIndexSpecification)      \
  V(kFuncName)      \
  V(kHandlerName)      \
  V(kQualOp)      \
  V(kQualAllOp)      \
  V(kSubqueryOp)      \
  V(kOptClass)      \
  V(kOptInlineHandler)      \
  V(kOptValidator)      \
  V(kValidatorClause)      \
  V(kOptCollate)      \
  V(kQualifiedName)      \
  V(kInsertTarget)      \
  V(kOptConstrFromTable)      \
  V(kAllOp)      \
  V(kMathOp)      \
  V(kRowSecurityCmd)      \
  V(kRowSecurityDefaultForCmd)      \
  V(kRowSecurityDefaultPermissive)      \
  V(kRowSecurityOptionalWithCheck)      \
  V(kRowSecurityOptionalExpr)      \
  V(kRowSecurityDefaultToRole)      \
  V(kRowSecurityOptionalToRole)      \
  V(kIsoLevel)      \
  V(kOptEncoding)      \
  V(kGrantee)      \
  V(kGranteeList)      \
  V(kPrivilege)      \
  V(kPrivileges)      \
  V(kPrivilegeList)      \
  V(kPrivilegeTarget)      \
  V(kFunctionWithArgtypes)      \
  V(kAggregateWithArgtypes)      \
  V(kOperatorWithArgtypes)      \
  V(kFunctionWithArgtypesList)      \
  V(kAggregateWithArgtypesList)      \
  V(kOperatorWithArgtypesList)      \
  V(kDefaclPrivilegeTarget)      \
  V(kDefACLOption)      \
  V(kDefACLOptionList)      \
  V(kImportQualificationType)      \
  V(kImportQualification)      \
  V(kVacuumRelation)      \
  V(kOptSelectLimit)      \
  V(kSelectLimit)      \
  V(kLimitClause)      \
  V(kParseToplevel)      \
  V(kStmtmulti)      \
  V(kRoutineBodyStmtList)      \
  V(kOptTableElementList)      \
  V(kTableElementList)      \
  V(kOptInherit)      \
  V(kDefinition)      \
  V(kOptTypedTableElementList)      \
  V(kTypedTableElementList)      \
  V(kReloptions)      \
  V(kOptReloptions)      \
  V(kOptWith)      \
  V(kOptDefinition)      \
  V(kFuncArgs)      \
  V(kFuncArgsList)      \
  V(kFuncArgsWithDefaults)      \
  V(kFuncArgsWithDefaultsList)      \
  V(kAggrArgs)      \
  V(kAggrArgsList)      \
  V(kFuncAs)      \
  V(kCreatefuncOptList)      \
  V(kOptCreatefuncOptList)      \
  V(kAlterfuncOptList)      \
  V(kOldAggrDefinition)      \
  V(kOldAggrList)      \
  V(kOperArgtypes)      \
  V(kRuleActionList)      \
  V(kRuleActionMulti)      \
  V(kOptColumnList)      \
  V(kColumnList)      \
  V(kOptNameList)      \
  V(kSortClause)      \
  V(kOptSortClause)      \
  V(kSortbyList)      \
  V(kIndexParams)      \
  V(kStatsParams)      \
  V(kOptInclude)      \
  V(kOptCInclude)      \
  V(kIndexIncludingParams)      \
  V(kNameList)      \
  V(kRoleList)      \
  V(kFromClause)      \
  V(kFromList)      \
  V(kOptArrayBounds)      \
  V(kQualifiedNameList)      \
  V(kAnyName)      \
  V(kAnyNameList)      \
  V(kTypeNameList)      \
  V(kAnyOperator)      \
  V(kExprList)      \
  V(kAttrs)      \
  V(kDistinctClause)      \
  V(kOptDistinctClause)      \
  V(kTargetList)      \
  V(kOptTargetList)      \
  V(kInsertColumnList)      \
  V(kSetTargetList)      \
  V(kSetClauseList)      \
  V(kSetClause)      \
  V(kDefList)      \
  V(kOperatorDefList)      \
  V(kIndirection)      \
  V(kOptIndirection)      \
  V(kReloptionList)      \
  V(kTriggerFuncArgs)      \
  V(kOpclassItemList)      \
  V(kOpclassDropList)      \
  V(kOpclassPurpose)      \
  V(kOptOpfamily)      \
  V(kTransactionModeListOrEmpty)      \
  V(kOptTableFuncElementList)      \
  V(kTableFuncElementList)      \
  V(kOptTypeModifiers)      \
  V(kPrepTypeClause)      \
  V(kExecuteParamClause)      \
  V(kUsingClause)      \
  V(kReturningClause)      \
  V(kOptEnumValList)      \
  V(kEnumValList)      \
  V(kTableFuncColumnList)      \
  V(kCreateGenericOptions)      \
  V(kAlterGenericOptions)      \
  V(kRelationExprList)      \
  V(kDostmtOptList)      \
  V(kTransformElementList)      \
  V(kTransformTypeList)      \
  V(kTriggerTransitions)      \
  V(kTriggerReferencing)      \
  V(kVacuumRelationList)      \
  V(kOptVacuumRelationList)      \
  V(kDropOptionList)      \
  V(kOptRoutineBody)      \
  V(kGroupClause)      \
  V(kGroupByList)      \
  V(kGroupByItem)      \
  V(kRollupClause)      \
  V(kCubeClause)      \
  V(kGroupingSetsClause)      \
  V(kOptPublicationForTables)      \
  V(kPublicationForTables)      \
  V(kOptFdwOptions)      \
  V(kFdwOptions)      \
  V(kFdwOption)      \
  V(kOptTempTableName)      \
  V(kIntoClause)      \
  V(kCreateAsTarget)      \
  V(kCreateMvTarget)      \
  V(kCreatefuncOptItem)      \
  V(kCommonFuncOptItem)      \
  V(kDostmtOptItem)      \
  V(kFuncArg)      \
  V(kFuncArgWithDefault)      \
  V(kTableFuncColumn)      \
  V(kAggrArg)      \
  V(kArgClass)      \
  V(kFuncReturn)      \
  V(kFuncType)      \
  V(kOptTrusted)      \
  V(kOptRestartSeqs)      \
  V(kOptTemp)      \
  V(kOptNoLog)      \
  V(kOnCommitOption)      \
  V(kForLockingStrength)      \
  V(kForLockingItem)      \
  V(kForLockingClause)      \
  V(kOptForLockingClause)      \
  V(kForLockingItems)      \
  V(kLockedRelsList)      \
  V(kSetQuantifier)      \
  V(kJoinQual)      \
  V(kJoinType)      \
  V(kExtractList)      \
  V(kOverlayList)      \
  V(kPositionList)      \
  V(kSubstrList)      \
  V(kTrimList)      \
  V(kOptInterval)      \
  V(kIntervalSecond)      \
  V(kUnicodeNormalForm)      \
  V(kOptInstead)      \
  V(kOptUnique)      \
  V(kOptConcurrently)      \
  V(kOptVerbose)      \
  V(kOptFull)      \
  V(kOptFreeze)      \
  V(kOptAnalyze)      \
  V(kOptDefault)      \
  V(kOptRecheck)      \
  V(kOptBinary)      \
  V(kCopyDelimiter)      \
  V(kCopyFrom)      \
  V(kOptProgram)      \
  V(kEvent)      \
  V(kCursorOptions)      \
  V(kOptHold)      \
  V(kOptSetData)      \
  V(kObjectTypeAnyName)      \
  V(kObjectTypeName)      \
  V(kObjectTypeNameOnAnyName)      \
  V(kDropTypeName)      \
  V(kFetchArgs)      \
  V(kSelectLimitValue)      \
  V(kOffsetClause)      \
  V(kSelectOffsetValue)      \
  V(kSelectFetchFirstValue)      \
  V(kIOrFConst)      \
  V(kRowOrRows)      \
  V(kFirstOrNext)      \
  V(kOptSeqOptList)      \
  V(kSeqOptList)      \
  V(kOptParenthesizedSeqOptList)      \
  V(kSeqOptElem)      \
  V(kInsertRest)      \
  V(kOptConfExpr)      \
  V(kOptOnConflict)      \
  V(kGenericSet)      \
  V(kSetRest)      \
  V(kSetRestMore)      \
  V(kGenericReset)      \
  V(kResetRest)      \
  V(kSetResetClause)      \
  V(kFunctionSetResetClause)      \
  V(kTableElement)      \
  V(kTypedTableElement)      \
  V(kConstraintElem)      \
  V(kTableFuncElement)      \
  V(kColumnDef)      \
  V(kColumnOptions)      \
  V(kDefElem)      \
  V(kReloptionElem)      \
  V(kOldAggrElem)      \
  V(kOperatorDefElem)      \
  V(kDefArg)      \
  V(kColumnElem)      \
  V(kWhereClause)      \
  V(kWhereOrCurrentClause)      \
  V(kAExpr)      \
  V(kBExpr)      \
  V(kCExpr)      \
  V(kAexprConst)      \
  V(kIndirectionEl)      \
  V(kOptSliceBound)      \
  V(kColumnref)      \
  V(kInExpr)      \
  V(kHavingClause)      \
  V(kFuncTable)      \
  V(kXmltable)      \
  V(kArrayExpr)      \
  V(kOptWhereClause)      \
  V(kOperatorDefArg)      \
  V(kRowsfromItem)      \
  V(kRowsfromList)      \
  V(kOptColDefList)      \
  V(kOptOrdinality)      \
  V(kExclusionConstraintList)      \
  V(kExclusionConstraintElem)      \
  V(kFuncArgList)      \
  V(kFuncArgListOpt)      \
  V(kFuncArgExpr)      \
  V(kRow)      \
  V(kExplicitRow)      \
  V(kImplicitRow)      \
  V(kTypeList)      \
  V(kArrayExprList)      \
  V(kCaseExpr)      \
  V(kCaseArg)      \
  V(kWhenClause)      \
  V(kCaseDefault)      \
  V(kWhenClauseList)      \
  V(kOptSearchClause)      \
  V(kOptCycleClause)      \
  V(kSubType)      \
  V(kOptMaterialized)      \
  V(kNumericOnly)      \
  V(kNumericOnlyList)      \
  V(kAliasClause)      \
  V(kOptAliasClause)      \
  V(kOptAliasClauseForJoinUsing)      \
  V(kFuncAliasClause)      \
  V(kSortby)      \
  V(kIndexElem)      \
  V(kIndexElemOptions)      \
  V(kStatsParam)      \
  V(kTableRef)      \
  V(kJoinedTable)      \
  V(kRelationExpr)      \
  V(kRelationExprOptAlias)      \
  V(kTablesampleClause)      \
  V(kOptRepeatableClause)      \
  V(kTargetEl)      \
  V(kSetTarget)      \
  V(kInsertColumnItem)      \
  V(kGenericOptionName)      \
  V(kGenericOptionArg)      \
  V(kGenericOptionElem)      \
  V(kAlterGenericOptionElem)      \
  V(kGenericOptionList)      \
  V(kAlterGenericOptionList)      \
  V(kReindexTargetType)      \
  V(kReindexTargetMultitable)      \
  V(kCopyGenericOptArg)      \
  V(kCopyGenericOptArgListItem)      \
  V(kCopyGenericOptElem)      \
  V(kCopyGenericOptList)      \
  V(kCopyGenericOptArgList)      \
  V(kCopyOptions)      \
  V(kTypename)      \
  V(kSimpleTypename)      \
  V(kConstTypename)      \
  V(kGenericType)      \
  V(kNumeric)      \
  V(kOptFloat)      \
  V(kConstCharacter)      \
  V(kCharacterWithLength)      \
  V(kCharacterWithoutLength)      \
  V(kConstDatetime)      \
  V(kConstInterval)      \
  V(kBit)      \
  V(kConstBit)      \
  V(kBitWithLength)      \
  V(kBitWithoutLength)      \
  V(kCharacter)      \
  V(kExtractArg)      \
  V(kOptVarying)      \
  V(kOptTimezone)      \
  V(kOptNoInherit)      \
  V(kIconst)      \
  V(kSignedIconst)      \
  V(kSconst)      \
  V(kCommentText)      \
  V(kNotifyPayload)      \
  V(kRoleId)      \
  V(kOptBooleanOrString)      \
  V(kVarList)      \
  V(kColId)      \
  V(kColLabel)      \
  V(kBareColLabel)      \
  V(kNonReservedWord)      \
  V(kNonReservedWordOrSconst)      \
  V(kVarName)      \
  V(kTypeFunctionName)      \
  V(kParamName)      \
  V(kCreatedbOptName)      \
  V(kPlassignTarget)      \
  V(kVarValue)      \
  V(kZoneValue)      \
  V(kAuthIdent)      \
  V(kRoleSpec)      \
  V(kOptGrantedBy)      \
  V(kUnreservedKeyword)      \
  V(kTypeFuncNameKeyword)      \
  V(kColNameKeyword)      \
  V(kReservedKeyword)      \
  V(kBareLabelKeyword)      \
  V(kTableConstraint)      \
  V(kTableLikeClause)      \
  V(kTableLikeOptionList)      \
  V(kTableLikeOption)      \
  V(kColumnCompression)      \
  V(kOptColumnCompression)      \
  V(kColQualList)      \
  V(kColConstraint)      \
  V(kColConstraintElem)      \
  V(kConstraintAttr)      \
  V(kKeyActions)      \
  V(kKeyDelete)      \
  V(kKeyMatch)      \
  V(kKeyUpdate)      \
  V(kKeyAction)      \
  V(kConstraintAttributeSpec)      \
  V(kConstraintAttributeElem)      \
  V(kExistingIndex)      \
  V(kConstraintsSetList)      \
  V(kConstraintsSetMode)      \
  V(kOptTableSpace)      \
  V(kOptConsTableSpace)      \
  V(kOptTableSpaceOwner)      \
  V(kOptCheckOption)      \
  V(kOptProvider)      \
  V(kSecurityLabel)      \
  V(kXmlAttributeEl)      \
  V(kXmlAttributeList)      \
  V(kXmlAttributes)      \
  V(kXmlRootVersion)      \
  V(kOptXmlRootStandalone)      \
  V(kXmlexistsArgument)      \
  V(kDocumentOrContent)      \
  V(kXmlWhitespaceOption)      \
  V(kXmltableColumnList)      \
  V(kXmltableColumnOptionList)      \
  V(kXmltableColumnEl)      \
  V(kXmltableColumnOptionEl)      \
  V(kXmlNamespaceList)      \
  V(kXmlNamespaceEl)      \
  V(kFuncApplication)      \
  V(kFuncExprCommonSubexpr)      \
  V(kFuncExpr)      \
  V(kFuncExprWindowless)      \
  V(kCommonTableExpr)      \
  V(kWithClause)      \
  V(kOptWithClause)      \
  V(kCteList)      \
  V(kWithinGroupClause)      \
  V(kFilterClause)      \
  V(kWindowClause)      \
  V(kWindowDefinitionList)      \
  V(kOptPartitionClause)      \
  V(kWindowDefinition)      \
  V(kOverClause)      \
  V(kWindowSpecification)      \
  V(kOptFrameClause)      \
  V(kFrameExtent)      \
  V(kFrameBound)      \
  V(kOptWindowExclusionClause)      \
  V(kOptExistingWindowName)      \
  V(kOptIfNotExists)      \
  V(kGeneratedWhen)      \
  V(kOverrideKind)      \
  V(kPartitionSpec)      \
  V(kOptPartitionSpec)      \
  V(kPartElem)      \
  V(kPartParams)      \
  V(kPartitionBoundSpec)      \
  V(kHashPartbound)      \
  V(kHashPartboundElem)      \
  V(kOptAs)                  \
  V(kOptUsing)               \
  V(kOptProcedural)          \
  V(kAnalyzeKeyword)         \
  V(kFromIn)                 \
  V(kOptFromIn)              \
  V(kPlassignEquals)         \
  V(kOptColumn)              \
  V(kOptBy)                  \
  V(kFunctionOrProcedure)    \
  V(kTriggerForOptEach)      \
  V(kXmlPassingMech)         \
  V(kOptOuter)               \
  V(kOptTable)               \
  V(kOptRestrict)            \
  V(kOptEqual)               \
  V(kAnyWith)                \
  V(kOptAllClause)           \
  V(kEmptyGroupingSet)       \
  V(kOptAsymmetric)          \
  \
  \
  \
  \
  /* Keep the old one to ensure compatibility first. Will remove below later. */  \
  V(kProgram)                                                                  \
  V(kStmtlist)                                                                 \
  V(kAlterStmt)                                                                \
  V(kAlterIndexStmt)                                                           \
  V(kSelectClauseList)                                                         \
  V(kCombineClause)                                                            \
  V(kOptFromClause)                                                            \
  V(kSelectTarget)                                                             \
  V(kOptWindowClause)                                                          \
  V(kWindowDefList)                                                            \
  V(kWindowDef)                                                                \
  V(kWindowName)                                                               \
  V(kWindow)                                                                   \
  V(kOptPartition)                                                             \
  V(kRangeOrRows)                                                              \
  V(kFrameBoundStart)                                                          \
  V(kFrameBoundEnd)                                                            \
  V(kOptFrameExclude)                                                          \
  V(kFrameExclude)                                                             \
  V(kOptExistWindowName)                                                       \
  V(kOptGroupClause)                                                           \
  V(kOptHavingClause)                                                          \
  V(kOptOnOrUsing)                                                             \
  V(kOnOrUsing)                                                                \
  V(kColumnNameList)                                                           \
  V(kOptTablePrefix)                                                           \
  V(kJoinOp)                                                                   \
  V(kOptJoinType)                                                              \
  V(kOptLimitClause)                                                           \
  V(kOptOrderClause)                                                           \
  V(kOptOrderNulls)                                                            \
  V(kOrderItemList)                                                            \
  V(kOrderItem)                                                                \
  V(kOptOrderBehavior)                                                         \
  V(kCteTableName)                                                             \
  V(kOptAllOrDistinct)                                                         \
  V(kCreateTableStmt)                                                          \
  V(kCreateIndexStmt)                                                          \
  V(kCreateViewStmt)                                                           \
  V(kDropIndexStmt)                                                            \
  V(kDropTableStmt)                                                            \
  V(kDropViewStmt)                                                             \
  V(kInsertQuery)                                                              \
  V(kValuesDefaultClause)                                                      \
  V(kExprDefaultListWithParens)                                                \
  V(kExprDefaultList)                                                                             \
  V(kSuperValuesList)                                                          \
  V(kValuesList)                                                               \
  V(kOptConflictExpr)                                                          \
  V(kIndexedColumnList)                                                        \
  V(kIndexedColumn)                                                            \
  V(kAlterAction)                                                              \
  V(kColumnDefList)                                                            \
  V(kOptColumnConstraintList)                                                  \
  V(kColumnConstraintList)                                                     \
  V(kColumnConstraint)                                                         \
  V(kConstraintType)                                                           \
  V(kForeignClause)                                                            \
  V(kOptForeignKeyActions)                                                     \
  V(kForeignKeyActions)                                                        \
  V(kOptConstraintAttributeSpec)                                               \
  V(kOptInitialTime)                                                           \
  V(kConstraintName)                                                           \
  V(kOptColumnNameListP)                                                       \
  V(kExpr)                                                                     \
  V(kOperand)                                                                  \
  V(kCastExpr)                                                                 \
  V(kCountExpr)                                                                \
  V(kAllExpr)                                                                  \
  V(kSumExpr)                                                                  \
  V(kScalarExpr)                                                               \
  V(kUnaryExpr)                                                                \
  V(kBinaryExpr)                                                               \
  V(kLogicExpr)                                                                \
  V(kBetweenExpr)                                                              \
  V(kExistsExpr)                                                               \
  V(kCaseList)                                                                 \
  V(kCaseClause)                                                               \
  V(kCompExpr)                                                                 \
  V(kExtractExpr)                                                              \
  V(kDatetimeField)                                                            \
  V(kArrayIndex)                                                               \
  V(kLiteral)                                                                  \
  V(kStringLiteral)                                                            \
  V(kBoolLiteral)                                                              \
  V(kNumLiteral)                                                               \
  V(kIntLiteral)                                                               \
  V(kFloatLiteral)                                                             \
  V(kOptIfNotExist)                                                            \
  V(kOptIfExist)                                                               \
  V(kIdentifier)                                                               \
  V(kTableName)                                                                \
  V(kColumnName)                                                               \
  V(kViewName)                                                                 \
  V(kIndexName)                                                                \
  V(kTablespaceName)                                                           \
  V(kRoleName)                                                                 \
  V(kExtensionName)                                                            \
  V(kIndexStorageParameterList)                                                \
  V(kIndexStorageParameter)                                                    \
  V(kBinaryOp)                                                                 \
  V(kOptNot)                                                                   \
  V(kTypeName)                                                                 \
  V(kCharacterType)                                                            \
  V(kCharacterConflicta)                                                       \
  V(kNumericType)                                                              \
  V(kOptTableConstraintList)                                                   \
  V(kTableConstraintList)                                                      \
  V(kUnknown)                                                                  \
  V(kEmpty)                                                                    \
  V(kOptAlias)                                                                 \
  V(kOptSemi)                                                                  \
  V(kOptOwnedby)                                                               \
  V(kOnOffLiteral)                                                             \
  V(kOptIfNotExistIndex)                                                       \
  V(kOptOnly)                                                                  \
  V(kOptUsingMethod)                                                           \
  V(kMethodName)                                                               \
  V(kOptTablespace)                                                            \
  V(kOptWherePredicate)                                                        \
  V(kPredicateName)                                                            \
  V(kOptWithIndexStorageParameterList)                                         \
  V(kOptIncludeColumnNameList)                                                 \
  V(kCollationName)                                                            \
  V(kOptColumnOrExpr)                                                          \
  V(kIndexedCreateIndexRestStmtList)                                           \
  V(kCreateIndexRestStmt)                                                      \
  V(kOptIndexOpclassParameterList)                                             \
  V(kOptOpclassParameterList)                                                  \
  V(kIndexOpclassParameterList)                                                \
  V(kIndexOpclassParameter)                                                    \
  V(kOpclassName)                                                              \
  V(kOpclassParameterName)                                                     \
  V(kOpclassParameterValue)                                                    \
  V(kOptIndexNameList)                                                         \
  V(kIndexNameList)                                                            \
  V(kOptCascadeRestrict)                                                       \
  V(kRoleSpecification)                                                        \
  V(kUserName)                                                                 \
  V(kUserNameList)                                                                 \
  V(kGroupName)                                                                \
  V(kDropGroupStmt)                                                            \
  V(kGroupNameList)                                                            \
  V(kValuesStmt)                                                            \
  V(kExprListWithParens)                                                            \
  V(kAllorDistinct)                                                            \
  V(kOptSelectTarget)                                                           \
  V(kOrderClause)                                                           \
  V(kTableNameList)                                                        \
  V(kOptNoWaitorSkip)                                                        \
  V(kForLockingItemList)                                                        \
  V(kAlterViewStmt)                                                            \
  V(kAlterViewAction)                                                          \
  V(kOwnerSpecification)                                                       \
  V(kSchemaName)                                                               \
  V(kIndexOptViewOptionList)                                                   \
  V(kIndexOptViewOption)                                                       \
  V(kOptEqualViewOptionValue)                                                  \
  V(kViewOptionName)                                                           \
  V(kViewOptionValue)                                                          \
  V(kViewOptionNameList)                                                       \
  V(kOptReindexOptionList)                                                      \
  V(kReindexOptionList)                                                         \
  V(kReindexOption)                                                             \
  V(kDatabaseName)                                                              \
  V(kSystemName)                                                                \
  V(kOptWithOptionList)                                                        \
  V(kOptionList)                                                               \
  V(kOption)                                                                   \
  V(kRoleNameList)                                                             \
  V(kOptEncrypted)                                                             \
  V(kViewNameList)                                                             \
  V(kOptTempToken)                                                             \
  V(kOptRecursive)                                                             \
  V(kOptWithViewOptionList)                                                    \
  V(kCreateTableAsStmt)                                                        \
  V(kOptWithStorageParameterList)                                              \
  V(kAlterTblspcStmt)                                                          \
  V(kIndexOptTablespaceOptionList)                                             \
  V(kIndexOptTablespaceOption)                                             \
  V(kOptEqualTablespaceOptionValue)                                             \
  V(kTablespaceOptionName)                                             \
  V(kTablespaceOptionValue)                                             \
  V(kAlterConversionStmt)                                                       \
  V(kConversionName)                                                            \
  V(kOptWithReplotions) \
  V(kOptTransaction) \
  V(kFUNCTIONOrPROCEDURE) \


#define ALLDATATYPE(V)                                                         \
  V(DataWhatever)                                                              \
  V(DataTableName)                                                             \
  V(DataColumnName)                                                            \
  V(DataViewName)                                                              \
  V(DataFunctionName)                                                          \
  V(DataPragmaKey)                                                             \
  V(DataPragmaValue)                                                           \
  V(DataTableSpaceName)                                                        \
  V(DataSequenceName)                                                          \
  V(DataExtensionName)                                                         \
  V(DataRoleName)                                                              \
  V(DataSchemaName)                                                            \
  V(DataDatabase)                                                              \
  V(DataTriggerName)                                                           \
  V(DataWindowName)                                                            \
  V(DataTriggerFunction)                                                       \
  V(DataDomainName)                                                            \
  V(DataAliasName)                                                             \
  V(DataLiteral)                                                               \
  V(DataIndexName)                                                             \
  V(DataUserName)                                                              \
  V(DataGroupName)                                                             \
  V(DataDatabaseName)                                                          \
  V(DataSystemName)                                                            \
  V(DataConversionName)                                                        \


#define SWITCHSTART switch (case_idx_) {

#define SWITCHEND                                                              \
  default:                                                                     \
                                                                               \
    assert(0);                                                                 \
    }

#define CASESTART(idx) case CASE##idx: {

#define CASEEND                                                                \
  break;                                                                       \
  }

#define TRANSLATESTART IR *res = NULL;

#define GENERATESTART(len) case_idx_ = rand() % len;

#define GENERATEEND return;

#define TRANSLATEEND                                                           \
  v_ir_collector.push_back(res);                                               \
                                                                               \
  return res;

#define TRANSLATEENDNOPUSH return res;

#define SAFETRANSLATE(a) (assert(a != NULL), a->translate(v_ir_collector))

#define SAFEDELETE(a)                                                          \
  if (a != NULL)                                                               \
  a->deep_delete()

#define SAFEDELETELIST(a)                                                      \
  for (auto _i : a)                                                            \
  SAFEDELETE(_i)

#define OP1(a) new IROperator(a)

#define OP2(a, b) new IROperator(a, b)

#define OP3(a, b, c) new IROperator(a, b, c)

#define OPSTART(a) new IROperator(a)

#define OPMID(a) new IROperator("", a, "")

#define OPEND(a) new IROperator("", "", a)

#define OP0() new IROperator()

#define TRANSLATELIST(t, a, b)                                                 \
  res = SAFETRANSLATE(a[0]);                                                   \
  res = new IR(t, OP0(), res);                                                 \
  v_ir_collector.push_back(res);                                               \
  for (int i = 1; i < a.size(); i++) {                                         \
    IR *tmp = SAFETRANSLATE(a[i]);                                             \
    res = new IR(t, OPMID(b), res, tmp);                                       \
    v_ir_collector.push_back(res);                                             \
  }

#define PUSH(a) v_ir_collector.push_back(a)

#define MUTATESTART                                                            \
  IR *res = NULL;                                                              \
  auto randint = get_rand_int(3);                                              \
  switch (randint) {

#define DOLEFT case 0: {

#define DORIGHT                                                                \
  break;                                                                       \
  }                                                                            \
                                                                               \
  case 1: {

#define DOBOTH                                                                 \
  break;                                                                       \
  }                                                                            \
  case 2: {

#define MUTATEEND                                                              \
  }                                                                            \
  }                                                                            \
                                                                               \
  return res;

#endif
