CREATE USER unlocked_user@localhost IDENTIFIED BY 'pas';
SELECT account_locked FROM mysql.user WHERE user='unlocked_user' and host = 'localhost';
SELECT CURRENT_USER();
UPDATE mysql.user SET account_locked='Y'   WHERE user='unlocked_user' and host = 'localhost';
SELECT CURRENT_USER();
FLUSH PRIVILEGES;
SELECT CURRENT_USER();
UPDATE mysql.user SET account_locked='y'   WHERE user='unlocked_user' and host = 'localhost';
FLUSH PRIVILEGES;
ALTER USER unlocked_user@localhost ACCOUNT UNLOCK;
SELECT account_locked FROM mysql.user WHERE user = 'unlocked_user' and host = 'localhost';
SELECT CURRENT_USER();
ALTER USER unlocked_user@localhost ACCOUNT LOCK;
SELECT account_locked FROM mysql.user WHERE user = 'unlocked_user' and host = 'localhost';
CREATE USER unlocked_user2@localhost IDENTIFIED BY 'pas';
SELECT CURRENT_USER();
ALTER USER unlocked_user@localhost, unlocked_user2@localhost ACCOUNT UNLOCK;
SELECT user, account_locked FROM mysql.user WHERE (user = 'unlocked_user' and host = 'localhost') or (user = 'unlocked_user2' and host = 'localhost') ORDER BY user;
SELECT CURRENT_USER();
SELECT CURRENT_USER();
SHOW CREATE USER unlocked_user@localhost;
ALTER USER unlocked_user@localhost ACCOUNT LOCK;
SHOW CREATE USER unlocked_user@localhost;
DROP USER unlocked_user@localhost;
DROP USER unlocked_user2@localhost;
CREATE USER ''@localhost IDENTIFIED BY 'pass';
SELECT CURRENT_USER();
DROP USER ''@localhost;
CREATE USER ''@localhost IDENTIFIED BY 'pass' ACCOUNT UNLOCK;
SELECT CURRENT_USER();
DROP USER ''@localhost;
CREATE USER ''@localhost IDENTIFIED BY 'pass' ACCOUNT LOCK;
DROP USER ''@localhost;
CREATE USER ''@localhost IDENTIFIED BY 'pass';
ALTER USER ''@localhost ACCOUNT LOCK;
DROP USER ''@localhost;
CREATE USER ''@localhost IDENTIFIED BY 'pass' ACCOUNT LOCK;
ALTER USER ''@localhost ACCOUNT UNLOCK;
SELECT CURRENT_USER();
DROP USER ''@localhost;
CREATE USER ''@localhost IDENTIFIED BY 'pass';
ALTER USER ''@localhost PASSWORD EXPIRE ACCOUNT LOCK;
DROP USER ''@localhost;
CREATE user ''@localhost IDENTIFIED BY 'pass';
CREATE USER 'unlocked_user'@localhost IDENTIFIED BY 'pass';
UPDATE mysql.user SET account_locked='Y'   WHERE user='unlocked_user' and host = 'localhost';
ALTER USER unlocked_user@localhost ACCOUNT LOCK;
DROP USER unlocked_user@localhost;
DROP USER ''@localhost;
CREATE USER u1@localhost IDENTIFIED BY 'pass';
CREATE USER u2@localhost IDENTIFIED BY 'pass';
GRANT ALL ON *.* TO u1@localhost;
CREATE TABLE mysql.t1(counter INT);
INSERT INTO mysql.t1 VALUES(0);
CREATE DEFINER = u1@localhost PROCEDURE mysql.p1() BEGIN UPDATE mysql.t1 SET counter = counter + 1; SELECT counter FROM mysql.t1; END;
CALL mysql.p1();
GRANT EXECUTE ON PROCEDURE mysql.p1 TO u2@localhost;
ALTER USER u1@localhost ACCOUNT LOCK;
SELECT CURRENT_USER();
CALL mysql.p1();
FLUSH STATUS;
CREATE USER 'u3'@'localhost' IDENTIFIED BY 'pass' ACCOUNT LOCK;
SHOW STATUS LIKE 'Locked_connects';
ALTER USER u3@localhost ACCOUNT UNLOCK;
ALTER USER u3@localhost ACCOUNT LOCK;
ALTER USER u3@localhost ACCOUNT UNLOCK;
ALTER USER u3@localhost ACCOUNT LOCK;
ALTER USER u3@localhost ACCOUNT UNLOCK;
ALTER USER u3@localhost ACCOUNT LOCK;
ALTER USER u3@localhost ACCOUNT UNLOCK;
ALTER USER u3@localhost ACCOUNT LOCK;
ALTER USER u3@localhost ACCOUNT UNLOCK;
ALTER USER u3@localhost ACCOUNT LOCK;
ALTER USER u3@localhost ACCOUNT UNLOCK;
ALTER USER u3@localhost ACCOUNT LOCK;
ALTER USER u3@localhost ACCOUNT UNLOCK;
ALTER USER u3@localhost ACCOUNT LOCK;
ALTER USER u3@localhost ACCOUNT UNLOCK;
ALTER USER u3@localhost ACCOUNT LOCK;
ALTER USER u3@localhost ACCOUNT UNLOCK;
ALTER USER u3@localhost ACCOUNT LOCK;
ALTER USER u3@localhost ACCOUNT UNLOCK;
ALTER USER u3@localhost ACCOUNT LOCK;
SHOW STATUS LIKE 'Locked_connects';
FLUSH STATUS;
CREATE USER u1@localhost REQUIRE NONE ACCOUNT LOCK WITH MAX_QUERIES_PER_HOUR 100;
DROP USER u1@localhost;
CREATE USER u1@localhost REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 100 ACCOUNT LOCK;
SHOW CREATE USER u1@localhost;
ALTER USER u1@localhost PASSWORD EXPIRE ACCOUNT UNLOCK;
SHOW CREATE USER u1@localhost;
ALTER USER u1@localhost ACCOUNT LOCK PASSWORD EXPIRE;
SHOW CREATE USER u1@localhost;
ALTER USER u1@localhost REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 99 ACCOUNT UNLOCK PASSWORD EXPIRE NEVER;
SHOW CREATE USER u1@localhost;
ALTER USER u1@localhost REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 98 PASSWORD EXPIRE INTERVAL 5 DAY ACCOUNT LOCK;
SHOW CREATE USER u1@localhost;
ALTER USER u1@localhost ACCOUNT UNLOCK WITH MAX_QUERIES_PER_HOUR 97 PASSWORD EXPIRE;
DROP USER u1@localhost;
CREATE USER u1@localhost IDENTIFIED BY 'PASS' ACCOUNT LOCK ACCOUNT UNLOCK;
SHOW CREATE USER u1@localhost;
DROP USER u1@localhost;
CREATE USER u1@localhost ACCOUNT UNLOCK ACCOUNT LOCK;
SHOW CREATE USER u1@localhost;
DROP USER u1@localhost;
CREATE USER u1@localhost ACCOUNT LOCK PASSWORD EXPIRE ACCOUNT LOCK;
SHOW CREATE USER u1@localhost;
ALTER USER u1@localhost IDENTIFIED BY 'PASS' ACCOUNT LOCK ACCOUNT UNLOCK;
SHOW CREATE USER u1@localhost;
ALTER USER u1@localhost ACCOUNT UNLOCK ACCOUNT LOCK;
SHOW CREATE USER u1@localhost;
ALTER USER u1@localhost ACCOUNT LOCK PASSWORD EXPIRE ACCOUNT LOCK;
SHOW CREATE USER u1@localhost;
ALTER USER u1@localhost PASSWORD EXPIRE ACCOUNT LOCK PASSWORD EXPIRE NEVER;
SHOW CREATE USER u1@localhost;
ALTER USER u1@localhost PASSWORD EXPIRE NEVER ACCOUNT LOCK PASSWORD EXPIRE INTERVAL 5 DAY ACCOUNT LOCK;
SHOW CREATE USER u1@localhost;
call mtr.add_suppression("Column count of mysql.* is wrong. "                          "Expected .*, found .*. "                          "The table is probably corrupted");
CREATE TABLE mysql.temp_user LIKE mysql.user;
INSERT INTO mysql.temp_user SELECT * FROM mysql.user;
ALTER TABLE mysql.user DROP COLUMN account_locked;
ALTER TABLE mysql.user DROP COLUMN create_role_priv;
ALTER TABLE mysql.user DROP COLUMN drop_role_priv;
CREATE USER backuser@localhost IDENTIFIED BY 'pass' ACCOUNT LOCK;
SELECT COUNT(*) FROM mysql.user WHERE (user = 'backuser' and host = 'localhost');
CREATE USER backuser@localhost IDENTIFIED BY 'pass' ACCOUNT UNLOCK;
SELECT COUNT(*) FROM mysql.user WHERE (user = 'backuser' and host = 'localhost');
CREATE USER backuser@localhost IDENTIFIED BY 'pass';
SELECT COUNT(*) FROM mysql.user WHERE (user = 'backuser' and host = 'localhost');
SELECT user, account_locked FROM mysql.user WHERE (user = 'backuser' and host = 'localhost');
ALTER USER backuser@localhost ACCOUNT LOCK;
ALTER USER backuser@localhost ACCOUNT UNLOCK;
DROP USER backuser@localhost;
DROP TABLE mysql.user;
ALTER TABLE mysql.temp_user RENAME mysql.user;
FLUSH PRIVILEGES;
CREATE DATABASE account;
CREATE TABLE account.`account` (account text(20));
INSERT INTO `account`.account VALUES("account");
SELECT account FROM account.account WHERE account = 'account';
SET @account = "account_before";
CREATE PROCEDURE account.account(OUT ac CHAR(20)) BEGIN SELECT account.`account`.account INTO ac FROM account.account; END;
CALL account.account(@account);
SELECT @account;
DROP DATABASE account;
CREATE USER ACCOUNT@localhost ACCOUNT LOCK;
DROP USER ACCOUNT@localhost;
DROP PROCEDURE mysql.p1;
DROP TABLE mysql.t1;
DROP USER u1@localhost;
DROP USER u2@localhost;
DROP USER u3@localhost;
CREATE USER u1 IDENTIFIED BY 'pass';
SHOW CREATE USER u1;
ALTER USER u1 ACCOUNT LOCK;
SHOW CREATE USER u1;
DROP USER u1;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
TRUNCATE TABLE mysql.general_log;
SET @old_log_output=          @@global.log_output;
SET @old_general_log=         @@global.general_log;
SET @old_general_log_file=    @@global.general_log_file;
SET GLOBAL general_log_file = '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/log/rewrite_general.log';
SET GLOBAL log_output =       'FILE,TABLE';
SET GLOBAL general_log=       'ON';
CREATE USER u1 IDENTIFIED BY 'pass';
CREATE USER u2 IDENTIFIED BY 'pass' ACCOUNT LOCK;
CREATE USER u3 IDENTIFIED BY 'pass' ACCOUNT UNLOCK;
ALTER USER u1 IDENTIFIED BY 'pass';
ALTER USER u1 IDENTIFIED BY 'pass' ACCOUNT LOCK;
ALTER USER u1 IDENTIFIED BY 'pass' ACCOUNT UNLOCK;
ALTER USER u2 IDENTIFIED BY 'pass';
SELECT argument FROM mysql.general_log WHERE argument LIKE 'CREATE USER %' AND command_type NOT LIKE 'Prepare';
SELECT argument FROM mysql.general_log WHERE argument LIKE 'ALTER USER %'AND command_type NOT LIKE 'Prepare';
DROP USER u1, u2, u3;
SET GLOBAL general_log_file=  @old_general_log_file;
SET GLOBAL general_log=       @old_general_log;
SET GLOBAL log_output=        @old_log_output;
TRUNCATE TABLE mysql.general_log;
