call mtr.add_suppression(".*Password salt for user.*");
call mtr.add_suppression("Found invalid password for user:*");
CREATE USER 'kristofer' IDENTIFIED WITH 'sha256_password';
ALTER USER 'kristofer' IDENTIFIED BY 'secret';
SELECT user, plugin FROM mysql.user ORDER BY user;
SELECT USER(),CURRENT_USER();
DROP USER 'kristofer';
CREATE USER 'kristofer'@'localhost' IDENTIFIED WITH 'sha256_password' BY '123';
CREATE USER 'kristofer2'@'localhost' IDENTIFIED WITH 'sha256_password' BY '123';
ALTER USER 'kristofer'@'localhost' IDENTIFIED BY 'secret2';
ALTER USER 'kristofer2'@'localhost' IDENTIFIED BY 'secret2';
SELECT USER(),CURRENT_USER();
SHOW CREATE USER 'kristofer'@'localhost';
SELECT USER(),CURRENT_USER();
DROP USER 'kristofer'@'localhost';
DROP USER 'kristofer2'@'localhost';
CREATE USER 'kristofer'@'localhost' IDENTIFIED WITH 'sha256_password' BY '123';
ALTER USER 'kristofer'@'localhost' IDENTIFIED BY '';
SELECT USER(),CURRENT_USER();
SHOW CREATE USER 'kristofer'@'localhost';
DROP USER 'kristofer'@'localhost';
CREATE USER 'kristofer'@'33.33.33.33' IDENTIFIED WITH 'sha256_password' BY '123';
ALTER USER 'kristofer'@'33.33.33.33' IDENTIFIED BY '';
DROP USER 'kristofer'@'33.33.33.33';
CREATE USER 'kristofer' IDENTIFIED WITH 'sha256_password';
ALTER USER 'kristofer' IDENTIFIED BY 'secret';
SELECT user, plugin FROM mysql.user ORDER BY user;
SELECT USER(),CURRENT_USER();
UPDATE mysql.user SET authentication_string= '$' WHERE user='kristofer';
FLUSH PRIVILEGES;
SELECT user,authentication_string,plugin FROM mysql.user WHERE user='kristofer';
UPDATE mysql.user SET authentication_string= '$5$asd' WHERE user='kristofer';
FLUSH PRIVILEGES;
SELECT user,authentication_string,plugin FROM mysql.user WHERE user='kristofer';
DROP USER kristofer;
