CALL mtr.add_suppression("Column count of");
CALL mtr.add_suppression("Incorrect definition of table");
CALL mtr.add_suppression("Cannot load from");
CALL mtr.add_suppression("Storage engine 'MyISAM' does not");
CREATE TABLE system_tables (ID INT PRIMARY KEY AUTO_INCREMENT, table_name VARCHAR(100));
INSERT INTO system_tables(table_name) SELECT concat(table_schema, ".", table_name) FROM INFORMATION_SCHEMA.tables WHERE table_schema = 'mysql' AND table_name NOT IN('general_log', 'slow_log', 'ndb_binlog_index') ORDER BY table_name;
CALL test_system_table_alter_engine();
DROP PROCEDURE test_system_table_alter_engine;
CREATE PROCEDURE execute_stmt(stmt VARCHAR(255)) BEGIN SET @error_no = 0; SET @sql_stmt = stmt; PREPARE stmt FROM @sql_stmt; EXECUTE stmt; GET DIAGNOSTICS CONDITION 1 @error_no = MYSQL_ERRNO, @error_message = MESSAGE_TEXT; IF @error_no > 0 THEN SELECT "Warning" AS SEVERITY, @error_no as ERRNO, @error_message as MESSAGE; END IF; DEALLOCATE PREPARE stmt; END;
CALL test_create_system_table();
DROP PROCEDURE test_create_system_table;
DROP PROCEDURE execute_stmt;
DROP TABLE system_tables;
CREATE USER 'user1'@'%';
CREATE TABLE t1 (f1 INT);
CREATE FUNCTION sequence RETURNS INTEGER SONAME "udf_example.so";
RENAME TABLE mysql.func TO mysql.func_bkp;
CREATE TABLE mysql.func ENGINE='MyISAM' AS SELECT * FROM mysql.func_bkp;
CREATE FUNCTION udf_func RETURNS STRING SONAME 'udf_func.so';
DROP FUNCTION sequence;
ALTER TABLE mysql.func ENGINE='InnoDB', DROP COLUMN ret;
CREATE FUNCTION udf_func RETURNS STRING SONAME 'udf_func.so';
DROP FUNCTION sequence;
DROP TABLE mysql.func;
RENAME TABLE mysql.func_bkp TO mysql.func;
DROP FUNCTION sequence;
RENAME TABLE mysql.plugin TO mysql.plugin_bkp;
CREATE TABLE mysql.plugin ENGINE='MyISAM' AS SELECT * FROM mysql.plugin_bkp;
INSTALL PLUGIN my_plug soname 'some_plugin.so';
UNINSTALL PLUGIN my_plug;
ALTER TABLE mysql.plugin ENGINE=InnoDB, MODIFY dl CHAR(64);
INSTALL PLUGIN my_plug soname 'some_plugin.so';
UNINSTALL PLUGIN my_plug;
DROP TABLE mysql.plugin;
RENAME TABLE mysql.plugin_bkp TO mysql.plugin;
RENAME TABLE mysql.servers TO mysql.servers_bkp;
CREATE TABLE mysql.servers ENGINE='MyISAM' AS SELECT * FROM mysql.servers_bkp;
CREATE SERVER fedlnk FOREIGN DATA WRAPPER mysql OPTIONS (USER 'fed_user', HOST 'remote_host', PORT 9306, DATABASE 'federated');
DROP SERVER fedlnk;
ALTER SERVER fedlnk OPTIONS (USER 'sally');
ALTER TABLE mysql.servers ENGINE='InnoDB', MODIFY WRAPPER varchar(128);
CREATE SERVER fedlnk FOREIGN DATA WRAPPER mysql OPTIONS (USER 'fed_user', HOST 'remote_host', PORT 9306, DATABASE 'federated');
DROP SERVER fedlnk;
ALTER SERVER fedlnk OPTIONS (USER 'sally');
DROP TABLE mysql.servers;
RENAME TABLE mysql.servers_bkp TO mysql.servers;
RENAME TABLE mysql.user TO mysql.user_bkp;
CREATE TABLE mysql.user ENGINE='MyISAM' AS SELECT * FROM mysql.user_bkp;
CREATE USER 'user2'@'%';
DROP USER 'user1'@'%';
ALTER USER 'user1'@'%' PASSWORD EXPIRE;
GRANT SELECT ON t1 TO 'user1'@'%';
REVOKE SELECT ON t1 FROM 'user1'@'%';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'user1'@'%';
SET PASSWORD FOR 'user1'@'%' = '123';
RENAME USER 'user1'@'%' TO 'user1'@'%';
ALTER TABLE mysql.user ENGINE='InnoDB', DROP COLUMN max_updates;
CREATE USER 'user2'@'%';
DROP USER 'user1'@'%';
ALTER USER 'user1'@'%' PASSWORD EXPIRE;
GRANT SELECT ON t1 TO 'user1'@'%';
REVOKE SELECT ON t1 FROM 'user1'@'%';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'user1'@'%';
SET PASSWORD FOR 'user1'@'%' = '123';
RENAME USER 'user1'@'%' TO 'user1'@'%';
DROP TABLE mysql.user;
RENAME TABLE mysql.user_bkp TO mysql.user;
RENAME TABLE mysql.columns_priv TO mysql.columns_priv_bkp;
CREATE TABLE mysql.columns_priv ENGINE='MyISAM' AS SELECT * FROM mysql.columns_priv_bkp;
GRANT SELECT(f1) ON t1 TO 'user1'@'%';
REVOKE SELECT ON t1.f1 FROM 'user1'@'%';
ALTER TABLE mysql.columns_priv ENGINE='InnoDB', DROP COLUMN Timestamp;
GRANT SELECT(f1) ON t1 TO 'user1'@'%';
REVOKE SELECT ON t1.f1 FROM 'user1'@'%';
DROP TABLE mysql.columns_priv;
RENAME TABLE mysql.columns_priv_bkp TO mysql.columns_priv;
RENAME TABLE mysql.tables_priv TO mysql.tables_priv_bkp;
CREATE TABLE mysql.tables_priv ENGINE='MyISAM' AS SELECT * FROM mysql.tables_priv_bkp;
GRANT SELECT ON t1 TO 'user1'@'%';
REVOKE SELECT ON t1 FROM 'user1'@'%';
ALTER TABLE mysql.tables_priv ENGINE='InnoDB', DROP COLUMN Timestamp;
GRANT SELECT ON t1 TO 'user1'@'%';
REVOKE SELECT ON t1 FROM 'user1'@'%';
DROP TABLE mysql.tables_priv;
RENAME TABLE mysql.tables_priv_bkp TO mysql.tables_priv;
CREATE FUNCTION f1() RETURNS INT return 1;
RENAME TABLE mysql.procs_priv TO mysql.procs_priv_bkp;
CREATE TABLE mysql.procs_priv ENGINE='MyISAM' AS SELECT * FROM mysql.procs_priv_bkp;
GRANT EXECUTE ON FUNCTION f1 TO 'user1'@'%';
REVOKE EXECUTE ON FUNCTION f1 FROM 'user1'@'%';
ALTER TABLE mysql.procs_priv ENGINE='InnoDB', DROP COLUMN timestamp;
GRANT EXECUTE ON FUNCTION f1 TO 'user1'@'%';
REVOKE EXECUTE ON FUNCTION f1 FROM 'user1'@'%';
DROP TABLE mysql.procs_priv;
RENAME TABLE mysql.procs_priv_bkp TO mysql.procs_priv;
RENAME TABLE mysql.proxies_priv TO mysql.proxies_priv_bkp;
CREATE TABLE mysql.proxies_priv ENGINE='MyISAM' AS SELECT * FROM mysql.proxies_priv_bkp;
GRANT PROXY ON 'user1'@'%' TO 'user2'@'%';
REVOKE PROXY ON 'user1'@'%' FROM 'user2'@'%';
ALTER TABLE mysql.proxies_priv ENGINE='InnoDB', DROP COLUMN timestamp;
GRANT PROXY ON 'user1'@'%' TO 'user2'@'%';
REVOKE PROXY ON 'user1'@'%' FROM 'user2'@'%';
DROP TABLE mysql.proxies_priv;
RENAME TABLE mysql.proxies_priv_bkp TO mysql.proxies_priv;
RENAME TABLE mysql.component TO mysql.component_bkp;
CREATE TABLE mysql.component ENGINE='MyISAM' AS SELECT * FROM mysql.component_bkp;
INSTALL COMPONENT "file://component_log_sink_json";
UNINSTALL COMPONENT "file://component_log_sink_json";
ALTER TABLE mysql.component ENGINE='InnoDB', DROP COLUMN component_urn;
INSTALL COMPONENT "file://component_log_sink_json";
UNINSTALL COMPONENT "file://component_log_sink_json";
DROP TABLE mysql.component;
RENAME TABLE mysql.component_bkp TO mysql.component;
RENAME TABLE mysql.db TO mysql.db_bkp;
CREATE TABLE mysql.db ENGINE='MyISAM' AS SELECT * FROM mysql.db_bkp;
GRANT ALL ON db.* TO 'user1'@'%';
ALTER TABLE mysql.db ENGINE='InnoDB', DROP COLUMN Select_priv;
GRANT ALL ON db.* TO 'user1'@'%';
DROP TABLE mysql.db;
RENAME TABLE mysql.db_bkp TO mysql.db;
RENAME TABLE mysql.default_roles TO mysql.default_roles_bkp;
CREATE TABLE mysql.default_roles ENGINE='MyISAM' AS SELECT * FROM mysql.default_roles_bkp;
SET DEFAULT ROLE ALL TO 'user1'@'%';
ALTER TABLE mysql.default_roles ENGINE='InnoDB', DROP COLUMN DEFAULT_ROLE_USER;
SET DEFAULT ROLE ALL TO 'user1'@'%';
DROP TABLE mysql.default_roles;
RENAME TABLE mysql.default_roles_bkp TO mysql.default_roles;
RENAME TABLE mysql.global_grants TO mysql.global_grants_bkp;
CREATE TABLE mysql.global_grants ENGINE='MyISAM' AS SELECT * FROM mysql.global_grants_bkp;
GRANT PROCESS ON *.* TO 'user1'@'%';
REVOKE PROCESS ON *.* FROM 'user1'@'%';
ALTER TABLE mysql.global_grants ENGINE='InnoDB', DROP COLUMN WITH_GRANT_OPTION;
GRANT PROCESS ON *.* TO 'user1'@'%';
REVOKE PROCESS ON *.* FROM 'user1'@'%';
DROP TABLE mysql.global_grants;
RENAME TABLE mysql.global_grants_bkp TO mysql.global_grants;
RENAME TABLE mysql.role_edges TO mysql.role_edges_bkp;
CREATE TABLE mysql.role_edges ENGINE='MyISAM' AS SELECT * FROM mysql.role_edges_bkp;
SET DEFAULT ROLE ALL TO 'user1'@'%';
ALTER TABLE mysql.role_edges ENGINE='InnoDB', DROP COLUMN TO_USER;
SET DEFAULT ROLE ALL TO 'user1'@'%';
DROP TABLE mysql.role_edges;
RENAME TABLE mysql.role_edges_bkp TO mysql.role_edges;
SET GLOBAL default_password_lifetime = 2;
RENAME TABLE mysql.password_history TO mysql.password_history_bkp;
CREATE TABLE mysql.password_history ENGINE='MyISAM' AS SELECT * FROM mysql.password_history_bkp;
ALTER USER 'user1'@'%' IDENTIFIED BY 'password';
ALTER TABLE mysql.password_history ENGINE='InnoDB', DROP COLUMN Password_timestamp;
ALTER USER 'user1'@'%' IDENTIFIED BY 'password';
DROP TABLE mysql.password_history;
RENAME TABLE mysql.password_history_bkp TO mysql.password_history;
SET GLOBAL default_password_lifetime = DEFAULT;
DROP TABLE t1;
DROP FUNCTION f1;
DROP USER 'user1'@'%';
SELECT table_schema, table_name, engine FROM information_schema.tables WHERE table_schema='mysql'                                               AND engine='MyISAM';
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
SELECT table_schema, table_name, engine FROM information_schema.tables WHERE table_schema='mysql'                                               AND engine='MyISAM';
