INSTALL COMPONENT "file://component_validate_password";
SET @@global.validate_password.policy=LOW;
SET @@global.validate_password.mixed_case_count=0;
SET @@global.validate_password.number_count=0;
SET @@global.validate_password.special_char_count=0;
SET @@global.validate_password.length=0;
CREATE USER foo@localhost IDENTIFIED BY 'root';
SELECT VALIDATE_PASSWORD_STRENGTH('root') = 0;
SELECT VALIDATE_PASSWORD_STRENGTH('toor') = 0;
SELECT VALIDATE_PASSWORD_STRENGTH('Root') <> 0;
SELECT VALIDATE_PASSWORD_STRENGTH('Toor') <> 0;
SELECT VALIDATE_PASSWORD_STRENGTH('fooHoHo%1') <> 0;
SET PASSWORD='base_User';
SELECT VALIDATE_PASSWORD_STRENGTH('resu_esab') = 0;
SET PASSWORD='';
CREATE USER ""@localhost;
GRANT ALL PRIVILEGES ON test.* TO ""@localhost;
SELECT USER(),CURRENT_USER();
SELECT VALIDATE_PASSWORD_STRENGTH('resu_nigol') = 0;
REVOKE ALL PRIVILEGES ON test.* FROM ""@localhost;
DROP USER ""@localhost;
SET @@global.validate_password.policy=default;
SET @@global.validate_password.length=default;
SET @@global.validate_password.mixed_case_count=default;
SET @@global.validate_password.number_count=default;
SET @@global.validate_password.special_char_count=default;
UNINSTALL COMPONENT "file://component_validate_password";
