DROP TABLE IF EXISTS t1;
SHOW CREATE TABLE t1;
drop table t1;
SHOW CREATE TABLE t1;
drop table t1;
set sql_mode='TRADITIONAL';
drop table t1;
SHOW CREATE TABLE t1;
drop table t1;
SET SQL_MODE='';
drop table t1;
SET SQL_MODE='TRADITIONAL';
