SELECT @@global.protocol_compression_algorithms;
SET @@global.protocol_compression_algorithms=default;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
SET GLOBAL protocol_compression_algorithms="zstd";
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
SET GLOBAL protocol_compression_algorithms="zstd,uncompressed";
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
SET GLOBAL protocol_compression_algorithms="zlib";
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
SET GLOBAL protocol_compression_algorithms="zlib,uncompressed";
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
SET GLOBAL protocol_compression_algorithms="zlib,zstd";
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
SET GLOBAL protocol_compression_algorithms="uncompressed";
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
SET @@global.protocol_compression_algorithms=default;
CREATE DATABASE wl12475;
USE wl12475;
CREATE TABLE t1(a LONGTEXT);
INSERT INTO t1 VALUES (REPEAT('1',200));
INSERT INTO t1 VALUES (REPEAT('2', 1800));
DROP TABLE t1;
SELECT COUNT(*) FROM wl12475.t1;
DROP TABLE wl12475.t1;
SELECT COUNT(*) FROM wl12475.t1;
SELECT COUNT(*) FROM wl12475.t1;
CALL mtr.add_suppression("Option --protocol-compression-algorithms is reset to default value.");
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
SELECT @@global.protocol_compression_algorithms;
DROP DATABASE wl12475;
