drop table if exists t1,t2;
show tables where Tables_in_mysql != 'ndb_binlog_index';
show tables;
show session status;
create user test@localhost identified by "gambling";
grant ALL on *.* to test@localhost;
create user test@127.0.0.1 identified by "gambling";
grant ALL on *.* to test@127.0.0.1;
show tables where Tables_in_mysql != 'ndb_binlog_index';
show tables;
show session status;
drop user test@localhost;
drop user test@127.0.0.1;
create table t1 (id integer not null auto_increment primary key);
create temporary table t2(id integer not null auto_increment primary key);
set @id := 1;
delete from t1 where id like @id;
show session status;
drop table t1;
CREATE USER mysqltest_u1@localhost;
SET GLOBAL max_connections = 3;
SELECT COUNT(*) = 1 FROM information_schema.processlist WHERE user = 'event_scheduler' AND command = 'Daemon';
show session status;
SELECT user FROM information_schema.processlist ORDER BY id;
SET GLOBAL max_connections = 151;
show session status;
DROP USER mysqltest_u1@localhost;
FLUSH STATUS;
SHOW STATUS LIKE 'max_used_connections';
SHOW STATUS LIKE 'max_used_connections';
SELECT COUNT(*) = 1 FROM information_schema.processlist WHERE user = 'event_scheduler' AND command = 'Daemon';
show session status;
CREATE USER must_change@localhost IDENTIFIED BY 'aha';
SELECT password_expired FROM mysql.user  WHERE user='must_change' and host = 'localhost';
SELECT USER();
CREATE TABLE t1 (A INT);
CREATE PROCEDURE TEST_t1(new_a INT) INSERT INTO t1 VALUES (new_a);
CREATE FUNCTION last_t1() RETURNS INT RETURN (SELECT MAX(A) FROM t1);
CALL test_t1(1);
UPDATE mysql.user SET password_expired='Y'   WHERE user='must_change' and host = 'localhost';
SELECT USER();
SELECT last_t1();
CALL test_t1(last_t1() + 1);
FLUSH PRIVILEGES;
SELECT USER();
SELECT last_t1();
CALL test_t1(last_t1() + 1);
SELECT USER();
SELECT last_t1();
CALL test_t1(last_t1() + 1);
ALTER USER must_change@localhost IDENTIFIED BY 'aha2';
SELECT USER();
SELECT last_t1();
CALL test_t1(last_t1() + 1);
SELECT password_expired FROM mysql.user WHERE user='must_change' and host = 'localhost';
UPDATE mysql.user SET password_expired='Y'   WHERE user='must_change' and host = 'localhost';
FLUSH PRIVILEGES;
SELECT USER();
SELECT last_t1();
CALL test_t1(last_t1() + 1);
ALTER USER must_change@localhost IDENTIFIED BY 'aha3';
SELECT USER();
SELECT last_t1();
CALL test_t1(last_t1() + 1);
ALTER USER must_change@localhost IDENTIFIED BY 'aha3';
SELECT USER();
SELECT last_t1();
CALL test_t1(last_t1() + 1);
ALTER USER must_change@localhost PASSWORD EXPIRE;
SELECT password_expired FROM mysql.user WHERE user='must_change' and host = 'localhost';
SELECT USER();
ALTER USER must_change@localhost IDENTIFIED BY 'aha4';
ALTER USER invalid_user@localhost, must_change@localhost PASSWORD EXPIRE;
SELECT password_expired FROM mysql.user WHERE user='must_change' and host = 'localhost';
SELECT USER();
ALTER USER must_change@localhost PASSWORD EXPIRE;
SELECT password_expired FROM mysql.user WHERE user='must_change' and host = 'localhost';
SELECT USER();
ALTER USER must_change@localhost IDENTIFIED BY 'aha5';
SELECT USER();
SELECT USER();
DROP PROCEDURE test_t1;
