SELECT @@session.session_track_schema;
SELECT @@session.session_track_system_variables;
SELECT @@global.session_track_schema;
SELECT @@global.session_track_system_variables;
SELECT @@session.character_set_client, @@session.character_set_results, @@session.character_set_connection;
SET NAMES 'utf8';
SELECT @@session.character_set_client, @@session.character_set_results, @@session.character_set_connection;
SET NAMES 'big5';
SELECT @@session.character_set_client, @@session.character_set_results, @@session.character_set_connection;
SET @@session.character_set_client=utf8;
SELECT @@session.character_set_client, @@session.character_set_results, @@session.character_set_connection;
SET @@session.character_set_results=utf8;
SELECT @@session.character_set_client, @@session.character_set_results, @@session.character_set_connection;
SET @@session.character_set_connection=utf8;
SELECT @@session.character_set_client, @@session.character_set_results, @@session.character_set_connection;
SELECT @@session.time_zone;
SET @@session.time_zone='Europe/Moscow';
SELECT @@session.time_zone;
SET @@session.time_zone='MET';
SELECT @@session.time_zone;
SET @@session.time_zone='funny';
SELECT @@session.time_zone;
SELECT @@session.autocommit;
SET @@session.autocommit= 1;
SELECT @@session.autocommit;
SET @@session.autocommit= 0;
SELECT @@session.autocommit;
SET @@session.autocommit= OFF;
SELECT @@session.autocommit;
SET @@session.autocommit= ON;
SELECT @@session.autocommit;
SET @@session.autocommit= foo;
SELECT @@session.autocommit;
SET @@session.autocommit=OFF, @@time_zone='SYSTEM';
SELECT @@session.autocommit;
SELECT @@session.time_zone;
SET @@session.autocommit=ON, @@time_zone='INVALID';
SELECT @@session.autocommit;
SELECT @@session.time_zone;
SELECT @@session.sql_mode;
SET @@session.session_track_system_variables='sql_mode';
SELECT @@session.session_track_system_variables;
SET @sql_mode_saved= @@session.sql_mode;
SET @@session.sql_mode='traditional';
SET @@session.sql_mode='traditional';
SELECT @@session.sql_mode;
SET @@session.sql_mode='invalid';
SET @@session.session_track_system_variables='*';
SET @@session.sql_mode= @sql_mode_saved;
SET @@session.session_track_system_variables='';
SET @@session.sql_mode= @sql_mode_saved;
SELECT @@session.sql_mode;
SET @@session.session_track_system_variables=NULL;
SET @@session.sql_mode= @sql_mode_saved;
SELECT @@session.sql_mode;
SET @@session.session_track_system_variables='var1,NULL';
SET @@session.sql_mode= @sql_mode_saved;
SELECT @@session.sql_mode;
SET @@session.session_track_system_variables='autocommit,time_zone,                                               transaction_isolation';
SELECT @@session.session_track_system_variables;
CREATE PROCEDURE my_proc() BEGIN SET @@session.autocommit=OFF; SET @@session.time_zone='-6:00'; SET @@session.transaction_isolation='READ-COMMITTED'; END;;
CALL my_proc;
CALL my_proc;
DROP PROCEDURE my_proc;
SHOW VARIABLES LIKE 'var1';
SHOW VARIABLES LIKE 'var1';
SET @@session.session_track_system_variables='var1,sql_mode,var2';
SELECT @@session.session_track_system_variables;
SET @@session.sql_mode='ANSI';
SELECT @@session.sql_mode;
SET @@session.sql_mode=@@session.sql_mode;
SET @@session.session_track_system_variables='session_track_system_variables';
SELECT @@session.session_track_system_variables;
SELECT @@session.session_track_schema;
USE mysql;
USE test;
USE non_existing_db;
USE mysql;
USE mysql;
USE test;
SET @@session.session_track_schema=false;
SELECT @@session.session_track_schema;
