call mtr.add_suppression("Dictionary file not specified");
INSTALL PLUGIN validate_password SONAME 'validate_password.so';
SET @@global.validate_password_policy=LOW;
SET @@global.validate_password_length= 12;
SET @@global.validate_password_mixed_case_count= 0;
SET @@global.validate_password_number_count= 0;
SET @@global.validate_password_special_char_count= 0;
SET @@global.validate_password_length= 0;
SET @@global.validate_password_length= -2;
SET @@global.validate_password_length= 3.5;
SET @@global.validate_password_length= 2147483647;
SET @@global.validate_password_length= 2147483648;
SET @a = REPEAT('a',2147483647);
EXECUTE stmt1 USING @a,@b;
DEALLOCATE PREPARE stmt1;
SET @@global.validate_password_length= 4294967295;
SET @@global.validate_password_length= 8;
SET @a = REPEAT('a',1048576);
EXECUTE stmt1 USING @a,@b;
DEALLOCATE PREPARE stmt1;
SET @@global.validate_password_mixed_case_count= 1;
SET @@global.validate_password_number_count= 1;
SET @@global.validate_password_special_char_count= 1;
SET @@global.validate_password_policy=MEDIUM;
SET @@global.validate_password_number_count= 0;
SET @@global.validate_password_mixed_case_count= 0;
SET @@global.validate_password_special_char_count= 0;
SET @@global.validate_password_special_char_count= 1;
SET @@global.validate_password_number_count= 1;
SET @@global.validate_password_mixed_case_count= 1;
SET @@global.validate_password_number_count= 2;
SET @@global.validate_password_number_count= 1;
SET @@global.validate_password_mixed_case_count= 2;
SET @@global.validate_password_mixed_case_count= 1;
SET @@global.validate_password_special_char_count= 2;
SET @@global.validate_password_special_char_count= 1;
SET @@global.validate_password_policy=STRONG;
SET @@global.validate_password_dictionary_file="/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/share//dictionary.txt";
SET @@global.validate_password_policy=STRONG;
SELECT VALIDATE_PASSWORD_STRENGTH('password', 0);
SELECT VALIDATE_PASSWORD_STRENGTH();
SELECT VALIDATE_PASSWORD_STRENGTH('');
SELECT VALIDATE_PASSWORD_STRENGTH('pass');
SELECT VALIDATE_PASSWORD_STRENGTH('password');
SELECT VALIDATE_PASSWORD_STRENGTH('password0000');
SELECT VALIDATE_PASSWORD_STRENGTH('password1A#');
SELECT VALIDATE_PASSWORD_STRENGTH('PA12wrd!#');
SELECT VALIDATE_PASSWORD_STRENGTH('PA00wrd!#');
SET NAMES 'ujis';
SELECT VALIDATE_PASSWORD_STRENGTH('PA12wrd!#');
SET @@global.validate_password_policy=MEDIUM;
SET @@global.validate_password_policy=LOW;
SET @@global.validate_password_length= 4;
SET @@global.validate_password_special_char_count= 0;
SET @@global.validate_password_mixed_case_count= 0;
show session status;
SET @@global.validate_password_length=default;
SET @@global.validate_password_number_count=default;
SET @@global.validate_password_mixed_case_count=default;
SET @@global.validate_password_special_char_count=default;
SET @@global.validate_password_policy=default;
SET @@global.validate_password_dictionary_file=default;
SELECT @@validate_password_length, @@validate_password_number_count, @@validate_password_mixed_case_count, @@validate_password_special_char_count, @@validate_password_policy, @@validate_password_dictionary_file;
SET @@global.validate_password_policy=STRONG;
SET @@global.validate_password_dictionary_file="/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/dictionary2.txt";
SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'validate_password_dictionary_file_words_count';
SELECT VARIABLE_VALUE into @ts1 FROM performance_schema.global_status WHERE VARIABLE_NAME = "validate_password_dictionary_file_last_parsed";
SELECT @ts1;
SELECT LENGTH(@ts1);
SET @@global.validate_password_dictionary_file="/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/tmp/dictionary.txt";
SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'validate_password_dictionary_file_words_count';
SELECT VARIABLE_VALUE into @ts2 FROM performance_schema.global_status WHERE VARIABLE_NAME = "validate_password_dictionary_file_last_parsed";
SELECT @ts1 <> @ts2;
SET @@global.validate_password_dictionary_file=NULL;
SELECT NAME FROM performance_schema.setup_instruments WHERE NAME LIKE '%validate%';
SELECT NAME FROM performance_schema.rwlock_instances WHERE NAME LIKE '%validate%';
SET @@global.validate_password_policy=DEFAULT;
UNINSTALL PLUGIN validate_password;
INSTALL PLUGIN validate_password SONAME 'validate_password.so';
CREATE ROLE r1;
DROP ROLE r1;
UNINSTALL PLUGIN validate_password;
