call mtr.add_suppression("Dictionary file not specified");
CREATE USER 'base_user'@'localhost' IDENTIFIED BY 'pass', 'user1'@'localhost' IDENTIFIED BY 'pass';
GRANT ALL ON mysql.* TO 'user1'@'localhost';
INSTALL PLUGIN validate_password SONAME 'validate_password.so';
SET @@global.validate_password_policy=LOW;
CREATE USER 'user'@'localhost' IDENTIFIED BY '';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'aweg';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password3';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'passwor';
SET @@global.validate_password_length= 12;
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'afrgtyhlp98';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'iuyt567nbvfA';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password1234';
SET @@global.validate_password_mixed_case_count= 0;
SET @@global.validate_password_number_count= 0;
SET @@global.validate_password_special_char_count= 0;
SET @@global.validate_password_length= 0;
ALTER USER 'base_user'@'localhost' IDENTIFIED BY '';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'p';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password';
SET @@global.validate_password_length= -2;
SET @@global.validate_password_length= 3.5;
SET @@global.validate_password_length= 2147483647;
SET @@global.validate_password_length= 2147483648;
PREPARE stmt1 FROM 'UPDATE mysql.user SET authentication_string=(?) where USER = ?';
SET @a = REPEAT('a',2147483647);
SET @b = 'user@localhost';
EXECUTE stmt1 USING @a,@b;
DEALLOCATE PREPARE stmt1;
SET @@global.validate_password_length= 4294967295;
SET @@global.validate_password_length= 8;
PREPARE stmt1 FROM 'UPDATE mysql.user SET authentication_string=(?) where USER = ?';
SET @a = REPEAT('a',1048576);
SET @b = 'user@localhost';
EXECUTE stmt1 USING @a,@b;
DEALLOCATE PREPARE stmt1;
SET @@global.validate_password_mixed_case_count= 1;
SET @@global.validate_password_number_count= 1;
SET @@global.validate_password_special_char_count= 1;
SET @@global.validate_password_policy=MEDIUM;
SET @@global.validate_password_number_count= 0;
CREATE USER 'user'@'localhost' IDENTIFIED BY 'aedfoiASE$%';
ALTER USER 'user'@'localhost' IDENTIFIED BY 'foiuiuytd78';
ALTER USER 'user'@'localhost' IDENTIFIED BY 'pasretryFRGH&^98';
SET @@global.validate_password_mixed_case_count= 0;
CREATE USER 'user'@'localhost' IDENTIFIED BY 'aedSWEhjui';
ALTER USER 'user'@'localhost' IDENTIFIED BY 'gruyuHOIU&*(';
ALTER USER 'user'@'localhost' IDENTIFIED BY 'passwor0987**&';
SET @@global.validate_password_special_char_count= 0;
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'piufgklol';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password1A#';
SET @@global.validate_password_special_char_count= 1;
SET @@global.validate_password_number_count= 1;
SET @@global.validate_password_mixed_case_count= 1;
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'erftuiik';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password1A#';
SET @@global.validate_password_number_count= 2;
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password1A#';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password12A#';
SET @@global.validate_password_number_count= 1;
SET @@global.validate_password_mixed_case_count= 2;
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password1A#';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password1AB#';
SET @@global.validate_password_mixed_case_count= 1;
SET @@global.validate_password_special_char_count= 2;
SET @@global.validate_password_special_char_count= 1;
SET @@global.validate_password_policy=STRONG;
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password1A#';
SET @@global.validate_password_dictionary_file="/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/share//dictionary.txt";
SET @@global.validate_password_policy=STRONG;
CREATE USER 'user'@'localhost' IDENTIFIED BY 'password';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'password1A#';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'pass12345A#';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'pass0000A#';
ALTER USER 'base_user'@'localhost' IDENTIFIED BY 'PA00wrd!#';
SELECT VALIDATE_PASSWORD_STRENGTH('password', 0);
SELECT VALIDATE_PASSWORD_STRENGTH();
SELECT VALIDATE_PASSWORD_STRENGTH('');
SELECT VALIDATE_PASSWORD_STRENGTH('pass');
SELECT VALIDATE_PASSWORD_STRENGTH('password');
SELECT VALIDATE_PASSWORD_STRENGTH('password0000');
