set names binary;
select hex(concat(1));
create table t1 as select concat(1) as c1;
show create table t1;
select hex(c1) from t1;
drop table t1;
select hex(concat(18446744073709551615));
create table t1 as select concat(18446744073709551615) as c1;
show create table t1;
select hex(c1) from t1;
drop table t1;
select hex(concat(1.1));
create table t1 as select concat(1.1) as c1;
show create table t1;
select hex(c1) from t1;
drop table t1;
select hex(concat('a', 1+2)), charset(concat(1+2));
create table t1 as select concat(1+2) as c1;
show create table t1;
drop table t1;
select hex(concat(1-2));
create table t1 as select concat(1-2) as c1;
show create table t1;
drop table t1;
select hex(concat(1*2));
create table t1 as select concat(1*2) as c1;
show create table t1;
drop table t1;
select hex(concat(1/2));
create table t1 as select concat(1/2) as c1;
show create table t1;
drop table t1;
select hex(concat(1 div 2));
create table t1 as select concat(1 div 2) as c1;
show create table t1;
drop table t1;
select hex(concat(1 % 2));
create table t1 as select concat(1 % 2) as c1;
show create table t1;
drop table t1;
select hex(concat(-1));
create table t1 as select concat(-1) as c1;
show create table t1;
drop table t1;
select hex(concat(-(1+2)));
create table t1 as select concat(-(1+2)) as c1;
show create table t1;
drop table t1;
select hex(concat(1|2));
create table t1 as select concat(1|2) as c1;
show create table t1;
drop table t1;
select hex(concat(1&2));
create table t1 as select concat(1&2) as c1;
show create table t1;
drop table t1;
select hex(concat(bit_count(12)));
create table t1 as select concat(bit_count(12)) as c1;
show create table t1;
drop table t1;
select hex(concat(2<<1));
create table t1 as select concat(2<<1) as c1;
show create table t1;
drop table t1;
select hex(concat(2>>1));
create table t1 as select concat(2>>1) as c1;
show create table t1;
drop table t1;
select hex(concat(~0));
create table t1 as select concat(~0) as c1;
show create table t1;
drop table t1;
select hex(concat(3^2));
create table t1 as select concat(3^2) as c1;
show create table t1;
drop table t1;
select hex(concat(abs(-2)));
create table t1 as select concat(abs(-2)) as c1;
show create table t1;
drop table t1;
select hex(left(concat(exp(2)),1));
create table t1 as select concat(exp(2)) as c1;
