SET NAMES gb18030;
SET CHARACTER_SET_DATABASE = gb18030;
CREATE DATABASE `����`;
CREATE DATABASE `���ݿ�`;
USE `���ݿ�`;
USE `����`;
DROP DATABASE `���ݿ�`;
DROP DATABASE `����`;
USE test;
CREATE TABLE `����` (`�ֶ�һ` CHAR(1)) DEFAULT CHARSET = gb18030;
CREATE TABLE `ģʽ` (`������` CHAR(1)) DEFAULT CHARSET = gb18030;
CREATE TABLE `�Jແ9�0` (`�Ё9�3�9�4` CHAR(1)) DEFAULT CHARSET = gb18030;
CREATE TABLE IF NOT EXISTS `����`(`�ֶ�һ` CHAR(1)) DEFAULT CHARSET = gb18030;
CREATE TABLE IF NOT EXISTS `ģʽ` (`������` CHAR(1)) DEFAULT CHARSET = gb18030;
CREATE TABLE IF NOT EXISTS `�Jແ9�0` (`�Ё9�3�9�4` CHAR(1)) DEFAULT CHARSET = gb18030;
CREATE TABLE IF NOT EXISTS `�9�4�9�4�9�4` (`�9�3�9�3�9�3` CHAR(1)) DEFAULT CHARSET = gb18030;
CREATE TEMPORARY TABLE `�9�6�9�7�9�8` (`�9�5�9�5�9�5` CHAR(1)) DEFAULT CHARSET = gb18030;
DESC `����`;
DESC `ģʽ`;
DESC `�Jແ9�0`;
DESC `�9�4�9�4�9�4`;
DESC `�9�6�9�7�9�8`;
SHOW CREATE TABLE `����`;
SHOW CREATE TABLE `ģʽ`;
SHOW CREATE TABLE `�Jແ9�0`;
SHOW CREATE TABLE `�9�4�9�4�9�4`;
SHOW CREATE TABLE `�9�6�9�7�9�8`;
DROP TABLE `����`, `ģʽ`, `�Jແ9�0`, `�9�4�9�4�9�4`, `�9�6�9�7�9�8`;
CREATE TABLE `����` (`�ֶ�һ` CHAR(5)) DEFAULT CHARSET = gb18030;
CREATE TABLE `�Jແ9�0` (`�9�1�9�2�9�3` CHAR(5)) DEFAULT CHARSET = gb18030;
INSERT INTO `����` VALUES ('һ�����ĕ2�8'), ('���߰˾�ʮ'), ('�9�4�9�5�9�6�9�7�9�8'), ('�2�6�2�8�0�5�5�2�5�0');
INSERT INTO `�Jແ9�0` VALUES ('���3�6���F'), ('�h���h���h'), ('�9�2�9�3�9�6�9�7�9�9');
ALTER TABLE `����` ADD `���ֶ�һ` CHAR(1) FIRST;
ALTER TABLE `����` ADD `���ֶζ�` CHAR(1) AFTER `�ֶ�һ`;
ALTER TABLE `����` ADD `���ֶ���` CHAR(1);
ALTER TABLE `����` ADD INDEX (`���ֶζ�`);
ALTER TABLE `����` ADD PRIMARY KEY (`�ֶ�һ`);
ALTER TABLE `����` ADD UNIQUE (`���ֶ���`);
ALTER TABLE `����` CHANGE `���ֶζ�` `�3�2�3�2һ` CHAR(1);
ALTER TABLE `����` MODIFY `���ֶ���` CHAR(6);
DESC `����`;
SHOW CREATE TABLE `����`;
ALTER TABLE `����` DROP INDEX `���ֶζ�`;
ALTER TABLE `����` DROP PRIMARY KEY;
ALTER TABLE `����` DROP INDEX `���ֶ���`;
ALTER TABLE `����` DROP `�3�2�3�2һ`;
ALTER TABLE `����` DROP `���ֶ�һ`;
ALTER TABLE `����` DROP `���ֶ���`;
DESC `����`;
SHOW CREATE TABLE `����`;
DROP TABLE `����`, `�Jແ9�0`;
CREATE TABLE `��һ` (`�ֶ�һ` char(5)) DEFAULT CHARSET = gb18030;
INSERT INTO `��һ` VALUES ('���5�3���5�2��');
UPDATE `��һ` SET `�ֶ�һ` = ('���������2�8');
DELETE FROM `��һ` WHERE `�ֶ�һ` = '���5�3���5�2��';
DELETE FROM `��һ`;
CREATE TABLE `����` (c CHAR(5), v VARCHAR(10), t TEXT) DEFAULT CHARSET = gb18030;
INSERT INTO `����` VALUES ('�����5�2�5�0��', '�䳤�2�8�0�5�5�2�ַ����ֶ�', '�ı������5�2�5�3�5�4�ֶ�');
TRUNCATE `����`;
DROP TABLE `��һ`, `����`;
CREATE TABLE `����` (e ENUM('��', '��', 'Ŀ', '��', '��'), INDEX(e)) DEFAULT CHARSET = gb18030;
INSERT INTO `����` VALUES('��'), ('��'), ('Ŀ'), ('��'), ('��');
