SET timestamp=1;
CREATE DATABASE db1;
use db1;
CREATE TABLE t1 (a1 INTEGER, a2 INTEGER GENERATED ALWAYS AS (a1 * 2) STORED, a3 INTEGER GENERATED ALWAYS AS (a1 * 3) VIRTUAL, KEY (a1) );
DROP TABLE t1;
DROP DATABASE db1;
