set global log_bin_trust_routine_creators=1;
set table_type='MyISAM';
select @@table_type='MyISAM';
backup table t1 to 'data.txt';
restore table t1 from 'data.txt';
show plugin;
load table t1 from master;
load data from master;
SHOW INNODB STATUS;
create table t1 (t6 timestamp) type=myisam;
show table types;
show mutex status;
set sql_mode=pipes_as_concat;
select 2 || 3;
select 2 or 3;
select concat(2,3);
set sql_mode='';
select 2 || 3;
select 2 or 3;
set sql_mode=default;
create table t1 (v varchar(10) binary);
show create table t1;
drop table t1;
create table t1 (v varchar(10) character set latin1 binary);
show create table t1;
drop table t1;
create table t1 (v varchar(10) binary character set latin1);
show create table t1;
drop table t1;
create table t1 (v varchar(10) binary ascii);
show create table t1;
drop table t1;
create table t1 (v varchar(10) ascii binary);
show create table t1;
drop table t1;
create table t1 (v varchar(10) binary unicode);
show create table t1;
drop table t1;
create table t1 (v varchar(10) unicode binary);
show create table t1;
drop table t1;
create table t1 (v varchar(10));
show create table t1;
alter table t1 modify v varchar(10) binary character set latin1;
show create table t1;
alter table t1 modify v varchar(10) unicode binary;
show create table t1;
alter table t1 modify v varchar(10) binary ascii;
show create table t1;
drop table t1;
select collation(cast('a' as char(2))), collation(cast('a' as char(2) binary));
select collation(convert('a', char(2))), collation(convert('a', char(2) binary));
select collation(convert('a',char(2) ascii)), collation(convert('a',char(2) ascii binary));
create table t1 (v binary(10));
show create table t1;
drop table t1;
create table t1 (v varchar(10)) character set binary;
show create table t1;
drop table t1;
create table t1 (v varchar(10));
show create table t1;
alter table t1 character set binary;
show create table t1;
drop table t1;
create database mysqltest2 default character set = binary;
show create database mysqltest2 ;
drop database mysqltest2;
create database mysqltest2 default character set = latin1;
show create database mysqltest2 ;
alter database mysqltest2 default character set = binary;
show create database mysqltest2 ;
drop database mysqltest2;
select @@character_set_client;
set character set binary;
select @@character_set_client;
set character set default;
select @@character_set_client;
set names binary;
select @@character_set_client;
set names default;
select convert("123" using binary);
select char(123 using binary);
