drop table if exists t1;
insert into t1 values(1);
delete from t1;
update t1 set a=1;
create table t1 (a int);
select count(test.t1.b) from t1;
select count(not_existing_database.t1) from t1;
select count(not_existing_database.t1.a) from t1;
select count(not_existing_database.t1.a) from not_existing_database.t1;
select 1 from t1 order by 2;
select 1 from t1 group by 2;
select 1 from t1 order by t1.b;
select count(*),b from t1;
drop table t1;
create table t1 (a int(256));
set sql_mode='traditional';
create table t1 (a varchar(66000));
set sql_mode=default;
SET sql_mode = 'NO_ENGINE_SUBSTITUTION';
CREATE TABLE t1 (a INT);
SELECT a FROM t1 WHERE a IN(1, (SELECT IF(1=0,1,2/0)));
INSERT INTO t1 VALUES(1);
SELECT a FROM t1 WHERE a IN(1, (SELECT IF(1=0,1,2/0)));
INSERT INTO t1 VALUES(2),(3);
SELECT a FROM t1 WHERE a IN(1, (SELECT IF(1=0,1,2/0)));
DROP TABLE t1;
SET sql_mode = default;
CREATE TABLE t1( a INT );
SELECT b FROM t1;
SHOW ERRORS;
CREATE TABLE t2 SELECT b FROM t1;
SHOW ERRORS;
INSERT INTO t1 SELECT b FROM t1;
DROP TABLE t1;
flush status;
drop table if exists t1, t2;
create table t1 (a int unique);
create table t2 (a int);
drop function if exists f1;
drop function if exists f2;
create function f1() returns int begin insert into t1 (a) values (1); insert into t1 (a) values (1); return 1; end;
create function f2() returns int begin insert into t2 (a) values (1); return 2; end;
flush status;
select f1(), f2();
show status like 'Com_insert';
select * from t1;
select * from t2;
drop table t1;
drop table t2;
drop function f1;
drop function f2;
SET NAMES utf8;
SET sql_quote_show_create= _binary x'5452C39C45';
SET sql_quote_show_create= _utf8 x'5452C39C45';
SET sql_quote_show_create=_latin1 x'5452DC45';
SET sql_quote_show_create='TRÜE';
SET sql_quote_show_create=TRÜE;
SET NAMES latin1;
SET sql_quote_show_create= _binary x'5452C39C45';
SET sql_quote_show_create= _utf8 x'5452C39C45';
SET sql_quote_show_create=_latin1 x'5452DC45';
SET sql_quote_show_create='TR�E';
SET sql_quote_show_create=TR�E;
SET NAMES binary;
SET sql_quote_show_create= _binary x'5452C39C45';
SET sql_quote_show_create= _utf8 x'5452C39C45';
SET sql_quote_show_create=_latin1 x'5452DC45';
CREATE TABLE t1(c1 BINARY(10), c2 BINARY(10), c3 BINARY(10), PRIMARY KEY(c1,c2,c3));
INSERT INTO t1 (c1,c2,c3) VALUES('abc','abc','abc');
INSERT INTO t1 (c1,c2,c3) VALUES('abc','abc','abc');
DROP TABLE t1;
CREATE TABLE t1 (f1 VARBINARY(19) PRIMARY KEY);
INSERT INTO t1 VALUES ('abc\0\0');
INSERT INTO t1 VALUES ('abc\0\0');
DROP TABLE t1;
SELECT (CONVERT('0' USING latin1) IN (CHAR(COT('v') USING utf8),''));
SET NAMES utf8 COLLATE utf8_latvian_ci ;
SELECT UPDATEXML(-73 * -2465717823867977728,@@global.auto_increment_increment,null);
CREATE TABLE t1 (a INT);
CREATE TABLE t2(a INT PRIMARY KEY, b INT);
SELECT '' AS b FROM t1 GROUP BY VALUES(b);
REPLACE t2(b) SELECT '' AS b FROM t1 GROUP BY VALUES(b);
