/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
CREATE TABLE `F` ( `col_int_key` int(11) DEFAULT NULL, `col_date_key` date DEFAULT NULL, `pk` int(11) NOT NULL AUTO_INCREMENT, `col_varchar_10_utf8` varchar(10) CHARACTER SET utf8 DEFAULT NULL, `col_int` int(11) DEFAULT NULL, `col_varchar_255_latin1` varchar(255) DEFAULT NULL, `col_varchar_255_latin1_key` varchar(255) DEFAULT NULL, `col_datetime` datetime DEFAULT NULL, `col_varchar_255_utf8_key` varchar(255) CHARACTER SET utf8 DEFAULT NULL, PRIMARY KEY (`pk`), KEY `col_int_key` (`col_int_key`), KEY `col_date_key` (`col_date_key`), KEY `col_varchar_255_latin1_key` (`col_varchar_255_latin1_key`), KEY `col_varchar_255_utf8_key` (`col_varchar_255_utf8_key`) );
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
CREATE TABLE `H` ( `col_date_key` date DEFAULT NULL, `col_int` int(11) DEFAULT NULL, `col_int_key` int(11) DEFAULT NULL, `col_varchar_255_latin1` varchar(255) DEFAULT NULL, `col_varchar_255_utf8_key` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `col_varchar_10_utf8` varchar(10) CHARACTER SET utf8 DEFAULT NULL, `pk` int(11) NOT NULL AUTO_INCREMENT, `col_datetime` datetime DEFAULT NULL, `col_varchar_255_latin1_key` varchar(255) DEFAULT NULL, PRIMARY KEY (`pk`), KEY `col_date_key` (`col_date_key`), KEY `col_int_key` (`col_int_key`), KEY `col_varchar_255_utf8_key` (`col_varchar_255_utf8_key`), KEY `col_varchar_255_latin1_key` (`col_varchar_255_latin1_key`) );
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
SET @@SESSION.sort_buffer_size=32768;
SET @@SESSION.sort_buffer_size=default;
DROP TABLE F, H;
CREATE TABLE t1 ( pk INTEGER, j JSON );
EXPLAIN FORMAT=tree SELECT j FROM t1 ORDER BY pk;
DROP TABLE t1;
