drop table if exists t1,t2;
create table t1 (a int not null auto_increment primary key);
insert into t1 values(0);
lock table t1 read;
flush table t1;
unlock tables;
lock table t1 write;
flush table t1;
check table t1;
unlock tables;
lock table t1 write;
lock table t1 read;
flush table t1;
select * from t1;
unlock tables;
reap;
unlock tables;
lock table t1 write;
lock table t1 write;
flush table t1;
select * from t1;
unlock tables;
reap;
unlock tables;
select * from t1;
drop table t1;
create table t1(table_id char(20) primary key);
create table t2(table_id char(20) primary key);
insert into t1 values ('test.t1');
insert into t1 values ('');
insert into t2 values ('test.t2');
insert into t2 values ('');
handler t1 open as a1;
handler t1 open as a2;
handler t2 open;
handler a1 read first limit 9;
handler a2 read first limit 9;
handler t2 read first limit 9;
flush tables;
handler a1 read first limit 9;
handler a2 read first limit 9;
handler t2 read first limit 9;
handler t1 open as a1;
handler t1 open as a2;
handler t2 open;
handler a1 read first limit 9;
handler a2 read first limit 9;
handler t2 read first limit 9;
flush table t1;
handler a1 read first limit 9;
handler a2 read first limit 9;
handler t2 read first limit 9;
flush table t2;
handler t2 close;
drop table t1;
drop table t2;
create table t1(table_id char(20) primary key);
insert into t1 values ('Record-01');
insert into t1 values ('Record-02');
insert into t1 values ('Record-03');
insert into t1 values ('Record-04');
insert into t1 values ('Record-05');
handler t1 open;
handler t1 read first limit 1;
handler t1 read next limit 1;
handler t1 read next limit 1;
flush table t1;
handler t1 read next limit 1;
handler t1 read next limit 1;
handler t1 close;
drop table t1;
FLUSH TABLES WITH READ LOCK ;
FLUSH TABLES WITH READ LOCK ;
UNLOCK TABLES;
SET @old_innodb_file_per_table= @@GLOBAL.innodb_file_per_table;
SET GLOBAL innodb_file_per_table= 1;
SET @export = 10;
CREATE PROCEDURE p1(export INT) BEGIN END;
DROP PROCEDURE p1;
CREATE PROCEDURE p1() BEGIN DECLARE export INT; END;
DROP PROCEDURE p1;
CREATE PROCEDURE export() BEGIN END;
DROP PROCEDURE export;
FLUSH TABLES FOR EXPORT;
FLUSH TABLES WITH EXPORT;
CREATE TABLE t1 (i INT) engine=InnoDB;
CREATE TABLE t2 LIKE t1;
FLUSH TABLES t1,t2 WITH EXPORT;
FLUSH TABLES t1, t2 FOR EXPORT;
UNLOCK TABLES;
FLUSH TABLES t1, t2 for ExPoRt;
UNLOCK TABLES;
FLUSH LOCAL TABLES t1, t2 FOR EXPORT;
UNLOCK TABLES;
FLUSH LOCAL TABLES test.t1, test.t2 for ExPoRt;
UNLOCK TABLES;
DROP TABLES t1, t2;
CREATE TABLE export (i INT) engine=InnoDB;
FLUSH TABLE export FOR EXPORT;
UNLOCK TABLES;
DROP TABLE export;
CREATE VIEW v1 AS SELECT 1;
CREATE TEMPORARY TABLE t1 (a INT);
FLUSH TABLES v1 FOR EXPORT;
FLUSH TABLES t1 FOR EXPORT;
FLUSH TABLES non_existent FOR EXPORT;
DROP TEMPORARY TABLE t1;
DROP VIEW v1;
CREATE TABLE t1 (a INT PRIMARY KEY, b INT) engine= InnoDB;
CREATE TABLE t2 (a INT) engine= InnoDB;
START TRANSACTION;
INSERT INTO t1 VALUES (1, 1);
FLUSH TABLES t1 FOR EXPORT;
COMMIT;
reap;
INSERT INTO t2 VALUES (1);
INSERT INTO t1 VALUES (2, 2);
UNLOCK TABLES;
reap;
START TRANSACTION;
SELECT * FROM t1;
FLUSH TABLES t1 FOR EXPORT;
COMMIT;
SELECT * FROM t1;
UNLOCK TABLES;
START TRANSACTION;
SELECT * FROM t1;
ALTER TABLE t1 ADD INDEX i1(b);
FLUSH TABLE t1 FOR EXPORT;
COMMIT;
reap;
reap;
UNLOCK TABLES;
FLUSH TABLE t1 FOR EXPORT;
DROP TABLE t1;
UNLOCK TABLES;
reap;
show session status;
DROP TABLE t2;
CREATE TABLE t1(a INT) engine= InnoDB;
FLUSH TABLES WITH READ LOCK;
FLUSH TABLE t1 FOR EXPORT;
UNLOCK TABLES;
show session status;
UNLOCK TABLES;
DROP TABLE t1;
CREATE DATABASE db1;
CREATE TABLE db1.t1 (a INT) engine= InnoDB;
FLUSH TABLE db1.t1 FOR EXPORT;
UNLOCK TABLES;
show session status;
FLUSH TABLE db1.t1 FOR EXPORT;
show session status;
FLUSH TABLE db1.t1 FOR EXPORT;
show session status;
FLUSH TABLE db1.t1 FOR EXPORT;
show session status;
FLUSH TABLE db1.t1 FOR EXPORT;
show session status;
DROP TABLE db1.t1;
DROP DATABASE db1;
CREATE TABLE t1 (a INT) engine= InnoDB;
CREATE TABLE t2 (a INT) engine= InnoDB;
FLUSH TABLE t1 FOR EXPORT;
FLUSH TABLE t2 FOR EXPORT;
UNLOCK TABLES;
FLUSH TABLE t1 FOR EXPORT;
UNLOCK TABLES;
reap;
UNLOCK TABLES;
LOCK TABLE t1 READ;
FLUSH TABLE t1 FOR EXPORT;
UNLOCK TABLES;
UNLOCK TABLES;
FLUSH TABLE t1 FOR EXPORT;
LOCK TABLE t1 READ;
UNLOCK TABLES;
UNLOCK TABLES;
show session status;
DROP TABLE t1, t2;
CREATE TABLE t1 ( i INT ) ENGINE = Innodb;
FLUSH TABLE t1 FOR EXPORT;
FLUSH TABLE t1 FOR EXPORT;
START TRANSACTION;
FLUSH TABLE t1 FOR EXPORT;
UNLOCK TABLES;
DROP TABLE t1;
CREATE TABLE t1 ( i INT ) ENGINE = Innodb;
INSERT INTO t1 VALUES (100),(200);
FLUSH LOCAL TABLES test.t1 FOR EXPORT;
FLUSH LOCAL TABLES t1 FOR EXPORT;
UNLOCK TABLE;
reap;
SELECT * FROM t1 ORDER BY i;
FLUSH NO_WRITE_TO_BINLOG TABLES test.t1 FOR EXPORT;
UNLOCK TABLES;
reap;
SELECT * FROM t1 ORDER BY i;
UNLOCK TABLE;
DROP TABLE t1;
CREATE TABLE t1 ( i INT ) ENGINE = Innodb;
INSERT INTO t1 VALUES (100),(200);
START TRANSACTION;
INSERT INTO t1 VALUES (300);
FLUSH LOCAL TABLES test.t1 FOR EXPORT;
ROLLBACK;
SELECT * FROM t1 ORDER BY i;
START TRANSACTION;
INSERT INTO t1 VALUES (400);
LOCK TABLES test.t1 READ;
ROLLBACK;
SELECT * FROM t1 ORDER BY i;
UNLOCK TABLES;
DROP TABLE t1;
CREATE TABLE t1 ( i INT ) ENGINE = Innodb;
LOCK TABLES test.t1 WRITE;
LOCK TABLES test.t1 READ;
FLUSH TABLES test.t1 FOR EXPORT;
LOCK TABLES test.t1 WRITE;
UNLOCK TABLES;
DROP TABLE t1;
show session status;
SET GLOBAL innodb_file_per_table= @old_innodb_file_per_table;
