SET @old_log_bin_trust_function_creators= @@global.log_bin_trust_function_creators;
SET GLOBAL log_bin_trust_function_creators = 1;
set @orig_sql_mode_session= @@SESSION.sql_mode;
set @orig_sql_mode_global= @@GLOBAL.sql_mode;
SET NAMES binary;
grant CREATE TEMPORARY TABLES, LOCK TABLES on mysqltest.* to mysqltest_1@localhost;
show grants for mysqltest_1@localhost;
flush privileges;
show grants for mysqltest_1@localhost;
revoke CREATE TEMPORARY TABLES on mysqltest.* from mysqltest_1@localhost;
show grants for mysqltest_1@localhost;
grant ALL PRIVILEGES on mysqltest.* to mysqltest_1@localhost with GRANT OPTION;
flush privileges;
show grants for mysqltest_1@localhost;
revoke LOCK TABLES, ALTER on mysqltest.* from mysqltest_1@localhost;
show grants for mysqltest_1@localhost;
revoke all privileges on mysqltest.* from mysqltest_1@localhost;
flush privileges;
grant usage on test.* to mysqltest_1@localhost with grant option;
show grants for mysqltest_1@localhost;
flush privileges;
show grants for mysqltest_1@localhost;
create table t1 (a int);
GRANT select,update,insert on t1 to mysqltest_1@localhost;
GRANT select (a), update (a),insert(a), references(a) on t1 to mysqltest_1@localhost;
show grants for mysqltest_1@localhost;
REVOKE select (a), update on t1 from mysqltest_1@localhost;
show grants for mysqltest_1@localhost;
REVOKE select,update,insert,insert (a) on t1 from mysqltest_1@localhost;
show grants for mysqltest_1@localhost;
GRANT select,references on t1 to mysqltest_1@localhost;
grant all on test.* to mysqltest_3@localhost with grant option;
revoke all on test.* from mysqltest_3@localhost;
show grants for mysqltest_3@localhost;
revoke grant option on test.* from mysqltest_3@localhost;
show grants for mysqltest_3@localhost;
grant all on test.t1 to mysqltest_2@localhost with grant option;
revoke all on test.t1 from mysqltest_2@localhost;
show grants for mysqltest_2@localhost;
revoke grant option on test.t1 from mysqltest_2@localhost;
show grants for mysqltest_2@localhost;
flush privileges;
drop table t1;
create table t1 (abcdefghijklmnopqrstuvwxyz int);
GRANT select (abcdefghijklmnopqrstuvwxyz) on t1 to mysqltest_1@localhost;
show grants for mysqltest_1@localhost;
drop table t1;
GRANT FILE on mysqltest.*  to mysqltest_1@localhost;
select 1;
alter table mysql.db order by db asc;
flush privileges;
show grants for test11@localhost;
alter table mysql.db order by db desc;
flush privileges;
show grants for test11@localhost;
create database mysqltest1;
grant usage on mysqltest1.* to test6123;
drop database mysqltest1;
flush privileges;
create table t1 (a int);
set sql_mode=ansi_quotes;
set sql_mode=default;
set sql_quote_show_create=0;
set sql_mode="ansi_quotes";
set sql_quote_show_create=1;
set sql_mode="";
drop table t1;
grant select, update, insert on test.* to mysqltest_1@localhost;
show grants for mysqltest_1@localhost;
SET NAMES koi8r;
CREATE DATABASE ��;
USE ��;
CREATE TABLE ��� (��� INT);
CREATE USER ����@localhost;
GRANT SELECT ON ��.* TO ����@localhost;
SHOW GRANTS FOR ����@localhost;
REVOKE SELECT ON ��.* FROM ����@localhost;
GRANT SELECT ON ��.��� TO ����@localhost;
SHOW GRANTS FOR ����@localhost;
REVOKE SELECT ON ��.��� FROM ����@localhost;
GRANT SELECT (���) ON ��.��� TO ����@localhost;
SHOW GRANTS FOR ����@localhost;
REVOKE SELECT (���) ON ��.��� FROM ����@localhost;
DROP USER ����@localhost;
DROP DATABASE ��;
SET NAMES latin1;
USE test;
CREATE TABLE t1 (a int );
CREATE TABLE t2 LIKE t1;
CREATE TABLE t3 LIKE t1;
CREATE TABLE t4 LIKE t1;
CREATE TABLE t5 LIKE t1;
CREATE TABLE t6 LIKE t1;
CREATE TABLE t7 LIKE t1;
CREATE TABLE t8 LIKE t1;
CREATE TABLE t9 LIKE t1;
CREATE TABLE t10 LIKE t1;
CREATE DATABASE testdb1;
CREATE DATABASE testdb2;
CREATE DATABASE testdb3;
CREATE DATABASE testdb4;
CREATE DATABASE testdb5;
CREATE DATABASE testdb6;
CREATE DATABASE testdb7;
CREATE DATABASE testdb8;
CREATE DATABASE testdb9;
CREATE DATABASE testdb10;
DROP TABLE t1,t2,t3,t4,t5,t6,t7,t8,t9,t10;
DROP DATABASE testdb1;
DROP DATABASE testdb2;
DROP DATABASE testdb3;
DROP DATABASE testdb4;
DROP DATABASE testdb5;
DROP DATABASE testdb6;
DROP DATABASE testdb7;
DROP DATABASE testdb8;
DROP DATABASE testdb9;
DROP DATABASE testdb10;
create table t1(a int, b int, c int, d int);
select Host,Db,User,Table_name,Column_name,Column_priv from mysql.columns_priv order by Column_name;
select Host,Db,User,Table_name,Column_name,Column_priv from mysql.columns_priv;
drop table t1;
create database mysqltest_1;
create database mysqltest_2;
create table mysqltest_1.t1 select 1 a, 2 q;
create table mysqltest_1.t2 select 1 b, 2 r;
create table mysqltest_2.t1 select 1 c, 2 s;
create table mysqltest_2.t2 select 1 d, 2 t;
grant update (a) on mysqltest_1.t1 to mysqltest_3@localhost;
grant select (b) on mysqltest_1.t2 to mysqltest_3@localhost;
grant select (c) on mysqltest_2.t1 to mysqltest_3@localhost;
grant update (d) on mysqltest_2.t2 to mysqltest_3@localhost;
SELECT * FROM INFORMATION_SCHEMA.COLUMN_PRIVILEGES WHERE GRANTEE = '''mysqltest_3''@''localhost'''  ORDER BY TABLE_NAME,COLUMN_NAME,PRIVILEGE_TYPE;
SELECT * FROM INFORMATION_SCHEMA.TABLE_PRIVILEGES WHERE GRANTEE = '''mysqltest_3''@''localhost'''  ORDER BY TABLE_NAME,PRIVILEGE_TYPE;
SELECT * from INFORMATION_SCHEMA.SCHEMA_PRIVILEGES WHERE GRANTEE = '''mysqltest_3''@''localhost'''  ORDER BY TABLE_SCHEMA,PRIVILEGE_TYPE;
SELECT * from INFORMATION_SCHEMA.USER_PRIVILEGES WHERE GRANTEE = '''mysqltest_3''@''localhost'''  ORDER BY TABLE_CATALOG,PRIVILEGE_TYPE;
update mysqltest_1.t1, mysqltest_1.t2 set q=10 where b=1;
update mysqltest_1.t2, mysqltest_2.t2 set d=20 where d=1;
update mysqltest_1.t1, mysqltest_2.t2 set d=20 where d=1;
update mysqltest_2.t1, mysqltest_1.t2 set c=20 where b=1;
update mysqltest_2.t1, mysqltest_2.t2 set d=10 where s=2;
update mysqltest_1.t1, mysqltest_2.t2 set a=10,d=10;
update mysqltest_1.t1, mysqltest_2.t1 set a=20 where c=20;
select t1.*,t2.* from mysqltest_1.t1,mysqltest_1.t2;
select t1.*,t2.* from mysqltest_2.t1,mysqltest_2.t2;
revoke all on mysqltest_1.t1 from mysqltest_3@localhost;
revoke all on mysqltest_1.t2 from mysqltest_3@localhost;
revoke all on mysqltest_2.t1 from mysqltest_3@localhost;
revoke all on mysqltest_2.t2 from mysqltest_3@localhost;
grant all on mysqltest_2.* to mysqltest_3@localhost;
grant select on *.* to mysqltest_3@localhost;
grant select on mysqltest_2.t1 to mysqltest_3@localhost;
flush privileges;
use mysqltest_1;
update mysqltest_2.t1, mysqltest_2.t2 set c=500,d=600;
update mysqltest_1.t1, mysqltest_1.t2 set a=100,b=200;
use mysqltest_2;
update mysqltest_1.t1, mysqltest_1.t2 set a=100,b=200;
update mysqltest_2.t1, mysqltest_1.t2 set c=100,b=200;
update mysqltest_1.t1, mysqltest_2.t2 set a=100,d=200;
select t1.*,t2.* from mysqltest_1.t1,mysqltest_1.t2;
select t1.*,t2.* from mysqltest_2.t1,mysqltest_2.t2;
flush privileges;
drop database mysqltest_1;
drop database mysqltest_2;
SHOW PRIVILEGES;
create database mysqltest;
create table mysqltest.t1 (a int,b int,c int);
grant all on mysqltest.t1 to mysqltest_1@localhost;
alter table t1 rename t2;
revoke all privileges on mysqltest.t1 from mysqltest_1@localhost;
drop database mysqltest;
CREATE USER dummy@localhost;
CREATE DATABASE mysqltest;
CREATE TABLE mysqltest.dummytable (dummyfield INT);
CREATE VIEW mysqltest.dummyview AS SELECT dummyfield FROM mysqltest.dummytable;
GRANT ALL PRIVILEGES ON mysqltest.dummytable TO dummy@localhost;
GRANT ALL PRIVILEGES ON mysqltest.dummyview TO dummy@localhost;
SHOW GRANTS FOR dummy@localhost;
use INFORMATION_SCHEMA;
SELECT TABLE_SCHEMA, TABLE_NAME, GROUP_CONCAT(PRIVILEGE_TYPE ORDER BY PRIVILEGE_TYPE SEPARATOR ', ') AS PRIVILEGES FROM TABLE_PRIVILEGES WHERE GRANTEE = '\'dummy\'@\'localhost\'' GROUP BY TABLE_SCHEMA, TABLE_NAME;
FLUSH PRIVILEGES;
SHOW GRANTS FOR dummy@localhost;
SELECT TABLE_SCHEMA, TABLE_NAME, GROUP_CONCAT(PRIVILEGE_TYPE ORDER BY PRIVILEGE_TYPE SEPARATOR ', ') AS PRIVILEGES FROM TABLE_PRIVILEGES WHERE GRANTEE = '\'dummy\'@\'localhost\'' GROUP BY TABLE_SCHEMA, TABLE_NAME;
SHOW FIELDS FROM mysql.tables_priv;
use test;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM dummy@localhost;
DROP USER dummy@localhost;
DROP DATABASE mysqltest;
CREATE USER dummy@localhost;
CREATE DATABASE mysqltest;
CREATE TABLE mysqltest.dummytable (dummyfield INT);
CREATE VIEW mysqltest.dummyview AS SELECT dummyfield FROM mysqltest.dummytable;
GRANT CREATE VIEW ON mysqltest.dummytable TO dummy@localhost;
GRANT CREATE VIEW ON mysqltest.dummyview TO dummy@localhost;
SHOW GRANTS FOR dummy@localhost;
use INFORMATION_SCHEMA;
SELECT TABLE_SCHEMA, TABLE_NAME, GROUP_CONCAT(PRIVILEGE_TYPE ORDER BY PRIVILEGE_TYPE SEPARATOR ', ') AS PRIVILEGES FROM TABLE_PRIVILEGES WHERE GRANTEE = '\'dummy\'@\'localhost\'' GROUP BY TABLE_SCHEMA, TABLE_NAME;
FLUSH PRIVILEGES;
SHOW GRANTS FOR dummy@localhost;
SELECT TABLE_SCHEMA, TABLE_NAME, GROUP_CONCAT(PRIVILEGE_TYPE ORDER BY PRIVILEGE_TYPE SEPARATOR ', ') AS PRIVILEGES FROM TABLE_PRIVILEGES WHERE GRANTEE = '\'dummy\'@\'localhost\'' GROUP BY TABLE_SCHEMA, TABLE_NAME;
use test;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM dummy@localhost;
DROP USER dummy@localhost;
DROP DATABASE mysqltest;
CREATE USER dummy@localhost;
CREATE DATABASE mysqltest;
CREATE TABLE mysqltest.dummytable (dummyfield INT);
CREATE VIEW mysqltest.dummyview AS SELECT dummyfield FROM mysqltest.dummytable;
GRANT SHOW VIEW ON mysqltest.dummytable TO dummy@localhost;
GRANT SHOW VIEW ON mysqltest.dummyview TO dummy@localhost;
SHOW GRANTS FOR dummy@localhost;
use INFORMATION_SCHEMA;
SELECT TABLE_SCHEMA, TABLE_NAME, GROUP_CONCAT(PRIVILEGE_TYPE ORDER BY PRIVILEGE_TYPE SEPARATOR ', ') AS PRIVILEGES FROM TABLE_PRIVILEGES WHERE GRANTEE = '\'dummy\'@\'localhost\'' GROUP BY TABLE_SCHEMA, TABLE_NAME;
FLUSH PRIVILEGES;
SHOW GRANTS FOR dummy@localhost;
SELECT TABLE_SCHEMA, TABLE_NAME, GROUP_CONCAT(PRIVILEGE_TYPE ORDER BY PRIVILEGE_TYPE SEPARATOR ', ') AS PRIVILEGES FROM TABLE_PRIVILEGES WHERE GRANTEE = '\'dummy\'@\'localhost\'' GROUP BY TABLE_SCHEMA, TABLE_NAME;
use test;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM dummy@localhost;
DROP USER dummy@localhost;
DROP DATABASE mysqltest;
use mysql;
insert into tables_priv values ('','test_db','mysqltest_1','test_table','test_grantor',CURRENT_TIMESTAMP,'Select','Select');
flush privileges;
flush privileges;
use test;
set names koi8r;
create database ��;
grant select on ��.* to root@localhost;
select hex(Db) from mysql.db where Db='��';
show grants for root@localhost;
flush privileges;
show grants for root@localhost;
drop database ��;
revoke select on ��.* from root@localhost;
show grants for root@localhost;
set names latin1;
show grants for mysqltest_7@;
show grants for mysqltest_7@;
create database mysqltest;
use mysqltest;
create table t1(f1 int);
CREATE USER mysqltest1@'%', mysqltest1@'192.%';
GRANT DELETE ON mysqltest.t1 TO mysqltest1@'%';
GRANT SELECT ON mysqltest.t1 TO mysqltest1@'192.%';
show grants for mysqltest1@'192.%';
show grants for mysqltest1@'%';
flush privileges;
drop database mysqltest;
create database db27515;
use db27515;
create table t1 (a int);
rename table t1 to t2;
drop database db27515;
use test;
create table t1 (a int);
flush privileges;
grant select on mysqltest.* to mysqltest_8@'';
show grants for mysqltest_8@'';
grant select on mysqltest.* to mysqltest_8@;
show grants for mysqltest_8@;
grant select on mysqltest.* to mysqltest_8;
show grants for mysqltest_8;
select * from  information_schema.schema_privileges where grantee like "'mysqltest_8'%";
select * from t1;
revoke select on mysqltest.* from mysqltest_8@'';
revoke select on mysqltest.* from mysqltest_8;
show grants for mysqltest_8@'';
show grants for mysqltest_8;
select * from  information_schema.schema_privileges where grantee like "'mysqltest_8'%";
flush privileges;
show grants for mysqltest_8@'';
show grants for mysqltest_8@;
grant select on mysqltest.* to mysqltest_8@'';
flush privileges;
show grants for mysqltest_8@;
revoke select on mysqltest.* from mysqltest_8@'';
flush privileges;
grant update (a) on t1 to mysqltest_8@'';
grant update (a) on t1 to mysqltest_8;
show grants for mysqltest_8@'';
show grants for mysqltest_8;
flush privileges;
show grants for mysqltest_8@'';
show grants for mysqltest_8;
select * from  information_schema.column_privileges;
select * from t1;
revoke update (a) on t1 from mysqltest_8@'';
revoke update (a) on t1 from mysqltest_8;
show grants for mysqltest_8@'';
show grants for mysqltest_8;
select * from  information_schema.column_privileges;
flush privileges;
show grants for mysqltest_8@'';
show grants for mysqltest_8;
grant update on t1 to mysqltest_8@'';
grant update on t1 to mysqltest_8;
show grants for mysqltest_8@'';
show grants for mysqltest_8;
flush privileges;
show grants for mysqltest_8@'';
show grants for mysqltest_8;
select * from  information_schema.table_privileges where table_schema NOT IN ('sys','mysql');
select * from t1;
revoke update on t1 from mysqltest_8@'';
revoke update on t1 from mysqltest_8;
show grants for mysqltest_8@'';
show grants for mysqltest_8;
select * from  information_schema.table_privileges where table_schema NOT IN ('sys','mysql');
flush privileges;
show grants for mysqltest_8@'';
show grants for mysqltest_8;
grant all privileges on mysqltest.* to mysqltest_8@'';
grant select on mysqltest.* to mysqltest_8@'';
grant update on t1 to mysqltest_8@'';
grant update (a) on t1 to mysqltest_8@'';
grant all privileges on mysqltest.* to mysqltest_8;
show grants for mysqltest_8@'';
show grants for mysqltest_8;
select * from t1;
flush privileges;
show grants for mysqltest_8@'';
show grants for mysqltest_8;
show grants for mysqltest_8@'';
show grants for mysqltest_8;
show grants for mysqltest_8;
show grants for mysqltest_8@host8;
flush privileges;
drop table t2;
drop table t1;
CREATE DATABASE mysqltest3;
USE mysqltest3;
CREATE TABLE t_nn (c1 INT);
CREATE VIEW  v_nn AS SELECT * FROM t_nn;
CREATE DATABASE mysqltest2;
USE mysqltest2;
CREATE TABLE t_nn (c1 INT);
CREATE VIEW  v_nn AS SELECT * FROM t_nn;
CREATE VIEW  v_yn AS SELECT * FROM t_nn;
CREATE VIEW  v_gy AS SELECT * FROM t_nn;
CREATE VIEW  v_ny AS SELECT * FROM t_nn;
CREATE VIEW  v_yy AS SELECT * FROM t_nn WHERE c1=55;
CREATE USER 'mysqltest_1'@'localhost' IDENTIFIED BY 'mysqltest_1';
GRANT SHOW VIEW        ON mysqltest2.v_ny TO 'mysqltest_1'@'localhost';
GRANT SELECT           ON mysqltest2.v_yn TO 'mysqltest_1'@'localhost';
GRANT SELECT           ON mysqltest2.*    TO 'mysqltest_1'@'localhost';
GRANT SHOW VIEW,SELECT ON mysqltest2.v_yy TO 'mysqltest_1'@'localhost';
SHOW CREATE VIEW  mysqltest2.v_nn;
SHOW CREATE TABLE mysqltest2.v_nn;
SHOW CREATE VIEW  mysqltest2.v_yn;
SHOW CREATE TABLE mysqltest2.v_yn;
SHOW CREATE TABLE mysqltest2.v_ny;
SHOW CREATE VIEW  mysqltest2.v_ny;
SHOW CREATE TABLE mysqltest3.t_nn;
SHOW CREATE VIEW  mysqltest3.t_nn;
SHOW CREATE VIEW  mysqltest3.v_nn;
SHOW CREATE TABLE mysqltest3.v_nn;
SHOW CREATE TABLE mysqltest2.t_nn;
SHOW CREATE VIEW  mysqltest2.t_nn;
SHOW CREATE VIEW mysqltest2.v_yy;
SHOW CREATE TABLE mysqltest2.v_yy;
SHOW CREATE TABLE mysqltest2.v_nn;
SHOW CREATE VIEW  mysqltest2.v_nn;
SHOW CREATE TABLE mysqltest2.t_nn;
SHOW CREATE VIEW mysqltest2.t_nn;
DROP VIEW  mysqltest2.v_nn;
DROP VIEW  mysqltest2.v_yn;
DROP VIEW  mysqltest2.v_ny;
DROP VIEW  mysqltest2.v_yy;
DROP TABLE mysqltest2.t_nn;
DROP DATABASE mysqltest2;
DROP VIEW  mysqltest3.v_nn;
DROP TABLE mysqltest3.t_nn;
DROP DATABASE mysqltest3;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'mysqltest_1'@'localhost';
DROP USER 'mysqltest_1'@'localhost';
USE test;
CREATE DATABASE mysqltest1;
CREATE TABLE mysqltest1.t1 ( int_field INTEGER UNSIGNED NOT NULL, char_field CHAR(10), INDEX(`int_field`) );
CREATE TABLE mysqltest1.t2 (int_field INT);
CREATE USER mysqltest_1@localhost;
GRANT SELECT ON mysqltest1.t1 TO mysqltest_1@localhost;
SELECT USER();
SHOW GRANTS;
RENAME TABLE t1 TO t2;
ALTER TABLE t1 RENAME TO t2;
GRANT DROP ON mysqltest1.t1 TO mysqltest_1@localhost;
RENAME TABLE t1 TO t2;
ALTER TABLE t1 RENAME TO t2;
GRANT ALTER ON mysqltest1.t1 TO mysqltest_1@localhost;
SHOW GRANTS;
RENAME TABLE t1 TO t2;
ALTER TABLE t1 RENAME TO t2;
GRANT INSERT, CREATE ON mysqltest1.t1 TO mysqltest_1@localhost;
SHOW GRANTS;
GRANT INSERT, SELECT, CREATE, ALTER, DROP ON mysqltest1.t2 TO mysqltest_1@localhost;
DROP TABLE mysqltest1.t2;
SHOW GRANTS;
RENAME TABLE t1 TO t2;
RENAME TABLE t2 TO t1;
ALTER TABLE t1 RENAME TO t2;
ALTER TABLE t2 RENAME TO t1;
REVOKE DROP, INSERT ON mysqltest1.t1 FROM mysqltest_1@localhost;
REVOKE DROP, INSERT ON mysqltest1.t2 FROM mysqltest_1@localhost;
SHOW GRANTS;
RENAME TABLE t1 TO t2;
ALTER TABLE t1 RENAME TO t2;
DROP USER mysqltest_1@localhost;
DROP DATABASE mysqltest1;
USE test;
GRANT CREATE ON mysqltest.* TO 1234567890abcdefGHIKL1234567890abcdefGHIKL@localhost;
REVOKE CREATE ON mysqltest.* FROM 1234567890abcdefGHIKL1234567890abcdefGHIKL@localhost;
GRANT CREATE ON t1 TO 1234567890abcdefGHIKL1234567890abcdefGHIKL@localhost;
REVOKE CREATE ON t1 FROM 1234567890abcdefGHIKL1234567890abcdefGHIKL@localhost;
GRANT EXECUTE ON PROCEDURE p1 TO 1234567890abcdefGHIKL1234567890abcdefGHIKL@localhost;
REVOKE EXECUTE ON PROCEDURE p1 FROM 1234567890abcdefGHIKL1234567890abcdefGHIKL@localhost;
CREATE USER bug23556@localhost;
CREATE DATABASE bug23556;
GRANT SELECT ON bug23556.* TO bug23556@localhost;
USE bug23556;
CREATE TABLE t1 (a INT PRIMARY KEY);
INSERT INTO t1 VALUES (1),(2),(3),(4),(5);
GRANT DELETE ON t1 TO bug23556@localhost;
USE bug23556;
TRUNCATE t1;
USE bug23556;
REVOKE DELETE ON t1 FROM bug23556@localhost;
GRANT DROP ON t1 TO bug23556@localhost;
USE bug23556;
TRUNCATE t1;
USE bug23556;
DROP TABLE t1;
USE test;
DROP DATABASE bug23556;
DROP USER bug23556@localhost;
CREATE DATABASE mysqltest1;
CREATE DATABASE mysqltest2;
CREATE DATABASE mysqltest3;
CREATE DATABASE mysqltest4;
CREATE PROCEDURE mysqltest1.p_def() SQL SECURITY DEFINER SELECT 1;
CREATE PROCEDURE mysqltest2.p_inv() SQL SECURITY INVOKER SELECT 1;
CREATE FUNCTION mysqltest3.f_def() RETURNS INT SQL SECURITY DEFINER RETURN 1;
CREATE FUNCTION mysqltest4.f_inv() RETURNS INT SQL SECURITY INVOKER RETURN 1;
CREATE USER mysqltest_1@localhost;
GRANT EXECUTE ON PROCEDURE mysqltest1.p_def TO mysqltest_1@localhost;
GRANT EXECUTE ON PROCEDURE mysqltest2.p_inv TO mysqltest_1@localhost;
GRANT EXECUTE ON FUNCTION mysqltest3.f_def TO mysqltest_1@localhost;
GRANT EXECUTE ON FUNCTION mysqltest4.f_inv TO mysqltest_1@localhost;
GRANT ALL PRIVILEGES ON test.* TO mysqltest_1@localhost;
use mysqltest1;
use mysqltest2;
use mysqltest3;
use mysqltest4;
use test;
CALL mysqltest1.p_def();
CALL mysqltest2.p_inv();
SELECT mysqltest3.f_def();
SELECT mysqltest4.f_inv();
DROP DATABASE mysqltest1;
DROP DATABASE mysqltest2;
DROP DATABASE mysqltest3;
DROP DATABASE mysqltest4;
DROP USER mysqltest_1@localhost;
CREATE DATABASE mysqltest1;
CREATE DATABASE mysqltest2;
CREATE USER mysqltest_1@localhost;
GRANT ALL PRIVILEGES ON mysqltest1.* TO mysqltest_1@localhost;
GRANT SELECT ON mysqltest2.* TO mysqltest_1@localhost;
CREATE PROCEDURE mysqltest1.p1() SQL SECURITY INVOKER SELECT 1;
CREATE TABLE t1(c INT);
CALL mysqltest1.p1();
CREATE TABLE t1(c INT);
CREATE TABLE t1(c INT);
SHOW TABLES;
DROP DATABASE mysqltest1;
DROP DATABASE mysqltest2;
DROP USER mysqltest_1@localhost;
CREATE DATABASE mysqltest1;
CREATE DATABASE mysqltest2;
CREATE TABLE mysqltest1.t1(c INT);
CREATE TABLE mysqltest2.t2(c INT);
CREATE USER mysqltest_1@localhost, mysqltest_2@localhost;
GRANT SELECT ON mysqltest1.t1 TO mysqltest_1@localhost;
GRANT SELECT ON mysqltest2.t2 TO mysqltest_2@localhost;
SHOW TABLES FROM mysqltest1;
PREPARE stmt1 FROM 'SHOW TABLES FROM mysqltest1';
EXECUTE stmt1;
SHOW COLUMNS FROM mysqltest2.t2;
PREPARE stmt2 FROM 'SHOW COLUMNS FROM mysqltest2.t2';
EXECUTE stmt2;
REVOKE SELECT ON mysqltest1.t1 FROM mysqltest_1@localhost;
REVOKE SELECT ON mysqltest2.t2 FROM mysqltest_2@localhost;
SHOW TABLES FROM mysqltest1;
EXECUTE stmt1;
SHOW COLUMNS FROM mysqltest2.t2;
EXECUTE stmt2;
DROP DATABASE mysqltest1;
DROP DATABASE mysqltest2;
DROP USER mysqltest_1@localhost;
DROP USER mysqltest_2@localhost;
USE test;
CREATE TABLE t1 (f1 int, f2 int);
INSERT INTO t1 VALUES(1,1), (2,2);
CREATE DATABASE db27878;
CREATE USER 'mysqltest_1'@'localhost';
GRANT UPDATE(f1) ON t1 TO 'mysqltest_1'@'localhost';
GRANT SELECT ON `test`.* TO 'mysqltest_1'@'localhost';
GRANT ALL ON db27878.* TO 'mysqltest_1'@'localhost';
USE db27878;
CREATE SQL SECURITY INVOKER VIEW db27878.v1 AS SELECT * FROM test.t1;
USE db27878;
SET sql_mode = 'NO_ENGINE_SUBSTITUTION';
UPDATE v1 SET f2 = 4;
SET sql_mode = default;
SELECT * FROM test.t1;
REVOKE UPDATE (f1) ON `test`.`t1` FROM 'mysqltest_1'@'localhost';
REVOKE SELECT ON `test`.* FROM 'mysqltest_1'@'localhost';
REVOKE ALL ON db27878.* FROM 'mysqltest_1'@'localhost';
DROP USER mysqltest_1@localhost;
DROP DATABASE db27878;
USE test;
DROP TABLE t1;
FLUSH PRIVILEGES;
drop table if exists test;
drop function if exists test_function;
drop view if exists v1;
create table test (col1 varchar(30));
create function test_function() returns varchar(30) begin declare tmp varchar(30); select col1 from test limit 1 into tmp; return '1'; end;
create view v1 as select test.* from test where test.col1=test_function();
grant update (col1) on v1 to 'greg'@'localhost';
drop view v1;
drop table test;
drop function test_function;
SELECT CURRENT_USER();
SET PASSWORD FOR CURRENT_USER() = "admin";
SET PASSWORD FOR CURRENT_USER() = "";
CREATE DATABASE mysqltest1;
CREATE DATABASE mysqltest2;
use mysqltest1;
CREATE TABLE t1(a INT, b INT);
INSERT INTO t1 VALUES (1, 1);
CREATE TABLE t2(a INT);
INSERT INTO t2 VALUES (2);
CREATE TABLE mysqltest2.t3(a INT);
INSERT INTO mysqltest2.t3 VALUES (4);
PREPARE s1 FROM 'SELECT b FROM t1';
PREPARE s2 FROM 'SELECT a FROM t2';
PREPARE s3 FROM 'SHOW TABLES FROM mysqltest2';
CREATE PROCEDURE p1() SELECT b FROM t1;
CREATE PROCEDURE p2() SELECT a FROM t2;
CREATE PROCEDURE p3() SHOW TABLES FROM mysqltest2;
CALL p1;
CALL p2;
CALL p3;
EXECUTE s1;
SELECT b FROM t1;
SELECT SUM(b) OVER () FROM t1;
EXECUTE s1;
CALL p1;
SELECT a FROM t2;
EXECUTE s2;
CALL p2;
SHOW TABLES FROM mysqltest2;
EXECUTE s3;
CALL p3;
DROP DATABASE mysqltest1;
DROP DATABASE mysqltest2;
use test;
create database mysqltest1;
create function mysqltest1.f1() returns int return 0;
create procedure mysqltest1.p1() begin end;
call mysqltest1.p1();
select mysqltest1.f1();
call mysqltest1.p1();
select mysqltest1.f1();
call mysqltest1.p1();
select mysqltest1.f1();
create table mysqltest1.t11 (i int);
create table mysqltest1.t22 (i int);
call mysqltest1.p1();
select mysqltest1.f1();
select * from mysqltest1.t11;
select * from mysqltest1.t22;
call mysqltest1.p1();
select mysqltest1.f1();
select * from mysqltest1.t11;
select * from mysqltest1.t22;
call mysqltest1.p1();
select mysqltest1.f1();
select * from mysqltest1.t11;
select * from mysqltest1.t22;
call mysqltest1.p1();
select mysqltest1.f1();
select * from mysqltest1.t11;
select * from mysqltest1.t22;
drop database mysqltest1;
set names utf8;
grant select on test.* to юзер_юзер@localhost;
revoke all on test.* from юзер_юзер@localhost;
set names default;
create database mysqltest;
use mysqltest;
grant create on mysqltest.* to mysqltest@localhost;
create table t1 (i INT);
insert into t1 values (1);
create table t2 (i INT);
create table t4 (i INT);
grant select, insert on mysqltest.t2 to mysqltest@localhost;
grant         insert on mysqltest.t4 to mysqltest@localhost;
grant create, insert on mysqltest.t5 to mysqltest@localhost;
grant create, insert on mysqltest.t6 to mysqltest@localhost;
flush privileges;
insert into t2 values (1);
create table if not exists t1 select * from t2;
create table if not exists t3 select * from t2;
create table if not exists t4 select * from t2;
create table if not exists t5 select * from t2;
create table t6 select * from t2;
create table t7 select * from t2;
create table t4 select * from t2;
create table t1 select * from t2;
drop table t1,t2,t4,t5,t6;
revoke create         on mysqltest.*  from mysqltest@localhost;
revoke select, insert on mysqltest.t2 from mysqltest@localhost;
revoke insert         on mysqltest.t4 from mysqltest@localhost;
revoke create, insert on mysqltest.t5 from mysqltest@localhost;
revoke create, insert on mysqltest.t6 from mysqltest@localhost;
drop database mysqltest;
use test;
call mtr.add_suppression("Can't open and lock privilege tables");
RENAME TABLE mysql.procs_priv TO mysql.procs_gone;
FLUSH PRIVILEGES;
CREATE DATABASE mysqltest1;
CREATE PROCEDURE mysqltest1.test() SQL SECURITY DEFINER SELECT 1;
CREATE FUNCTION mysqltest1.test() RETURNS INT RETURN 1;
GRANT EXECUTE ON FUNCTION mysqltest1.test TO mysqltest_1@localhost;
GRANT ALL PRIVILEGES ON test.* TO mysqltest_1@localhost;
CALL mysqltest1.test();
DROP DATABASE mysqltest1;
RENAME TABLE mysql.procs_gone TO mysql.procs_priv;
FLUSH PRIVILEGES;
CREATE DATABASE dbbug33464;
SELECT USER() AS "", DATABASE() AS "";
CREATE PROCEDURE sp3(v1 char(20)) BEGIN SELECT * from dbbug33464.t6 where t6.f2= 'xyz'; END;
CREATE FUNCTION fn1() returns char(50) SQL SECURITY INVOKER BEGIN return 1; END;
CREATE FUNCTION fn2() returns char(50) SQL SECURITY DEFINER BEGIN return 2; END;
USE dbbug33464;
SELECT USER() AS "", DATABASE() AS "";
SELECT fn1();
SELECT fn2();
DROP FUNCTION fn1;
DROP FUNCTION fn2;
DROP PROCEDURE sp3;
USE test;
DROP DATABASE dbbug33464;
SET @@global.log_bin_trust_function_creators= @old_log_bin_trust_function_creators;
FLUSH PRIVILEGES;
SELECT @@GLOBAL.sql_mode;
SELECT @@SESSION.sql_mode;
CREATE DATABASE db1;
CREATE PROCEDURE db1.proc1(p1 INT) BEGIN SET @x = 0; REPEAT SET @x = @x + 1; UNTIL @x > p1 END REPEAT; END ;;
CREATE PROCEDURE db1.proc2(p1 INT) BEGIN SET @x = 0; REPEAT SET @x = @x + 1; UNTIL @x > p1 END REPEAT; END ;;
DROP PROCEDURE db1.proc1;
DROP PROCEDURE db1.proc2;
DROP DATABASE db1;
GRANT ALL ON * TO mysqltest_1;
CREATE USER mysqltest_1;
GRANT ALL ON *.* TO mysqltest_1;
SHOW GRANTS FOR mysqltest_1;
DROP USER mysqltest_1;
USE test;
CREATE USER mysqltest_1;
GRANT ALL ON * TO mysqltest_1;
SHOW GRANTS FOR mysqltest_1;
DROP USER mysqltest_1;
CREATE USER mysqltest_1;
GRANT ALL ON *.* TO mysqltest_1;
SHOW GRANTS FOR mysqltest_1;
DROP USER mysqltest_1;
CREATE DATABASE db1;
CREATE DATABASE db2;
CREATE USER 'testbug'@localhost;
GRANT SELECT ON db1.* to 'testbug'@localhost;
USE db2;
CREATE TABLE t1 (a INT);
USE test;
SELECT * FROM `../db2/tb2`;
SELECT * FROM `../db2`.tb2;
SELECT * FROM `#mysql50#/../db2/tb2`;
DROP USER 'testbug'@localhost;
DROP TABLE db2.t1;
DROP DATABASE db1;
DROP DATABASE db2;
flush privileges;
DELETE FROM mysql.db WHERE User LIKE 'mysqltest_%';
DELETE FROM mysql.tables_priv WHERE User LIKE 'mysqltest_%';
DELETE FROM mysql.columns_priv WHERE User LIKE 'mysqltest_%';
FLUSH PRIVILEGES;
CREATE DATABASE mysqltest_db1;
CREATE TABLE mysqltest_db1.t1(a INT);
CREATE USER mysqltest_u1@localhost;
GRANT EVENT                   ON mysqltest_db1.* TO mysqltest_u1@localhost;
GRANT CREATE TEMPORARY TABLES ON mysqltest_db1.* TO mysqltest_u1@localhost;
GRANT LOCK TABLES             ON mysqltest_db1.* TO mysqltest_u1@localhost;
GRANT ALTER ROUTINE           ON mysqltest_db1.* TO mysqltest_u1@localhost;
GRANT CREATE ROUTINE          ON mysqltest_db1.* TO mysqltest_u1@localhost;
GRANT EXECUTE                 ON mysqltest_db1.* TO mysqltest_u1@localhost;
GRANT GRANT OPTION            ON mysqltest_db1.* TO mysqltest_u1@localhost;
GRANT GRANT OPTION            ON mysqltest_db1.t1 TO mysqltest_u1@localhost;
GRANT FILE                    ON *.* TO mysqltest_u1@localhost;
GRANT CREATE USER             ON *.* TO mysqltest_u1@localhost;
GRANT PROCESS                 ON *.* TO mysqltest_u1@localhost;
GRANT RELOAD                  ON *.* TO mysqltest_u1@localhost;
GRANT REPLICATION CLIENT      ON *.* TO mysqltest_u1@localhost;
GRANT REPLICATION SLAVE       ON *.* TO mysqltest_u1@localhost;
GRANT SHOW DATABASES          ON *.* TO mysqltest_u1@localhost;
GRANT SHUTDOWN                ON *.* TO mysqltest_u1@localhost;
GRANT USAGE                   ON *.* TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT SELECT ON mysqltest_db1.* TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT INSERT ON mysqltest_db1.* TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT UPDATE ON mysqltest_db1.* TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT DELETE ON mysqltest_db1.* TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT CREATE ON mysqltest_db1.* TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT DROP ON mysqltest_db1.* TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT ALTER ON mysqltest_db1.* TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT INDEX ON mysqltest_db1.* TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT REFERENCES ON mysqltest_db1.* TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT CREATE VIEW ON mysqltest_db1.* TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT SHOW VIEW ON mysqltest_db1.* TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT SELECT ON mysqltest_db1.t1 TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT INSERT ON mysqltest_db1.t1 TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT UPDATE ON mysqltest_db1.t1 TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT DELETE ON mysqltest_db1.t1 TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT CREATE ON mysqltest_db1.t1 TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT DROP ON mysqltest_db1.t1 TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT ALTER ON mysqltest_db1.t1 TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT INDEX ON mysqltest_db1.t1 TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT REFERENCES ON mysqltest_db1.t1 TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT CREATE VIEW ON mysqltest_db1.t1 TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
GRANT SHOW VIEW ON mysqltest_db1.t1 TO mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
SHOW CREATE TABLE t1;
REVOKE ALL PRIVILEGES, GRANT OPTION FROM mysqltest_u1@localhost;
SHOW GRANTS FOR mysqltest_u1@localhost;
DROP DATABASE mysqltest_db1;
DROP USER mysqltest_u1@localhost;
create database mysqltest_db1;
grant execute on function mysqltest_db1.f1 to mysqltest_u1;
grant execute on procedure mysqltest_db1.p1 to mysqltest_u1;
grant select on mysqltest_db1.t1 to mysqltest_u1;
show grants for mysqltest_u1;
drop database mysqltest_db1;
CREATE DATABASE secret;
CREATE USER 'untrusted'@localhost;
GRANT USAGE ON *.* TO 'untrusted'@localhost;
SHOW GRANTS;
SHOW DATABASES;
CREATE PROCEDURE no_such_db.foo() BEGIN END;
CREATE PROCEDURE secret.peek_at_secret() BEGIN END;
DROP USER 'untrusted'@localhost;
DROP DATABASE secret;
CREATE USER foo@'127.0.0.1';
GRANT ALL ON *.* TO foo@'127.0.0.1';
RENAME USER foo@'127.0.0.1' to foo@'127.0.0.0/255.0.0.0';
RENAME USER foo@'127.0.0.0/255.0.0.0' to foo@'127.0.0.1';
DROP USER foo@'127.0.0.1';
SET @saved_value = @@global.default_password_lifetime;
SET GLOBAL default_password_lifetime = 2;
SHOW VARIABLES LIKE 'default_password_lifetime';
CREATE USER 'wl7131' IDENTIFIED BY 'wl7131';
FLUSH PRIVILEGES;
SELECT 1;
ALTER USER wl7131 IDENTIFIED BY 'new_wl7131';
SELECT 1;
SELECT 1;
DROP USER 'wl7131';
CREATE USER 'wl7131' IDENTIFIED BY 'wl7131';
ALTER USER 'wl7131' PASSWORD EXPIRE NEVER;
FLUSH PRIVILEGES;
ALTER USER 'wl7131' PASSWORD EXPIRE DEFAULT;
SET GLOBAL default_password_lifetime = 0;
ALTER USER 'wl7131' PASSWORD EXPIRE INTERVAL 4 DAY;
SET GLOBAL default_password_lifetime = @saved_value;
ALTER USER 'wl7131' PASSWORD EXPIRE INTERVAL 6 DAY;
DROP USER 'wl7131';
CREATE USER 'wl7131';
SELECT '2022-01-02 23:18:03' IS NOT NULL;
ALTER USER 'wl7131' REQUIRE SSL;
SELECT TIMESTAMPDIFF(SECOND,'2022-01-02 23:18:03','2022-01-02 23:18:03') <> 0;
ALTER USER 'wl7131' PASSWORD EXPIRE INTERVAL -2 DAY;
ALTER USER 'wl7131' PASSWORD EXPIRE INTERVAL 0 DAY;
ALTER USER 'wl7131' PASSWORD EXPIRE INTERVAL 65536 DAY;
ALTER USER 'wl7131' IDENTIFIED BY '';
DROP USER 'wl7131';
CREATE USER 'wl7131'@'localhost' IDENTIFIED BY 'wl7131';
DROP USER 'wl7131'@'localhost';
set GLOBAL sql_mode= @orig_sql_mode_global;
set SESSION sql_mode= @orig_sql_mode_session;
CREATE TABLE t1 ( int_field INTEGER UNSIGNED NOT NULL, char_field CHAR(10), INDEX(`int_field`) );
CREATE PROCEDURE p1() SELECT b FROM t1;
set names utf8;
CREATE USER очень_длинный_юз@localhost;
CREATE USER очень_очень_длинный_юзер@localhost;
CREATE USER очень_очень_очень_длинный_юзер__@localhost;
CREATE USER очень_очень_очень_очень_длинный_юзер@localhost;
GRANT CREATE ON mysqltest.* TO очень_длинный_юз@localhost;
GRANT CREATE ON mysqltest.* TO очень_очень_длинный_юзер@localhost;
GRANT CREATE ON mysqltest.* TO очень_очень_очень_длинный_юзер__@localhost;
GRANT CREATE ON mysqltest.* TO очень_очень_очень_очень_длинный_юзер@localhost;
REVOKE CREATE ON mysqltest.* FROM очень_длинный_юз@localhost;
REVOKE CREATE ON mysqltest.* FROM очень_очень_длинный_юзер@localhost;
REVOKE CREATE ON mysqltest.* FROM очень_очень_очень_длинный_юзер__@localhost;
REVOKE CREATE ON mysqltest.* FROM очень_очень_очень_очень_длинный_юзер@localhost;
GRANT CREATE ON t1 TO очень_длинный_юз@localhost;
GRANT CREATE ON t1 TO очень_очень_длинный_юзер@localhost;
GRANT CREATE ON t1 TO очень_очень_очень_длинный_юзер__@localhost;
GRANT CREATE ON t1 TO очень_очень_очень_очень_длинный_юзер@localhost;
REVOKE CREATE ON t1 FROM очень_длинный_юз@localhost;
REVOKE CREATE ON t1 FROM очень_очень_длинный_юзер@localhost;
REVOKE CREATE ON t1 FROM очень_очень_очень_длинный_юзер__@localhost;
REVOKE CREATE ON t1 FROM очень_очень_очень_очень_длинный_юзер@localhost;
GRANT SELECT ON t1 TO очень_длинный_юз@localhost;
GRANT SELECT ON t1 TO очень_очень_длинный_юзер@localhost;
GRANT SELECT ON t1 TO очень_очень_очень_длинный_юзер__@localhost;
GRANT SELECT ON t1 TO очень_очень_очень_очень_длинный_юзер@localhost;
REVOKE SELECT ON t1 FROM очень_длинный_юз@localhost;
REVOKE SELECT ON t1 FROM очень_очень_длинный_юзер@localhost;
REVOKE SELECT ON t1 FROM очень_очень_очень_длинный_юзер__@localhost;
REVOKE SELECT ON t1 FROM очень_очень_очень_очень_длинный_юзер@localhost;
GRANT EXECUTE ON PROCEDURE p1 TO очень_длинный_юз@localhost;
GRANT EXECUTE ON PROCEDURE p1 TO очень_очень_длинный_юзер@localhost;
GRANT EXECUTE ON PROCEDURE p1 TO очень_очень_очень_длинный_юзер__@localhost;
GRANT EXECUTE ON PROCEDURE p1 TO очень_очень_очень_очень_длинный_юзер@localhost;
REVOKE EXECUTE ON PROCEDURE p1 FROM очень_длинный_юз@localhost;
REVOKE EXECUTE ON PROCEDURE p1 FROM очень_очень_длинный_юзер@localhost;
REVOKE EXECUTE ON PROCEDURE p1 FROM очень_очень_очень_длинный_юзер__@localhost;
REVOKE EXECUTE ON PROCEDURE p1 FROM очень_очень_очень_очень_длинный_юзер@localhost;
CREATE DATABASE db_1;
CREATE TABLE db_1.test_table (name varchar(15) not null, surname varchar(20) not null,  email varchar(50) null, street varchar(50) null, city varchar(50) null,  is_active int default 1 );
INSERT INTO db_1.test_table values('rob', 'g', 'robg@oracle.com', 'couldbeworse_street', 'couldbeworse_city', 1);
INSERT INTO db_1.test_table values('rob', 'g', 'robg@oracle.com', 'couldbeworse_street', 'couldbeworse_city', 1);
INSERT INTO db_1.test_table values('kam', 'g', 'kamg@oracle.com', 'couldbeworse_street', 'couldbeworse_city', 1);
SELECT * FROM db_1.test_table;
SELECT * FROM db_1.test_table;
UPDATE db_1.test_table SET street='couldbemuchworse_street' WHERE name='rob';
UPDATE db_1.test_table SET street='couldbemuchworse_street' WHERE name='rob';
DELETE FROM db_1.test_table WHERE name='rob';
DELETE FROM db_1.test_table WHERE name='rob';
DROP TABLE db_1.test_table;
DROP TABLE db_1.test_table;
DROP DATABASE db_1;
DROP USER очень_длинный_юз@localhost;
DROP USER очень_очень_длинный_юзер@localhost;
DROP USER очень_очень_очень_длинный_юзер__@localhost;
DROP USER очень_очень_очень_очень_длинный_юзер@localhost;
set names default;
DROP TABLE t1;
DROP PROCEDURE p1;
CREATE USER proxy_native_0123456789@localhost IDENTIFIED WITH mysql_native_password;
SELECT USER, PROXIED_USER, GRANTOR FROM mysql.proxies_priv WHERE Proxied_host='localhost';
DROP USER proxy_native_0123456789@localhost;
CREATE DATABASE db8657;
CREATE TABLE db8657.t1 (i INT);
CREATE USER 'untrusted8657'@'localhost';
CREATE INDEX idx1 ON db8657.t1 (i);
PREPARE stmt FROM 'CREATE TABLE db8657.t2 (i INT)';
SHOW CREATE TABLE db8657.t1;
DROP USER 'untrusted8657'@localhost;
DROP DATABASE db8657;
CREATE DATABASE db8063;
CREATE TABLE db8063.t1(a VARCHAR(20));
CREATE USER 'untrusted8063'@'localhost';
LOAD DATA INFILE '../../std_data/loaddata_utf8.dat' INTO TABLE db8063.t1;
SHOW CREATE TABLE db8063.t1;
DROP USER 'untrusted8063'@localhost;
DROP DATABASE db8063;
CREATE DATABASE mysqltest_1;
CREATE VIEW mysqltest_1.v1 AS SELECT 1;
SELECT view_definition FROM information_schema.views WHERE table_schema='mysqltest_1' AND table_name='v1';
SELECT view_definition FROM information_schema.views WHERE table_schema='mysqltest_1' AND table_name='v1';
DROP DATABASE mysqltest_1;
CREATE DATABASE mysqltest;
CREATE USER mysqltest@localhost;
CREATE TABLE mysqltest.visible(s INTEGER, u INTEGER, d INTEGER);
GRANT ALL PRIVILEGES ON mysqltest.visible TO mysqltest@localhost;
CREATE VIEW mysqltest.v0 AS SELECT s, u, d FROM mysqltest.visible;
GRANT ALL PRIVILEGES ON mysqltest.v0 TO mysqltest@localhost;
CREATE TABLE mysqltest.cols( s1 INTEGER, s2 INTEGER, u1 INTEGER, u2 INTEGER, i1 INTEGER, i2 INTEGER);
GRANT SELECT(s1, s2, u1, u2, i1, i2) ON mysqltest.cols TO mysqltest@localhost;
GRANT INSERT(s1, s2, u1, u2, i1, i2) ON mysqltest.cols TO mysqltest@localhost;
GRANT UPDATE(u1, u2) ON mysqltest.cols TO mysqltest@localhost;
GRANT DELETE ON mysqltest.cols TO mysqltest@localhost;
CREATE TABLE mysqltest.ins(i1 INTEGER, i2 INTEGER, i3 INTEGER);
GRANT SELECT(i1, i2, i3) ON mysqltest.ins TO mysqltest@localhost;
GRANT INSERT(i1, i2, i3) ON mysqltest.ins TO mysqltest@localhost;
GRANT UPDATE(i1, i2, i3) ON mysqltest.ins TO mysqltest@localhost;
CREATE TABLE mysqltest.source(b1 INTEGER, b2 INTEGER);
INSERT INTO mysqltest.source VALUES(1, 1);
GRANT SELECT(b1, b2) ON mysqltest.source TO mysqltest@localhost;
CREATE VIEW mysqltest.v1 AS SELECT s1, s2, u1, u2, i1, i2 FROM mysqltest.cols;
GRANT SELECT(s1, s2, u1, u2, i1, i2) ON mysqltest.v1 TO mysqltest@localhost;
GRANT INSERT(s1, s2, u1, u2, i1, i2) ON mysqltest.v1 TO mysqltest@localhost;
GRANT UPDATE(u1, u2) ON mysqltest.v1 TO mysqltest@localhost;
GRANT DELETE ON mysqltest.v1 TO mysqltest@localhost;
CREATE FUNCTION mysqltest.f1() RETURNS INTEGER DETERMINISTIC RETURN 1;
GRANT EXECUTE ON FUNCTION mysqltest.f1 TO mysqltest@localhost;
CREATE PROCEDURE mysqltest.p1(a INTEGER) SELECT a;
GRANT EXECUTE ON PROCEDURE mysqltest.p1 TO mysqltest@localhost;
CREATE PROCEDURE mysqltest.p2(a INTEGER) SELECT a;
GRANT EXECUTE ON PROCEDURE mysqltest.p2 TO mysqltest@localhost;
PREPARE stmt_i0 FROM 'INSERT INTO mysqltest.visible VALUES(1, 1, 1)';
PREPARE stmt_s0 FROM 'SELECT s FROM mysqltest.visible';
PREPARE stmt_u0 FROM 'UPDATE mysqltest.visible SET u=1';
PREPARE stmt_d0 FROM 'DELETE FROM mysqltest.visible WHERE d=1';
PREPARE stmt_i0v FROM 'INSERT INTO mysqltest.v0 VALUES(1, 1, 1)';
PREPARE stmt_s0v FROM 'SELECT s FROM mysqltest.v0';
PREPARE stmt_u0v FROM 'UPDATE mysqltest.v0 SET u=1';
PREPARE stmt_d0v FROM 'DELETE FROM mysqltest.v0 WHERE d=1';
PREPARE stmt_i1 FROM 'INSERT INTO mysqltest.cols(i1, s1, u1) VALUES(1, 1, 1)';
PREPARE stmt_i2 FROM 'INSERT INTO mysqltest.cols(i2, s2, u2) VALUES(1, 1, 1)';
PREPARE stmt_iv1 FROM 'INSERT INTO mysqltest.cols(i1) VALUES((SELECT b1 FROM mysqltest.source))';
PREPARE stmt_iv2 FROM 'INSERT INTO mysqltest.cols(i1) VALUES((SELECT b2 FROM mysqltest.source))';
PREPARE stmt_is1 FROM 'INSERT INTO mysqltest.cols(i1) SELECT b1 FROM mysqltest.source';
PREPARE stmt_is2 FROM 'INSERT INTO mysqltest.cols(i1) SELECT b2 FROM mysqltest.source';
PREPARE stmt_ii1 FROM 'INSERT INTO mysqltest.ins(i1, i3) VALUES(1, i1)';
PREPARE stmt_ii2 FROM 'INSERT INTO mysqltest.ins(i2, i3) VALUES(1, i2)';
PREPARE stmt_iu1 FROM 'INSERT INTO mysqltest.ins(i1)  VALUES(1) ON DUPLICATE KEY UPDATE i1=i1+VALUES(i1)';
PREPARE stmt_iu2 FROM 'INSERT INTO mysqltest.ins(i2)  VALUES(1) ON DUPLICATE KEY UPDATE i2=i2+VALUES(i2)';
PREPARE stmt_s1 FROM 'SELECT s1 FROM mysqltest.cols';
PREPARE stmt_s2 FROM 'SELECT s2 FROM mysqltest.cols';
PREPARE stmt_sw1 FROM 'SELECT 1 FROM mysqltest.cols WHERE s1=1';
PREPARE stmt_sw2 FROM 'SELECT 1 FROM mysqltest.cols WHERE s2=1';
PREPARE stmt_su1 FROM 'SELECT 1 FROM mysqltest.cols AS a JOIN mysqltest.cols AS b USING (s1)';
PREPARE stmt_su2 FROM 'SELECT 1 FROM mysqltest.cols AS a JOIN mysqltest.cols AS b USING (s2)';
PREPARE stmt_sj1 FROM 'SELECT 1 FROM mysqltest.cols AS a JOIN mysqltest.cols AS b ON a.s1=b.s1';
PREPARE stmt_sj2 FROM 'SELECT 1 FROM mysqltest.cols AS a JOIN mysqltest.cols AS b ON a.s2=b.s2';
PREPARE stmt_sg1 FROM 'SELECT 1 FROM mysqltest.cols GROUP BY s1';
PREPARE stmt_sg2 FROM 'SELECT 1 FROM mysqltest.cols GROUP BY s2';
PREPARE stmt_sh1 FROM 'SELECT 1 FROM mysqltest.cols HAVING SUM(s1)=1';
PREPARE stmt_sh2 FROM 'SELECT 1 FROM mysqltest.cols HAVING SUM(s2)=1';
PREPARE stmt_so1 FROM 'SELECT 1 FROM mysqltest.cols ORDER BY s1';
PREPARE stmt_so2 FROM 'SELECT 1 FROM mysqltest.cols ORDER BY s2';
PREPARE stmt_sr1 FROM 'SELECT SUM(1) OVER (ORDER BY s1) FROM mysqltest.cols';
PREPARE stmt_sr2 FROM 'SELECT SUM(1) OVER (ORDER BY s2) FROM mysqltest.cols';
PREPARE stmt_sp1 FROM 'SELECT SUM(1) OVER (PARTITION BY s1) FROM mysqltest.cols';
PREPARE stmt_sp2 FROM 'SELECT SUM(1) OVER (PARTITION BY s2) FROM mysqltest.cols';
PREPARE stmt_sq1 FROM 'SELECT 1 FROM mysqltest.cols WHERE s1 IN (SELECT s1 FROM mysqltest.cols)';
PREPARE stmt_sq2 FROM 'SELECT 1 FROM mysqltest.cols WHERE s1 IN (SELECT s2 FROM mysqltest.cols)';
PREPARE stmt_u1 FROM 'UPDATE mysqltest.cols SET u1=1';
PREPARE stmt_u2 FROM 'UPDATE mysqltest.cols SET u2=1';
PREPARE stmt_us1 FROM 'UPDATE mysqltest.cols SET u1=s1';
PREPARE stmt_us2 FROM 'UPDATE mysqltest.cols SET u1=s2';
PREPARE stmt_uj1 FROM 'UPDATE mysqltest.cols AS a JOIN mysqltest.cols AS b ON a.s1=b.s1 SET a.u1=1';
PREPARE stmt_uj2 FROM 'UPDATE mysqltest.cols AS a JOIN mysqltest.cols AS b ON a.s2=b.s2 SET a.u1=1';
PREPARE stmt_uw1 FROM 'UPDATE mysqltest.cols SET u1=1 WHERE s1=1';
PREPARE stmt_uw2 FROM 'UPDATE mysqltest.cols SET u1=1 WHERE s2=1';
PREPARE stmt_uo1 FROM 'UPDATE mysqltest.cols SET u1=1 ORDER BY s1';
PREPARE stmt_uo2 FROM 'UPDATE mysqltest.cols SET u1=1 ORDER BY s2';
PREPARE stmt_d1 FROM 'DELETE FROM mysqltest.cols WHERE s1=1';
PREPARE stmt_d2 FROM 'DELETE FROM mysqltest.cols WHERE s2=1';
PREPARE stmt_dj1 FROM 'DELETE a FROM mysqltest.cols AS a JOIN mysqltest.cols AS b ON a.s1=b.s1';
PREPARE stmt_dj2 FROM 'DELETE a FROM mysqltest.cols AS a JOIN mysqltest.cols AS b ON a.s2=b.s2';
PREPARE stmt_do1 FROM 'DELETE FROM mysqltest.cols WHERE s1=1 ORDER BY s1';
PREPARE stmt_do2 FROM 'DELETE FROM mysqltest.cols WHERE s1=1 ORDER BY s2';
PREPARE stmt_set1 FROM 'SET @a = (SELECT COUNT(s1) FROM mysqltest.cols)';
PREPARE stmt_set2 FROM 'SET @b = (SELECT COUNT(s2) FROM mysqltest.cols)';
PREPARE stmt_i1v FROM 'INSERT INTO mysqltest.v1(i1, s1, u1) VALUES(1, 1, 1)';
PREPARE stmt_i2v FROM 'INSERT INTO mysqltest.v1(i2, s2, u2) VALUES(1, 1, 1)';
PREPARE stmt_s1v FROM 'SELECT s1 FROM mysqltest.v1';
PREPARE stmt_s2v FROM 'SELECT s2 FROM mysqltest.v1';
PREPARE stmt_u1v FROM 'UPDATE mysqltest.v1 SET u1=1';
PREPARE stmt_u2v FROM 'UPDATE mysqltest.v1 SET u2=1';
PREPARE stmt_d1v FROM 'DELETE FROM mysqltest.v1 WHERE s1=1';
PREPARE stmt_d2v FROM 'DELETE FROM mysqltest.v1 WHERE s2=1';
PREPARE stmt_f1 FROM 'SELECT mysqltest.f1()';
PREPARE stmt_p1 FROM 'CALL mysqltest.p1(10)';
PREPARE stmt_c1 FROM 'CALL mysqltest.p2((SELECT b1 FROM mysqltest.source))';
PREPARE stmt_c2 FROM 'CALL mysqltest.p2((SELECT b2 FROM mysqltest.source))';
EXECUTE stmt_i0;
EXECUTE stmt_s0;
EXECUTE stmt_u0;
EXECUTE stmt_d0;
EXECUTE stmt_i0v;
EXECUTE stmt_s0v;
EXECUTE stmt_u0v;
EXECUTE stmt_d0v;
EXECUTE stmt_i1;
EXECUTE stmt_i2;
EXECUTE stmt_iv1;
EXECUTE stmt_iv2;
EXECUTE stmt_is1;
EXECUTE stmt_is2;
EXECUTE stmt_ii1;
EXECUTE stmt_ii2;
EXECUTE stmt_iu1;
EXECUTE stmt_iu2;
EXECUTE stmt_s1;
EXECUTE stmt_s2;
EXECUTE stmt_sw1;
EXECUTE stmt_sw2;
EXECUTE stmt_su1;
EXECUTE stmt_su2;
EXECUTE stmt_sj1;
EXECUTE stmt_sj2;
EXECUTE stmt_sg1;
EXECUTE stmt_sg2;
EXECUTE stmt_sh1;
EXECUTE stmt_sh2;
EXECUTE stmt_so1;
EXECUTE stmt_so2;
EXECUTE stmt_sr1;
EXECUTE stmt_sr2;
EXECUTE stmt_sp1;
EXECUTE stmt_sp2;
EXECUTE stmt_sq1;
EXECUTE stmt_sq2;
EXECUTE stmt_u1;
EXECUTE stmt_u2;
EXECUTE stmt_us1;
EXECUTE stmt_us2;
EXECUTE stmt_uj1;
EXECUTE stmt_uj2;
EXECUTE stmt_uw1;
EXECUTE stmt_uw2;
EXECUTE stmt_uo1;
EXECUTE stmt_uo2;
EXECUTE stmt_d1;
EXECUTE stmt_d2;
EXECUTE stmt_dj1;
EXECUTE stmt_dj2;
EXECUTE stmt_do1;
EXECUTE stmt_do2;
EXECUTE stmt_set1;
EXECUTE stmt_set2;
EXECUTE stmt_i1v;
EXECUTE stmt_i2v;
EXECUTE stmt_s1v;
EXECUTE stmt_s2v;
EXECUTE stmt_u1v;
EXECUTE stmt_u2v;
EXECUTE stmt_d1v;
EXECUTE stmt_d2v;
EXECUTE stmt_f1;
EXECUTE stmt_p1;
EXECUTE stmt_c1;
EXECUTE stmt_c2;
REVOKE ALL PRIVILEGES ON mysqltest.v0 FROM mysqltest@localhost;
REVOKE SELECT(s2) ON mysqltest.v1 FROM mysqltest@localhost;
REVOKE INSERT(i2,s2,u2) ON mysqltest.v1 FROM mysqltest@localhost;
REVOKE UPDATE(u2) ON mysqltest.v1 FROM mysqltest@localhost;
EXECUTE stmt_i0v;
EXECUTE stmt_s0v;
EXECUTE stmt_u0v;
EXECUTE stmt_d0v;
EXECUTE stmt_i1v;
EXECUTE stmt_s1v;
EXECUTE stmt_u1v;
EXECUTE stmt_d1v;
EXECUTE stmt_i2v;
EXECUTE stmt_s2v;
EXECUTE stmt_u2v;
EXECUTE stmt_d2v;
REVOKE ALL PRIVILEGES ON mysqltest.visible FROM mysqltest@localhost;
REVOKE SELECT(s2) ON mysqltest.cols FROM mysqltest@localhost;
REVOKE INSERT(i2,s2,u2) ON mysqltest.cols FROM mysqltest@localhost;
REVOKE UPDATE(u2) ON mysqltest.cols FROM mysqltest@localhost;
REVOKE SELECT(i2) ON mysqltest.ins FROM mysqltest@localhost;
REVOKE SELECT(b2) ON mysqltest.source FROM mysqltest@localhost;
REVOKE EXECUTE ON FUNCTION mysqltest.f1 FROM mysqltest@localhost;
REVOKE EXECUTE ON PROCEDURE mysqltest.p1 FROM mysqltest@localhost;
EXECUTE stmt_i0;
EXECUTE stmt_s0;
EXECUTE stmt_u0;
EXECUTE stmt_d0;
EXECUTE stmt_i1;
EXECUTE stmt_iv1;
EXECUTE stmt_is1;
EXECUTE stmt_ii1;
EXECUTE stmt_iu1;
EXECUTE stmt_s1;
EXECUTE stmt_sw1;
EXECUTE stmt_su1;
EXECUTE stmt_sj1;
EXECUTE stmt_sg1;
EXECUTE stmt_sh1;
EXECUTE stmt_so1;
EXECUTE stmt_sp1;
EXECUTE stmt_sr1;
EXECUTE stmt_sq1;
EXECUTE stmt_u1;
EXECUTE stmt_us1;
EXECUTE stmt_uj1;
EXECUTE stmt_uw1;
EXECUTE stmt_uo1;
EXECUTE stmt_d1;
EXECUTE stmt_dj1;
EXECUTE stmt_do1;
EXECUTE stmt_set1;
EXECUTE stmt_c1;
EXECUTE stmt_i2;
EXECUTE stmt_iv2;
EXECUTE stmt_is2;
EXECUTE stmt_ii2;
EXECUTE stmt_iu2;
EXECUTE stmt_s2;
EXECUTE stmt_sw2;
EXECUTE stmt_su2;
EXECUTE stmt_sj2;
EXECUTE stmt_sg2;
EXECUTE stmt_sh2;
EXECUTE stmt_so2;
EXECUTE stmt_sp2;
EXECUTE stmt_sr2;
EXECUTE stmt_sq2;
EXECUTE stmt_u2;
EXECUTE stmt_us2;
EXECUTE stmt_uj2;
EXECUTE stmt_uw2;
EXECUTE stmt_uo2;
EXECUTE stmt_d2;
EXECUTE stmt_dj2;
EXECUTE stmt_do2;
EXECUTE stmt_set2;
EXECUTE stmt_f1;
EXECUTE stmt_p1;
EXECUTE stmt_c2;
DROP TABLE mysqltest.visible, mysqltest.cols, mysqltest.source, mysqltest.ins;
DROP VIEW mysqltest.v0, mysqltest.v1;
DROP FUNCTION mysqltest.f1;
DROP PROCEDURE mysqltest.p1;
DROP PROCEDURE mysqltest.p2;
DROP DATABASE mysqltest;
DROP USER mysqltest@localhost;
