CREATE DATABASE privtest_db;
CREATE TABLE privtest_db.t1 (a INT);
CREATE TABLE privtest_db.t2 (a INT);
INSERT INTO privtest_db.t2 VALUES (1), (2), (3);
CREATE USER 'privtest'@'localhost';
GRANT SELECT ON privtest_db.t2 TO 'privtest'@'localhost';
USE privtest_db;
EXPLAIN INSERT INTO t1 VALUES (10);
INSERT INTO t1 VALUES (10);
EXPLAIN INSERT INTO t1 SELECT * FROM t2;
INSERT INTO t1 SELECT * FROM t2;
GRANT INSERT ON privtest_db.t1 TO 'privtest'@'localhost';
EXPLAIN INSERT INTO t1 VALUES (10);
INSERT INTO t1 VALUES (10);
EXPLAIN INSERT INTO t1 SELECT * FROM t2;
INSERT INTO t1 SELECT * FROM t2;
REVOKE ALL PRIVILEGES ON privtest_db.t1 FROM 'privtest'@'localhost';
EXPLAIN REPLACE INTO t1 VALUES (10);
REPLACE INTO t1 VALUES (10);
EXPLAIN REPLACE INTO t1 SELECT * FROM t2;
REPLACE INTO t1 SELECT * FROM t2;
GRANT INSERT ON privtest_db.t1 TO 'privtest'@'localhost';
EXPLAIN REPLACE INTO t1 VALUES (10);
REPLACE INTO t1 VALUES (10);
EXPLAIN REPLACE INTO t1 SELECT * FROM t2;
REPLACE INTO t1 SELECT * FROM t2;
REVOKE INSERT ON privtest_db.t1 FROM 'privtest'@'localhost';
GRANT DELETE ON privtest_db.t1 TO 'privtest'@'localhost';
EXPLAIN REPLACE INTO t1 VALUES (10);
REPLACE INTO t1 VALUES (10);
EXPLAIN REPLACE INTO t1 SELECT * FROM t2;
REPLACE INTO t1 SELECT * FROM t2;
GRANT INSERT, DELETE ON privtest_db.t1 TO 'privtest'@'localhost';
EXPLAIN REPLACE INTO t1 VALUES (10);
REPLACE INTO t1 VALUES (10);
EXPLAIN REPLACE INTO t1 SELECT * FROM t2;
REPLACE INTO t1 SELECT * FROM t2;
REVOKE ALL PRIVILEGES ON privtest_db.t1 FROM 'privtest'@'localhost';
EXPLAIN UPDATE t1 SET a = a + 1;
UPDATE t1 SET a = a + 1;
EXPLAIN UPDATE t1, t2 SET t1.a = t1.a + 1 WHERE t1.a = t2.a;
UPDATE t1, t2 SET t1.a = t1.a + 1 WHERE t1.a = t2.a;
GRANT UPDATE ON privtest_db.t1 TO 'privtest'@'localhost';
EXPLAIN UPDATE t1 SET a = a + 1;
UPDATE t1 SET a = a + 1;
EXPLAIN UPDATE t1, t2 SET t1.a = t1.a + 1 WHERE t1.a = t2.a;
UPDATE t1, t2 SET t1.a = t1.a + 1 WHERE t1.a = t2.a;
REVOKE UPDATE ON privtest_db.t1 FROM 'privtest'@'localhost';
GRANT SELECT ON privtest_db.t1 TO 'privtest'@'localhost';
EXPLAIN UPDATE t1 SET a = a + 1;
UPDATE t1 SET a = a + 1;
EXPLAIN UPDATE t1, t2 SET t1.a = t1.a + 1 WHERE t1.a = t2.a;
UPDATE t1, t2 SET t1.a = t1.a + 1 WHERE t1.a = t2.a;
GRANT UPDATE, SELECT ON privtest_db.t1 TO 'privtest'@'localhost';
EXPLAIN UPDATE t1 SET a = a + 1;
UPDATE t1 SET a = a + 1;
EXPLAIN UPDATE t1, t2 SET t1.a = t1.a + 1 WHERE t1.a = t2.a;
UPDATE t1, t2 SET t1.a = t1.a + 1 WHERE t1.a = t2.a;
REVOKE ALL PRIVILEGES ON privtest_db.t1 FROM 'privtest'@'localhost';
EXPLAIN DELETE FROM t1 WHERE a = 10;
DELETE FROM t1 WHERE a = 10;
EXPLAIN DELETE FROM t1 USING t1, t2 WHERE t1.a = t2.a;
DELETE FROM t1 USING t1, t2 WHERE t1.a = t2.a;
GRANT DELETE ON privtest_db.t1 TO 'privtest'@'localhost';
EXPLAIN DELETE FROM t1 WHERE a = 10;
DELETE FROM t1 WHERE a = 10;
EXPLAIN DELETE FROM t1 USING t1, t2 WHERE t1.a = t2.a;
DELETE FROM t1 USING t1, t2 WHERE t1.a = t2.a;
REVOKE ALL PRIVILEGES ON privtest_db.t1 FROM 'privtest'@'localhost';
GRANT SELECT ON privtest_db.t1 TO 'privtest'@'localhost';
EXPLAIN DELETE FROM t1 WHERE a = 10;
DELETE FROM t1 WHERE a = 10;
EXPLAIN DELETE FROM t1 USING t1, t2 WHERE t1.a = t2.a;
DELETE FROM t1 USING t1, t2 WHERE t1.a = t2.a;
REVOKE ALL PRIVILEGES ON privtest_db.t1 FROM 'privtest'@'localhost';
GRANT DELETE, SELECT ON privtest_db.t1 TO 'privtest'@'localhost';
EXPLAIN DELETE FROM t1 WHERE a = 10;
DELETE FROM t1 WHERE a = 10;
EXPLAIN DELETE FROM t1 USING t1, t2 WHERE t1.a = t2.a;
DELETE FROM t1 USING t1, t2 WHERE t1.a = t2.a;
REVOKE ALL PRIVILEGES ON privtest_db.t1 FROM 'privtest'@'localhost';
CREATE VIEW privtest_db.v1 (a) AS SELECT a FROM privtest_db.t1;
