garbage ;
garbage ;
garbage ;
set @my_var= 'abc' ;
garbage ;
drop table if exists t1 ;
garbage ;
drop table if exists t1 ;
garbage ;
garbage ;
garbage ;
garbage ;
prepare stmt from "select 3 from t1" ;
create table t1 ( f1 char(10));
garbage ;
prepare stmt from "select 3 from t1" ;
garbage ;
execute stmt;
drop table t1;
garbage ;
execute stmt;
garbage ;
execute __stmt_;
garbage ;
deallocate prepare stmt;
garbage ;
deallocate prepare __stmt_;
garbage ;
garbage ;
garbage;
DROP TABLE table_does_not_exist;
DROP TABLE table_does_not_exist;
DROP TABLE table_does_not_exist;
DROP TABLE table_does_not_exist;
CREATE TABLE t1 (a INT);
CREATE TABLE t1 (a INT);
CREATE TABLE t1 (a INT);
DROP TABLE t1;
create table t1 (a varchar(100)) charset utf8mb4;
insert into t1 values ('`select 42`');
insert into t1 values ('$dollar');
drop table t1;
show tables;
failing_statement;
failing_statement;
SET @utf8_message = CONVERT('Here comes a message' using utf8);
SET @utf8_message = CONVERT('root@localhost' using utf8);
SET @utf8_message = CONVERT('"Here comes a very very long message that     - is longer then 80 characters    and     - consists of several lines"' using utf8);
SET @utf8_message = CONVERT('. Here comes a very very long message that .      - is longer then 80 characters    and .      - consists of several lines' using utf8);
drop table t1;
drop table t1;
drop table t1;
drop table t1;
sleep;
sleep;
;
create table t1 (a int, b int);
insert into t1 values (1,3);
insert into t1 values (2,4);
drop table t1;
create table t2 ( a char(10));
garbage;
