set optimizer_trace_max_mem_size=10000000,@@session.optimizer_trace="enabled=on";
create table t1(a int);
insert into t1 values(1),(2);
create table t2(a int);
prepare s from "select ?+11.1";
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
prepare s from "select ?+11";
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
prepare s from "select ?+?";
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
execute s using @a,@a;
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
set @a=1e0;
flush status;
execute s using @a,@a;
show status like 'com_stmt_reprepare';
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
prepare s from "select ?+?";
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
set @a=11;
flush status;
execute s using @a,@a;
show status like 'com_stmt_reprepare';
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
prepare s from "select ?+?";
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
set @a=11.1;
execute s using @a,@a;
show status like 'com_stmt_reprepare';
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
prepare s from "select ?+?";
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
set @a=11e0;
execute s using @a,@a;
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
prepare s from "select ?+?";
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
set @a='11.1';
execute s using @a,@a;
show status like 'com_stmt_reprepare';
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
set @a=11;
execute s using @a,@a;
show status like 'com_stmt_reprepare';
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
set @a='11.1';
execute s using @a,@a;
show status like 'com_stmt_reprepare';
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
set @a='11.1garbage';
prepare s from "select 1.0+?";
execute s using @a;
show status like 'com_stmt_reprepare';
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
prepare s from "select 1e0+?";
execute s using @a;
show status like 'com_stmt_reprepare';
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
prepare s from "select date(?)";
execute s using @a;
show status like 'com_stmt_reprepare';
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
prepare s from "select 11.1*(?+?)";
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
prepare s from 'select -(?)';
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
set @a='1.1';
execute s using @a;
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
set @a=2.2;
execute s using @a;
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
prepare s from 'select cast(? as time), ?+1';
set @a="14:15:16",@b=3;
execute s using @a,@b;
set @a="14:15:16",@b=3.1;
execute s using @a,@b;
prepare s from 'select ABS(?)';
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
set @a='-5.2';
execute s using @a;
select json_extract(trace,"$.steps[*].statement_parameters") from information_schema.optimizer_trace;
