CREATE TABLE t (a INT, b INT, c INT, d INT, e INT, PRIMARY KEY(a, b, c, d), KEY(b, d)) ENGINE=innodb;
CREATE TEMPORARY TABLE a (a INT);
INSERT INTO a VALUES (10);
INSERT INTO a VALUES (9);
INSERT INTO a VALUES (8);
INSERT INTO a VALUES (7);
INSERT INTO a VALUES (6);
INSERT INTO a VALUES (5);
INSERT INTO a VALUES (4);
INSERT INTO a VALUES (3);
INSERT INTO a VALUES (2);
INSERT INTO a VALUES (1);
CREATE TEMPORARY TABLE b (a INT);
INSERT INTO b VALUES (5);
INSERT INTO b VALUES (4);
INSERT INTO b VALUES (3);
INSERT INTO b VALUES (2);
INSERT INTO b VALUES (1);
CREATE TEMPORARY TABLE c (a INT);
INSERT INTO c VALUES (5);
INSERT INTO c VALUES (4);
INSERT INTO c VALUES (3);
INSERT INTO c VALUES (2);
INSERT INTO c VALUES (1);
CREATE TEMPORARY TABLE d (a INT);
INSERT INTO d VALUES (10);
INSERT INTO d VALUES (9);
INSERT INTO d VALUES (8);
INSERT INTO d VALUES (7);
INSERT INTO d VALUES (6);
INSERT INTO d VALUES (5);
INSERT INTO d VALUES (4);
INSERT INTO d VALUES (3);
INSERT INTO d VALUES (2);
INSERT INTO d VALUES (1);
INSERT INTO t SELECT a.a, b.a, c.a, d.a, d.a FROM a, b, c, d ORDER BY a.a, b.a, c.a, d.a;
DROP TEMPORARY TABLE a, b, c, d;
ANALYZE TABLE t;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, d FROM t WHERE d < 2;
FLUSH STATUS;
SELECT b, d FROM t WHERE d < 2;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, d FROM t WHERE d < 2;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, d FROM t WHERE d < 2;
FLUSH STATUS;
SELECT b, d FROM t WHERE d < 2;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, d FROM t WHERE d < 2;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, d FROM t WHERE d < 2;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, d FROM t WHERE d < 2;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, d FROM t WHERE d < 2;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, d FROM t WHERE d > 4;
FLUSH STATUS;
SELECT b, d FROM t WHERE d > 4;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, d FROM t WHERE d > 4;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, d FROM t WHERE d > 4;
FLUSH STATUS;
SELECT b, d FROM t WHERE d > 4;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, d FROM t WHERE d > 4;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, d FROM t WHERE d > 4;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, d FROM t WHERE d > 4;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, d FROM t WHERE d > 4;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a = 5 AND d <= 3;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a = 5 AND d <= 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a = 5 AND d <= 3;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a = 5 AND d <= 3;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a = 5 AND d <= 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a = 5 AND d <= 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND d <= 3;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND d <= 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND d <= 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a = 5 AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a = 5 AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a = 5 AND d >= 98;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a = 5 AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a = 5 AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a = 5 AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND d >= 98;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 5) AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 5) AND b IN (1, 2) AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 2, 3, 4, 5) AND b IN (1, 2, 3) AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = 5 AND b = 2 AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
FLUSH STATUS;
SELECT a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
FLUSH STATUS;
SELECT a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a+1`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a+1`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a+1, b, c, d FROM t WHERE a = 5 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a+1`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a+1`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND d < 3;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, c, d FROM t WHERE a = 5 AND d < 3;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND d < 3;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, c, d FROM t WHERE a = 5 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND d < 3;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a = b AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a = b AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a = b AND d >= 98;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a = b AND d >= 98;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a = b AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a = b AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = b AND d >= 98;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = b AND d >= 98;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a = b AND d >= 98;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 1 AND d < 3 ORDER BY d, c * -1;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT e FROM t WHERE a = 5 AND d <= 3;
FLUSH STATUS;
SELECT e FROM t WHERE a = 5 AND d <= 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT e FROM t WHERE a = 5 AND d <= 3;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT e FROM t WHERE a = 5 AND d <= 3;
FLUSH STATUS;
SELECT e FROM t WHERE a = 5 AND d <= 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT e FROM t WHERE a = 5 AND d <= 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `e` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `e` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ e FROM t WHERE a = 5 AND d <= 3;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ e FROM t WHERE a = 5 AND d <= 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ e FROM t WHERE a = 5 AND d <= 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `e` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `e` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 10 AND d < 3 ORDER BY d, c, e;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT count(a), count(b), count(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT count(a), count(b), count(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT count(a), count(b), count(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT count(a), count(b), count(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT count(a), count(b), count(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT count(a), count(b), count(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `count(a)`,`count(b)`,`count(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `count(a)`,`count(b)`,`count(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ count(a), count(b), count(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ count(a), count(b), count(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ count(a), count(b), count(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `count(a)`,`count(b)`,`count(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `count(a)`,`count(b)`,`count(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT min(a), max(b), min(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT min(a), max(b), min(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT min(a), max(b), min(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT min(a), max(b), min(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT min(a), max(b), min(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT min(a), max(b), min(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `min(a)`,`max(b)`,`min(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `min(a)`,`max(b)`,`min(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ min(a), max(b), min(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ min(a), max(b), min(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ min(a), max(b), min(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `min(a)`,`max(b)`,`min(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `min(a)`,`max(b)`,`min(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT sum(a), sum(b), sum(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT sum(a), sum(b), sum(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT sum(a), sum(b), sum(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT sum(a), sum(b), sum(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT sum(a), sum(b), sum(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT sum(a), sum(b), sum(c)  FROM t WHERE a = 5 AND c > 10 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `sum(a)`,`sum(b)`,`sum(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `sum(a)`,`sum(b)`,`sum(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ sum(a), avg(b), sum(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ sum(a), avg(b), sum(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ sum(a), avg(b), sum(c) FROM t WHERE a = 5 AND c > 10 AND d < 3;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `sum(a)`,`avg(b)`,`sum(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `sum(a)`,`sum(b)`,`sum(c)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT count(*) FROM t WHERE d < 2;;
FLUSH STATUS;
SELECT count(*) FROM t WHERE d < 2;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT count(*) FROM t WHERE d < 2;;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT count(*) FROM t WHERE d < 2;;
FLUSH STATUS;
SELECT count(*) FROM t WHERE d < 2;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT count(*) FROM t WHERE d < 2;;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `count(*)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `count(*)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ count(*) FROM t WHERE d < 2;;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ count(*) FROM t WHERE d < 2;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ count(*) FROM t WHERE d < 2;;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `count(*)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `count(*)` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
ALTER TABLE t DROP PRIMARY KEY;
ALTER TABLE t DROP KEY b;
ALTER TABLE t ADD PRIMARY KEY(a DESC, b, c DESC, d);
ANALYZE TABLE t;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 3 AND d < 3;;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 3 AND d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 3 AND d < 3;;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c > 3 AND d < 3;;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c > 3 AND d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c > 3 AND d < 3;;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 3 AND d < 3;;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 3 AND d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c > 3 AND d < 3;;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c < 3 AND d < 3;;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c < 3 AND d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c < 3 AND d < 3;;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c < 3 AND d < 3;;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c < 3 AND d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c < 3 AND d < 3;;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c < 3 AND d < 3;;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c < 3 AND d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c < 3 AND d < 3;;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c = 3 AND d < 3;;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c = 3 AND d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c = 3 AND d < 3;;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c = 3 AND d < 3;;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c = 3 AND d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c = 3 AND d < 3;;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c = 3 AND d < 3;;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c = 3 AND d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c = 3 AND d < 3;;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c BETWEEN 3 AND 5 AND d < 3;;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c BETWEEN 3 AND 5 AND d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c BETWEEN 3 AND 5 AND d < 3;;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, c, d FROM t WHERE a = 5 AND c BETWEEN 3 AND 5 AND d < 3;;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE a = 5 AND c BETWEEN 3 AND 5 AND d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, c, d FROM t WHERE a = 5 AND c BETWEEN 3 AND 5 AND d < 3;;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c BETWEEN 3 AND 5 AND d < 3;;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c BETWEEN 3 AND 5 AND d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE a = 5 AND c BETWEEN 3 AND 5 AND d < 3;;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, c, d FROM t WHERE c BETWEEN 3 AND 5 AND d < 3;;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE c BETWEEN 3 AND 5 AND d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, c, d FROM t WHERE c BETWEEN 3 AND 5 AND d < 3;;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, c, d FROM t WHERE c BETWEEN 3 AND 5 AND d < 3;;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE c BETWEEN 3 AND 5 AND d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, c, d FROM t WHERE c BETWEEN 3 AND 5 AND d < 3;;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE c BETWEEN 3 AND 5 AND d < 3;;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE c BETWEEN 3 AND 5 AND d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE c BETWEEN 3 AND 5 AND d < 3;;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT b, c, d FROM t WHERE d < 3;;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT b, c, d FROM t WHERE d < 3;;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT b, c, d FROM t WHERE d < 3;;
FLUSH STATUS;
SELECT b, c, d FROM t WHERE d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT b, c, d FROM t WHERE d < 3;;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE d < 3;;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE d < 3;;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ b, c, d FROM t WHERE d < 3;;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 5;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 5;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 5;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 5;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 5;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 5;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 5;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 5;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 3, 5) AND d >= 5;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 5, 3) AND b IN (1, 2) AND d >= 5;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 5, 3) AND b IN (1, 2) AND d >= 5;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 5, 3) AND b IN (1, 2) AND d >= 5;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t WHERE a IN (1, 5, 3) AND b IN (1, 2) AND d >= 5;
FLUSH STATUS;
SELECT a, b, c, d FROM t WHERE a IN (1, 5, 3) AND b IN (1, 2) AND d >= 5;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t WHERE a IN (1, 5, 3) AND b IN (1, 2) AND d >= 5;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 5, 3) AND b in (1, 2) AND d >= 5;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 5, 3) AND b in (1, 2) AND d >= 5;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t) */ a, b, c, d FROM t WHERE a IN (1, 5, 3) AND b in (1, 2) AND d >= 5;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = default;
DROP TABLE t;
CREATE TABLE t1 (a INT, b INT, c INT, d INT, e INT);
INSERT INTO t1 VALUES (NULL, 1, 1, 3, 4), (NULL, 2, 1, 4, 5), (1, 2, 1, 3, 4), (2, 2, 1, 4, 5), (5, 2, 3, 3, 4), (2, 2, 1, 4, 11), (8, 2, 1, 3, 4), (7, 2, 1, 4, 9);
INSERT INTO t1 SELECT * FROM t1;
INSERT INTO t1 SELECT * FROM t1;
INSERT INTO t1 SELECT * FROM t1;
ALTER TABLE t1 ADD KEY k1(a DESC, b, c DESC, d, e DESC);
ANALYZE TABLE t1;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
FLUSH STATUS;
SELECT a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
FLUSH STATUS;
SELECT a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t1) */ a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t1) */ a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t1) */ a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
ALTER TABLE t1 DROP KEY k1;
ALTER TABLE t1 ADD KEY k1(a, b DESC, c, d DESC, e);
ANALYZE TABLE t1;
set optimizer_switch = 'skip_scan=on';
EXPLAIN SELECT a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
FLUSH STATUS;
SELECT a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE skip_scan SELECT a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
set optimizer_switch = 'skip_scan=off';
EXPLAIN SELECT a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
FLUSH STATUS;
SELECT a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE no_skip_scan SELECT a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
EXPLAIN SELECT /*+ SKIP_SCAN(t1) */ a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
FLUSH STATUS;
SELECT /*+ SKIP_SCAN(t1) */ a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
SHOW STATUS LIKE 'handler_read%';
CREATE TABLE hint_skip_scan SELECT /*+ SKIP_SCAN(t1) */ a, b, c, d FROM t1 WHERE (a IN (1, 5) or a IS NULL) AND b in (1, 2) AND d BETWEEN 2 AND 5;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.hint_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-hint_skip_scan';;
set @@sort_buffer_size = @save_sbs;
set @save_sbs = @@sort_buffer_size;
set @@sort_buffer_size = 1048576;
SELECT * FROM test.no_skip_scan ORDER BY `a`,`b`,`c`,`d` INTO OUTFILE '/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/mysqld.1/data//diff_table--test-no_skip_scan';;
set @@sort_buffer_size = @save_sbs;
DROP TABLE skip_scan, no_skip_scan, hint_skip_scan;
set optimizer_switch = default;
DROP TABLE t1;
CREATE TABLE t1 (f1 INT(11), f2 VARCHAR(1), KEY k1 (f2, f1));
INSERT INTO t1 VALUES (-682212662,'c'), (-1974921822,'C'), (1260604936,'9');
CREATE TABLE t2 (f1 INT(11));
INSERT INTO t2 VALUES (824388284), (1186821161);
CREATE VIEW v1 AS select f1, f2 from t1;
DELETE FROM t2 WHERE (f1, f1) IN (SELECT f1,f2 FROM v1 WHERE f1 >= 2);
DROP VIEW v1;
DROP TABLE t1, t2;
CREATE TABLE t1(f1 INT, f2 VARCHAR(64) NOT NULL, PRIMARY KEY (f1)) PARTITION BY RANGE(f1) ( PARTITION p1 VALUES LESS THAN (3), PARTITION p2 VALUES LESS THAN (maxvalue) );
INSERT INTO t1 VALUES (1, 'abcde'), (2, 'abcde'), (3, 'abcde');
CREATE INDEX idx1 ON t1(f2);
ANALYZE TABLE t1;
EXPLAIN SELECT /*+ SKIP_SCAN(t1 idx1) */ count(*) FROM t1 WHERE f1 <= 3;
SELECT /*+ SKIP_SCAN(t1 idx1) */ count(*) FROM t1 WHERE f1 <= 3;
DROP TABLE t1;
