create table mysql.db_copy as select * from mysql.db;
delete from mysql.db where host='%';
flush privileges;
set @orig_sql_mode_session= @@SESSION.sql_mode;
set @orig_sql_mode_global= @@GLOBAL.sql_mode;
set @orig_partial_revokes = @@global.partial_revokes;
SET GLOBAL partial_revokes= OFF;
use test;
create user user1@localhost;
create user ''@'%';
create user user1;
delete from mysql.db;
insert into mysql.db select * from mysql.db_copy;
flush privileges;
drop table if exists t1;
drop database if exists db1_secret;
create database db1_secret;
create procedure db1_secret.dummy() begin end;
drop procedure db1_secret.dummy;
use db1_secret;
create table t1 ( u varchar(64), i int );
insert into t1 values('test', 0);
create procedure stamp(i int) insert into db1_secret.t1 values (user(), i);
show procedure status like 'stamp';
create function db() returns varchar(64) begin declare v varchar(64); select u into v from t1 limit 1; return v; end;
show function status like 'db';
call stamp(1);
select * from t1;
select db();
grant execute on procedure db1_secret.stamp to user1@'%';
grant execute on function db1_secret.db to user1@'%';
grant execute on procedure db1_secret.stamp to ''@'%';
grant execute on function db1_secret.db to ''@'%';
call db1_secret.stamp(2);
select db1_secret.db();
select * from db1_secret.t1;
create procedure db1_secret.dummy() begin end;
drop procedure db1_secret.dummy;
drop procedure db1_secret.stamp;
drop function db1_secret.db;
call db1_secret.stamp(3);
select db1_secret.db();
select * from db1_secret.t1;
create procedure db1_secret.dummy() begin end;
drop procedure db1_secret.dummy;
drop procedure db1_secret.stamp;
drop function db1_secret.db;
select * from t1;
alter procedure stamp sql security invoker;
show procedure status like 'stamp';
alter function db sql security invoker;
show function status like 'db';
call stamp(4);
select * from t1;
select db();
call db1_secret.stamp(5);
select db1_secret.db();
call db1_secret.stamp(6);
select db1_secret.db();
drop database if exists db2;
create database db2;
use db2;
create table t2 (s1 int);
insert into t2 values (0);
create user user2@localhost;
grant usage on db2.* to user1@localhost;
grant select on db2.* to user1@localhost;
grant usage on db2.* to user2@localhost;
grant select,insert,update,delete,create routine on db2.* to user2@localhost;
grant create routine on db2.* to user1@localhost;
flush privileges;
use db2;
create procedure p () insert into t2 values (1);
call p();
use db2;
call p();
select * from t2;
create procedure q () insert into t2 values (2);
call q();
select * from t2;
grant usage on procedure db2.q to user2@localhost with grant option;
grant execute on procedure db2.q to user1@localhost;
use db2;
call q();
select * from t2;
alter procedure p modifies sql data;
drop procedure p;
alter procedure q modifies sql data;
drop procedure q;
use db2;
alter procedure q modifies sql data;
drop procedure q;
use test;
select routine_type, routine_schema, routine_name from information_schema.routines where routine_schema like 'db%' order by routine_type, routine_name;
drop database db1_secret;
drop database db2;
select routine_type, routine_schema, routine_name from information_schema.routines where routine_schema like 'db%';
delete from mysql.user where user='user1' or user='user2';
delete from mysql.user where user='' and host='%';
delete from mysql.procs_priv where user='user1' or user='user2';
delete from mysql.procs_priv where user='' and host='%';
delete from mysql.db where user='user1' or user='user2';
flush privileges;
create user usera@localhost;
create user userb@localhost;
create user userc@localhost;
create database sptest;
create table t1 ( u varchar(64), i int );
create procedure sptest.p1(i int) insert into test.t1 values (user(), i);
grant insert on t1 to usera@localhost;
grant execute on procedure sptest.p1 to usera@localhost;
show grants for usera@localhost;
grant execute on procedure sptest.p1 to userc@localhost with grant option;
show grants for userc@localhost;
call sptest.p1(1);
grant execute on procedure sptest.p1 to userb@localhost;
drop procedure sptest.p1;
call sptest.p1(2);
grant execute on procedure sptest.p1 to userb@localhost;
drop procedure sptest.p1;
call sptest.p1(3);
grant execute on procedure sptest.p1 to userb@localhost;
