drop table if exists t1,t2;
set names utf8mb4;
CREATE TABLE t1 (a char(10) character set utf8mb4 not null);
INSERT INTO t1 VALUES ('a'),('a\0'),('a\t'),('a ');
DROP TABLE t1;
create table t1 select date_format("2004-01-19 10:10:10", "%Y-%m-%d");
show create table t1;
drop table t1;
set names utf8mb4;
set LC_TIME_NAMES='fr_FR';
create table t1 (s1 char(20) character set latin1);
insert into t1 values (date_format('2004-02-02','%M'));
drop table t1;
create table t1 (s1 char(20) character set koi8r);
set LC_TIME_NAMES='ru_RU';
insert into t1 values (date_format('2004-02-02','%M'));
insert into t1 values (date_format('2004-02-02','%b'));
insert into t1 values (date_format('2004-02-02','%W'));
insert into t1 values (date_format('2004-02-02','%a'));
drop table t1;
set LC_TIME_NAMES='en_US';
SET sql_mode = 'NO_ENGINE_SUBSTITUTION';
set names koi8r;
create table t1 (s1 char(1) character set utf8mb4);
insert into t1 values (_koi8r'��');
drop table t1;
create table t1 (s1 tinytext character set utf8mb4);
insert into t1 select repeat('a',300);
insert into t1 select repeat('�',300);
insert into t1 select repeat('a�',300);
insert into t1 select repeat('�a',300);
insert into t1 select repeat('��',300);
drop table t1;
create table t1 (s1 text character set utf8mb4);
insert into t1 select repeat('a',66000);
insert into t1 select repeat('�',66000);
insert into t1 select repeat('a�',66000);
insert into t1 select repeat('�a',66000);
insert into t1 select repeat('��',66000);
drop table t1;
SET sql_mode = default;
create table t1 (s1 char(10) character set utf8mb4);
insert ignore into t1 values (0x41FF);
drop table t1;
create table t1 (s1 varchar(10) character set utf8mb4);
insert ignore into t1 values (0x41FF);
drop table t1;
create table t1 (s1 text character set utf8mb4);
insert ignore into t1 values (0x41FF);
drop table t1;
create table t1 (a text character set utf8mb4, primary key(a(371)));
CREATE TABLE t1 ( a varchar(10) ) CHARACTER SET utf8mb4;
INSERT INTO t1 VALUES ( 'test' );
DROP TABLE t1;
create table t1 (a char(255) character set utf8mb4);
insert into t1 values('b'),('b');
drop table t1;
set collation_connection=utf8mb4_general_ci;
drop table if exists t1;
create table t1 as select repeat(' ', 64) as s1, repeat(' ',64) as s2 union select null, null;
show create table t1;
delete from t1;
