SET @org_partial_revokes= @@partial_revokes;
SET @org_sql_mode= @@sql_mode;
CREATE USER u1;
SHOW CREATE USER u1;
ALTER USER u1 COMMENT 'free form text';
ALTER USER u1 COMMENT 'changed the free form text';
ALTER USER u1 ATTRIBUTE '{"uid" : "34234"}';
ALTER USER u1 ATTRIBUTE '{"speed" : "9000"}';
ALTER USER u1 ATTRIBUTE '{"speed" : null }';
CREATE USER foo@localhost IDENTIFIED BY 'foo' FAILED_LOGIN_ATTEMPTS 4 PASSWORD_LOCK_TIME 6;
ALTER USER foo@localhost COMMENT 'password lock time';
ALTER USER foo@localhost ATTRIBUTE '{"flag":"red"}';
SHOW CREATE USER foo@localhost;
ALTER USER foo@localhost ATTRIBUTE '{"flag":null}';
ALTER USER foo@localhost COMMENT 'xxx';
ALTER USER foo@localhost ATTRIBUTE 'not a valid object';
ALTER USER foo@localhost ATTRIBUTE NULL;
ALTER USER foo@localhost ATTRIBUTE;
ALTER USER foo@localhost COMMENT;
ALTER USER u4@sdasd ATTRIBUTE '{}';
ALTER USER fff@asdasd COMMENT '';
ALTER USER USER() COMMENT 'test';
CREATE USER foo2@localhost IDENTIFIED BY 'foo' COMMENT 'xxx';
SHOW CREATE USER foo2@localhost;
CREATE USER foo3 PASSWORD EXPIRE DEFAULT COMMENT 'abc';
CREATE USER foo4 ACCOUNT LOCK ATTRIBUTE '{"stuff":"ffuts"}';
ALTER USER foo4 ACCOUNT UNLOCK ATTRIBUTE '{"stuff":"unlocked"}';
SHOW CREATE USER foo4;
SELECT * FROM INFORMATION_SCHEMA.USER_ATTRIBUTES WHERE USER like 'foo%';
SELECT `attribute`->>"$.comment" FROM INFORMATION_SCHEMA.USER_ATTRIBUTES WHERE USER like 'foo%';
SET GLOBAL partial_revokes=ON;
GRANT SELECT ON *.* TO foo@localhost;
REVOKE SELECT ON mysql.* FROM foo@localhost;
ALTER USER foo@localhost ATTRIBUTE '{"key":"value"}';
ALTER USER foo@localhost COMMENT 'Added key/value pair';
GRANT SELECT ON mysql.* TO foo@localhost;
CREATE USER redqueen@localhost IDENTIFIED BY 'shoo';
ALTER USER redqueen@localhost IDENTIFIED BY 'madness' RETAIN CURRENT PASSWORD;
ALTER USER redqueen@localhost DISCARD OLD PASSWORD COMMENT 'Dropped old password';
SET GLOBAL partial_revokes=OFF;
DROP USER foo@localhost, u1, foo3, foo2@localhost, foo4, redqueen@localhost;
CREATE USER u1 COMMENT 'Hello "Smith"';
DROP USER u1;
CREATE USER `u1`@`%` IDENTIFIED WITH 'caching_sha2_password' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT ATTRIBUTE '{"comment": "Hello \\"Smith\\""}';
DROP USER u1;
CREATE USER u1 COMMENT 'Hello "Smith"';
SET @@sql_mode='NO_BACKSLASH_ESCAPES';
DROP USER u1;
CREATE USER `u1`@`%` IDENTIFIED WITH 'caching_sha2_password' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT ATTRIBUTE '{"comment": "Hello \"Smith\""}';
DROP USER u1;
SET @@sql_mode = @org_sql_mode;
CREATE USER u1@localhost IDENTIFIED BY 'foo' COMMENT 'Not permitted to change this';
GRANT SELECT ON *.* to u1@localhost;
ALTER USER u1@localhost COMMENT 'I comment what I want';
ALTER USER u1@localhost ATTRIBUTE '{"key": "value"}';
DROP USER u1@localhost;
CREATE USER u1@localhost IDENTIFIED BY 'foo',u2@localhost IDENTIFIED BY 'foo' COMMENT "Works with partial restrictions";
GRANT CREATE USER,SELECT ON *.* TO u2@localhost;
GRANT INSERT, CREATE ON *.* TO u1@localhost;
SET GLOBAL partial_revokes=ON;
REVOKE INSERT ON mysql.* FROM u1@localhost;
ALTER USER CURRENT_USER() COMMENT 'test';
ALTER USER CURRENT_USER() ATTRIBUTE '{ "comment" : null }';
REVOKE CREATE ON mysql.* FROM u1@localhost;
SHOW GRANTS FOR u1@localhost;
ALTER USER u1@localhost ATTRIBUTE '{"Restrictions": [{"Database":"mysql","Privileges": [ "CREATE" ]}]}';
SHOW GRANTS FOR u1@localhost;
DROP USER u1@localhost, u2@localhost;
CREATE USER u1@localhost ATTRIBUTE "this is a string";
SET GLOBAL partial_revokes=@org_partial_revokes;
