CALL mtr.add_suppression('Following users were specified in CREATE USER IF NOT EXISTS but they already exist');
CALL mtr.add_suppression('Following users were specified in ALTER USER IF EXISTS but they do not exist');
FLUSH PRIVILEGES;
CREATE USER wl8540@host1;
CREATE USER wl8540@host1;
CREATE USER IF NOT EXISTS wl8540@host1;
SHOW WARNINGS;
CREATE USER IF NOT EXISTS wl8540@host1, wl8540@host2;
SHOW WARNINGS;
CREATE USER IF NOT EXISTS wl8540@host1, wl8540@host2;
SHOW WARNINGS;
ALTER USER wl8540@host3 ACCOUNT LOCK;
ALTER USER IF EXISTS wl8540@host3, wl8540@host4, wl8540@host1 ACCOUNT LOCK;
SHOW WARNINGS;
ALTER USER IF EXISTS wl8540@host2 ACCOUNT LOCK;
SHOW WARNINGS;
DROP USER wl8540@host3;
DROP USER IF EXISTS wl8540@host3;
SHOW WARNINGS;
DROP USER IF EXISTS wl8540@host3,wl8540@host2,wl8540@host4;
SHOW WARNINGS;
DROP USER IF EXISTS wl8540@nohost1, wl8540@nohost2;
SHOW WARNINGS;
ALTER USER IF EXISTS wl8540@nohost1, wl8540@nohost2 ACCOUNT LOCK;
SHOW WARNINGS;
CREATE USER IF NOT EXISTS wl8540@nohost1, wl8540@nohost2;
ALTER USER IF EXISTS wl8540@nohost1, wl8540@nohost2 ACCOUNT LOCK;
CREATE USER IF NOT EXISTS wl8540@nohost1, wl8540@nohost2;
SHOW WARNINGS;
DROP USER IF EXISTS wl8540@nohost1, wl8540@nohost2;
CREATE USER wl8540@nohost1;
DROP USER IF EXISTS wl8540@nohost1, wl8540@nohost2;
SHOW WARNINGS;
ALTER USER IF EXISTS wl8540@nohost1, wl8540@nohost2 ACCOUNT LOCK;
SHOW WARNINGS;
CREATE USER IF NOT EXISTS wl8540@nohost1, wl8540@nohost2;
SHOW WARNINGS;
FLUSH PRIVILEGES;
CREATE USER user1@localhost IDENTIFIED WITH 'mysql_native_password' BY 'auth_string#%y';
CREATE USER IF NOT EXISTS user2@localhost IDENTIFIED WITH 'mysql_native_password'             AS '*67092806AE91BFB6BE72DE6C7BE2B7CCA8CFA9DF';
CREATE USER IF NOT EXISTS user2@localhost IDENTIFIED WITH 'sha256_password';
ALTER USER IF EXISTS user2@localhost IDENTIFIED WITH 'mysql_native_password'             AS '*67092806AE91BFB6BE72DE6C7BE2B7CCA8CFA9DF';
CREATE USER IF NOT EXISTS user1@localhost IDENTIFIED WITH 'mysql_native_password' BY 'auth_string#%y';
CREATE USER IF NOT EXISTS ne_user1@localhost,user1@localhost IDENTIFIED WITH 'mysql_native_password' BY 'auth_string';
ALTER USER IF EXISTS ne_user2@localhost IDENTIFIED WITH 'mysql_native_password' BY 'auth_string#%y';
ALTER USER IF EXISTS user1@localhost,ne_user3@localhost IDENTIFIED WITH 'mysql_native_password' BY 'auth_string#%y';
DROP USER IF EXISTS user1@localhost,user2@localhost,ne_user1@localhost, ne_user2@localhost,ne_user3@localhost;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
CREATE USER user1@localhost IDENTIFIED WITH 'mysql_native_password';
CREATE USER IF NOT EXISTS user2@localhost IDENTIFIED WITH 'mysql_native_password'             AS '*67092806AE91BFB6BE72DE6C7BE2B7CCA8CFA9DF';
CREATE USER IF NOT EXISTS user1@localhost IDENTIFIED WITH 'mysql_native_password' BY 'auth_string#%y';
CREATE USER IF NOT EXISTS ne_user1@localhost,user1@localhost IDENTIFIED WITH 'mysql_native_password' BY 'auth_string';
ALTER USER IF EXISTS ne_user2@localhost IDENTIFIED WITH 'mysql_native_password' BY 'auth_string#%y';
ALTER USER IF EXISTS user1@localhost,ne_user3@localhost IDENTIFIED WITH 'mysql_native_password' BY 'auth_string#%y';
DROP USER IF EXISTS user1@localhost,user2@localhost,ne_user1@localhost, ne_user2@localhost,ne_user3@localhost;
CREATE USER IF NOT EXISTS b21807286@localhost IDENTIFIED BY 'xyz';
CREATE USER IF NOT EXISTS b21807286@localhost IDENTIFIED BY 'xyz';
DROP USER b21807286@localhost;
ALTER USER IF EXISTS b21807286@localhost IDENTIFIED BY 'xyz';
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
