set @orig_sql_mode= @@sql_mode;
drop table if exists t1;
create table t1 (i int);
delete from mysql.user where user like 'mysqltest\_%';
delete from mysql.db where user like 'mysqltest\_%';
delete from mysql.tables_priv where user like 'mysqltest\_%';
delete from mysql.columns_priv where user like 'mysqltest\_%';
flush privileges;
create user mysqltest_1@localhost with max_queries_per_hour 2;
flush user_resources;
select * from t1;
select * from t1;
select * from t1;
select * from t1;
drop user mysqltest_1@localhost;
create user mysqltest_1@localhost with max_updates_per_hour 2;
flush user_resources;
select * from t1;
select * from t1;
select * from t1;
delete from t1;
delete from t1;
delete from t1;
select * from t1;
delete from t1;
select * from t1;
drop user mysqltest_1@localhost;
create user mysqltest_1@localhost with max_connections_per_hour 2;
flush user_resources;
select * from t1;
select * from t1;
select * from t1;
drop user mysqltest_1@localhost;
flush privileges;
create user mysqltest_1@localhost with max_user_connections 2;
flush user_resources;
select * from t1;
select * from t1;
select * from t1;
alter user mysqltest_1@localhost with max_user_connections 3;
flush user_resources;
select * from t1;
drop user mysqltest_1@localhost;
select @@session.max_user_connections, @@global.max_user_connections;
set session max_user_connections= 2;
set global max_user_connections= 2;
select @@session.max_user_connections, @@global.max_user_connections;
create user mysqltest_1@localhost;
flush user_resources;
select @@session.max_user_connections, @@global.max_user_connections;
select * from t1;
alter user mysqltest_1@localhost with max_user_connections 3;
flush user_resources;
select @@session.max_user_connections, @@global.max_user_connections;
set global max_user_connections= 0;
drop user mysqltest_1@localhost;
drop table t1;
set sql_mode= @orig_sql_mode;
