CREATE USER no_pwd_history@localhost PASSWORD HISTORY 0 PASSWORD REUSE INTERVAL 0 DAY;
SET PASSWORD FOR no_pwd_history@localhost = 'changeme';
ALTER USER no_pwd_history@localhost IDENTIFIED BY 'changemeagain';
ALTER USER no_pwd_history@localhost IDENTIFIED WITH "mysql_native_password"   AS '*C40F578E1A9D8D1146AFD04AFCB0228EED9D45FB';
SET PASSWORD='pwd1'; SET PASSWORD='pwd2';;
SET GLOBAL password_history= 1;
SET PASSWORD FOR no_pwd_history@localhost = 'tracked';
SET PASSWORD FOR no_pwd_history@localhost = 'tracked';
SET GLOBAL password_history= default;
SET GLOBAL password_reuse_interval= 100;
SET PASSWORD FOR no_pwd_history@localhost = 'tracked';
SET PASSWORD FOR no_pwd_history@localhost = 'tracked';
SHOW CREATE USER no_pwd_history@localhost;
SET GLOBAL password_reuse_interval= DEFAULT;
DROP USER no_pwd_history@localhost;
CREATE USER default_def@localhost IDENTIFIED BY 'haha';
SHOW CREATE USER default_def@localhost;
SET GLOBAL password_history=1;
ALTER USER default_def@localhost IDENTIFIED BY 'haha';
ALTER USER default_def@localhost IDENTIFIED BY 'haha';
SET GLOBAL password_history=default;
ALTER USER default_def@localhost IDENTIFIED BY 'haha';
SET GLOBAL password_history=1;
ALTER USER default_def@localhost IDENTIFIED BY 'haha';
DROP USER default_def@localhost;
SET GLOBAL password_history=default;
SET GLOBAL password_history=1;
CREATE USER method_alter@localhost IDENTIFIED BY 'haha';
ALTER USER method_alter@localhost IDENTIFIED WITH 'sha256_password';
DROP USER method_alter@localhost;
SET GLOBAL password_history=default;
CREATE USER to_be_renamed@localhost IDENTIFIED BY 'haha' PASSWORD HISTORY 1;
RENAME USER to_be_renamed@localhost TO now_renamed@localhost;
SET PASSWORD FOR now_renamed@localhost = 'haha';
SET PASSWORD FOR now_renamed@localhost = 'haha';
DROP USER now_renamed@localhost;
CREATE USER no_pwd_history@localhost IDENTIFIED BY 'haha';
CREATE USER no_pwd_history_err@localhost IDENTIFIED BY 'haha'   PASSWORD HISTORY 0 PASSWORD REUSE INTERVAL 0 DAY;
SET PASSWORD FOR no_pwd_history@localhost = 'hehe';
ALTER USER no_pwd_history@localhost IDENTIFIED BY 'hihi';
ALTER USER no_pwd_history@localhost IDENTIFIED WITH 'sha256_password';
DROP USER no_pwd_history@localhost;
DROP USER no_pwd_history@localhost;
CREATE USER dup_history@localhost IDENTIFIED BY 'haha'   PASSWORD HISTORY 1 PASSWORD HISTORY DEFAULT;
DROP USER dup_history@localhost;
CREATE USER dup_interval@localhost IDENTIFIED BY 'haha'   PASSWORD REUSE INTERVAL 10 DAY PASSWORD REUSE INTERVAL DEFAULT;
DROP USER dup_interval@localhost;
CREATE USER empty_pwd@localhost IDENTIFIED BY ''   PASSWORD HISTORY 1;
SET PASSWORD FOR empty_pwd@localhost = '';
DROP USER empty_pwd@localhost;
SET SESSION password_reuse_interval= 0;
SET GLOBAL password_history=0;
SET GLOBAL password_reuse_interval=1;
CREATE USER def_interval@localhost IDENTIFIED BY 'haha';
SET PASSWORD FOR def_interval@localhost = 'haha';
SET PASSWORD FOR def_interval@localhost = 'haha';
SET PASSWORD FOR def_interval@localhost = 'hihi';
SET PASSWORD FOR def_interval@localhost = 'hoho';
SET GLOBAL password_reuse_interval = default;
DROP USER def_interval@localhost;
SET GLOBAL password_history=5;
SET GLOBAL password_reuse_interval=5;
CREATE USER mohit@localhost IDENTIFIED BY 'mohit'   PASSWORD HISTORY 1 PASSWORD REUSE INTERVAL 2 DAY;
SHOW CREATE USER mohit@localhost;
ALTER USER mohit@localhost IDENTIFIED BY 'mohit';
ALTER USER mohit@localhost IDENTIFIED BY 'mohit1';
SHOW CREATE USER mohit@localhost;
DROP USER mohit@localhost;
SET GLOBAL password_reuse_interval= default;
CREATE USER mohit@localhost IDENTIFIED BY 'mohit' PASSWORD HISTORY 1;
SHOW CREATE USER mohit@localhost;
ALTER USER mohit@localhost IDENTIFIED BY 'mohit';
ALTER USER mohit@localhost IDENTIFIED BY 'mohit1';
ALTER USER mohit@localhost IDENTIFIED BY 'mohit';
DROP USER mohit@localhost;
SET GLOBAL password_history= default;
SET GLOBAL password_reuse_interval= default;
CREATE USER mohit@localhost IDENTIFIED WITH sha256_password BY 'mohit' PASSWORD HISTORY 1;
ALTER USER mohit@localhost IDENTIFIED WITH mysql_native_password BY 'mohit';
