drop table if exists t1,t2;
set @a := foo;
set @a := connection_id() + 3;
set @b := 1;
CREATE TABLE t1 ( i int not null, v int not null,index (i));
insert into t1 values (1,1),(1,3),(2,1);
create table t2 (i int not null, unique (i));
insert into t2 select distinct i from t1;
analyze table t1;
explain select * from t1 where i=@vv1;
explain select * from t1 where @vv1:=@vv1+1 and i=@vv1;
explain select @vv1:=i from t1 where i=@vv1;
explain select * from t1 where i=@vv1;
drop table t1,t2;
set @a=0,@b=0;
create table t1 (id int, d double, c char(10));
insert into t1 values (1,2.0, "test");
update t1 SET id=(@c:=@c+1);
update t1 set id=(@c:=@c+1);
set @g=1;
drop table t1;
create table t1 (i int not null);
insert t1 values (1),(2),(2),(3),(3),(3);
set @a=0;
drop table t1;
set @a=_latin2'test';
set @a=_latin2'test' collate latin2_general_ci;
set @var= NULL ;
set @v1=null, @v2=1, @v3=1.1, @v4=now();
set session @honk=99;
set @first_var= NULL;
create table t1 select @first_var;
show create table t1;
drop table t1;
set @first_var= cast(NULL as signed integer);
create table t1 select @first_var;
show create table t1;
drop table t1;
set @first_var= NULL;
create table t1 select @first_var;
show create table t1;
drop table t1;
set @first_var= concat(NULL);
create table t1 select @first_var;
show create table t1;
drop table t1;
set @first_var=1;
set @first_var= cast(NULL as CHAR);
create table t1 select @first_var;
show create table t1;
drop table t1;
set @a=18446744071710965857;
CREATE TABLE `bigfailure` ( `afield` BIGINT UNSIGNED NOT NULL );
INSERT INTO `bigfailure` VALUES (18446744071710965857);
SET @a := (SELECT afield FROM bigfailure);
SET @a := (select afield from (SELECT afield FROM bigfailure) as b);
SET @a := (select * from bigfailure where afield = (SELECT afield FROM bigfailure));
drop table bigfailure;
create table t1(f1 int, f2 int);
insert into t1 values (1,2),(2,3),(3,1);
set @previous_sql_mode_htnt542nh=@@sql_mode;
set sql_mode=(select replace(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
