drop table if exists t1,t2;
SET @default_table_open_cache = @@table_open_cache;
set @my_log_error_verbosity       =@@global.log_error_verbosity;
set @my_connect_timeout           =@@global.connect_timeout;
set @my_delayed_insert_timeout    =@@global.delayed_insert_timeout;
set @my_delayed_queue_size        =@@global.delayed_queue_size;
set @my_flush                     =@@global.flush;
set @my_flush_time                =@@global.flush_time;
set @my_key_buffer_size           =@@global.key_buffer_size;
set @my_max_binlog_cache_size     =@@global.max_binlog_cache_size;
set @my_binlog_cache_size         =@@global.binlog_cache_size;
set @my_max_binlog_size           =@@global.max_binlog_size;
set @my_max_connect_errors        =@@global.max_connect_errors;
set @my_max_connections           =@@global.max_connections;
set @my_max_delayed_threads       =@@global.max_delayed_threads;
set @my_max_heap_table_size       =@@global.max_heap_table_size;
set @my_max_insert_delayed_threads=@@global.max_insert_delayed_threads;
set @my_max_join_size             =@@global.max_join_size;
set @my_myisam_data_pointer_size  =@@global.myisam_data_pointer_size;
set @my_myisam_max_sort_file_size =@@global.myisam_max_sort_file_size;
set @my_net_buffer_length         =@@global.net_buffer_length;
set @my_net_write_timeout         =@@global.net_write_timeout;
set @my_net_read_timeout          =@@global.net_read_timeout;
set @my_server_id                 =@@global.server_id;
set @my_slow_launch_time          =@@global.slow_launch_time;
set @my_storage_engine            =@@global.default_storage_engine;
set @my_max_allowed_packet        =@@global.max_allowed_packet;
set @my_join_buffer_size          =@@global.join_buffer_size;
set @`test`=1;
set @TEST=2;
set @"tEST"=3;
set @`TeST`=4;
set @select=2,@t5=1.23456;
set @test_int=10,@test_double=1e-10,@test_string="abcdeghi",@test_string2="abcdefghij",@select=NULL;
set @test_int="hello",@test_double="hello",@test_string="hello",@test_string2="hello";
set @test_int="hellohello",@test_double="hellohello",@test_string="hellohello",@test_string2="hellohello";
set @test_int=null,@test_double=null,@test_string=null,@test_string2=null;
explain select @t1:=(@t2:=1)+@t3:=4,@t1,@t2,@t3;
CREATE TABLE t1 (c_id INT(4) NOT NULL, c_name CHAR(20), c_country CHAR(3), PRIMARY KEY(c_id));
INSERT INTO t1 VALUES (1,'Bozo','USA'),(2,'Ronald','USA'),(3,'Kinko','IRE'),(4,'Mr. Floppy','GB');
ALTER TABLE t1 DROP PRIMARY KEY;
drop table t1;
set GLOBAL max_join_size=10;
set max_join_size=100;
set max_join_size=1000;
show variables like 'max_join_size';
set max_join_size=100;
SET SQL_BIG_SELECTS=1;
show global variables like 'max_join_size';
set GLOBAL max_join_size=2000;
show global variables like 'max_join_size';
set max_join_size=DEFAULT;
show variables like 'max_join_size';
set GLOBAL max_join_size=DEFAULT;
show global variables like 'max_join_size';
set @@max_join_size=1000, @@global.max_join_size=2000;
explain select last_insert_id(345);
explain select @@IDENTITY,last_insert_id(), @@identity;
set big_tables=OFF, big_tables=ON, big_tables=0, big_tables=1, big_tables="OFF", big_tables="ON";
set global concurrent_insert=2;
show variables like 'concurrent_insert';
set global concurrent_insert=1;
