drop table if exists t1,t2,t3,t4,t9,`t1a``b`,v1,v2,v3,v4,v5,v6;
drop view if exists t1,t2,`t1a``b`,v1,v2,v3,v4,v5,v6;
drop database if exists mysqltest;
use test;
create view v1 (c,d) as select a,b from t1;
create temporary table t1 (a int, b int);
create view v1 (c) as select b+1 from t1;
drop table t1;
create table t1 (a int, b int);
insert into t1 values (1,2), (1,3), (2,4), (2,5), (3,10);
create view v1 (c,d) as select a,b+@@global.max_user_connections from t1;
create view v1 (c,d) as select a,b from t1 where a = @@global.max_user_connections;
CREATE VIEW v1 AS SELECT @a=1 FROM DUAL;
CREATE VIEW v1 AS SELECT 1 FROM DUAL WHERE @a>1;
CREATE VIEW v1 AS SELECT (@a:= 1) AS one FROM DUAL;
CREATE VIEW v1 AS SELECT 1 FROM DUAL WHERE (@a:= 1);
create view v1 (c) as select b+1 from t1;
create temporary table t1 (a int, b int);
show create table v1;
show create view v1;
show create view t1;
drop table t1;
analyze table t1;
explain select c from v1;
create algorithm=temptable view v2 (c) as select b+1 from t1;
show create view v2;
explain select c from v2;
create view v3 (c) as select a+1 from v1;
create view v3 (c) as select b+1 from v1;
create view v3 (c) as select c+1 from v1;
explain select c from v3;
create algorithm=temptable view v4 (c) as select c+1 from v2;
explain select c from v4;
create view v5 (c) as select c+1 from v2;
explain select c from v5;
create algorithm=temptable view v6 (c) as select c+1 from v1;
explain select c from v6;
show tables;
show full tables;
show table status;
drop view v1,v2,v3,v4,v5,v6;
create view v1 (c,d,e,f) as select a,b, a in (select a+2 from t1), a = all (select a from t1) from t1;
create view v2 as select c, d from v1;
create view v1 (c,d,e,f) as select a,b, a in (select a+2 from t1), a = all (select a from t1) from t1;
create or replace view v1 (c,d,e,f) as select a,b, a in (select a+2 from t1), a = all (select a from t1) from t1;
drop view v2;
alter view v2 as select c, d from v1;
create or replace view v2 as select c, d from v1;
alter view v1 (c,d) as select a,max(b) from t1 group by a;
drop view v100;
drop view t1;
drop table v1;
drop view v1,v2;
drop table t1;
create table t1 (a int);
insert into t1 values (1), (2), (3);
create view v1 (a) as select a+1 from t1;
create view v2 (a) as select a-1 from t1;
drop view v1, v2;
drop table t1;
create table t1 (a int);
insert into t1 values (1), (2), (3), (1), (2), (3);
