drop table if exists t1, t2;
create table t1 (a int) engine=innodb;
xa start 'test1';
insert t1 values (10);
xa end 'test1';
xa prepare 'test1';
xa rollback 'test1';
select * from t1;
xa start 'test2';
xa start 'test-bad';
insert t1 values (20);
xa prepare 'test2';
xa end 'test2';
xa prepare 'test2';
xa commit 'test2';
select * from t1;
xa start 'testa','testb';
insert t1 values (30);
commit;
xa end 'testa','testb';
begin;
create table t2 (a int);
xa start 'testa','testb';
xa start 'testa','testb', 123;
xa start 0x7465737462, 0x2030405060, 0xb;
insert t1 values (40);
xa end 'testb',' 0@P`',11;
xa prepare 'testb',0x2030405060,11;
start transaction;
xa recover;
xa prepare 'testa','testb';
xa recover;
xa commit 'testb',0x2030405060,11;
xa rollback 'testb',0x2030405060,11;
xa rollback 'testa','testb';
xa commit 'testb',0x2030405060,11;
xa rollback 'testb',0x2030405060,11;
xa start 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz';
select * from t1;
show session status;
xa recover;
xa rollback 'testb',0x2030405060,11;
drop table t1;
drop table if exists t1;
create table t1(a int, b int, c varchar(20), primary key(a)) engine = innodb;
insert into t1 values(1, 1, 'a');
insert into t1 values(2, 2, 'b');
xa start 'a','b';
update t1 set c = 'aa' where a = 1;
xa start 'a','c';
update t1 set c = 'bb' where a = 2;
update t1 set c = 'bb' where a = 2;
update t1 set c = 'aa' where a = 1;
select count(*) from t1;
xa end 'a','c';
xa rollback 'a','c';
xa start 'a','c';
reap;
drop table t1;
CREATE TABLE t1(a INT) ENGINE=InnoDB;
XA START 'x';
SET SESSION autocommit=0;
INSERT INTO t1 VALUES(1);
SET SESSION autocommit=1;
SELECT @@autocommit;
INSERT INTO t1 VALUES(1);
XA END 'x';
XA COMMIT 'x' ONE PHASE;
DROP TABLE t1;
SET SESSION autocommit=1;
xa start 'a';
xa end 'a';
xa rollback 'a';
xa start 'a';
xa end 'a';
xa rollback 'a';
xa start 'a';
xa end 'a';
xa prepare 'a';
xa commit 'a';
xa start 'a';
xa end 'a';
xa prepare 'a';
xa commit 'a';
CREATE TABLE t1(a INT, KEY(a)) ENGINE=InnoDB;
INSERT INTO t1 VALUES(1),(2);
BEGIN;
UPDATE t1 SET a=3 WHERE a=1;
BEGIN;
UPDATE t1 SET a=4 WHERE a=2;
UPDATE t1 SET a=5 WHERE a=2;
UPDATE t1 SET a=5 WHERE a=1;
ROLLBACK;
REAP;
ROLLBACK;
BEGIN;
UPDATE t1 SET a=3 WHERE a=1;
XA START 'xid1';
UPDATE t1 SET a=4 WHERE a=2;
UPDATE t1 SET a=5 WHERE a=2;
UPDATE t1 SET a=5 WHERE a=1;
XA END 'xid1';
XA ROLLBACK 'xid1';
XA START 'xid1';
XA END 'xid1';
XA ROLLBACK 'xid1';
REAP;
DROP TABLE t1;
XA START 'x';
XA END 'x';
XA END 'x';
XA PREPARE 'x';
XA PREPARE 'x';
XA ROLLBACK 'x';
DROP TABLE IF EXISTS t1;
CREATE TABLE t1(a INT, b INT, PRIMARY KEY(a)) engine=InnoDB;
INSERT INTO t1 VALUES (1, 1), (2, 2);
XA START 'a';
UPDATE t1 SET b= 3 WHERE a=1;
XA START 'b';
UPDATE t1 SET b=4 WHERE a=2;
UPDATE t1 SET b=5 WHERE a=1;
UPDATE t1 SET b=6 WHERE a=2;
XA COMMIT 'a';
reap;
XA END 'b';
XA ROLLBACK 'b';
DROP TABLE t1;
CREATE TABLE t1 (a INT) engine=InnoDB;
XA START 'a';
INSERT INTO t1 VALUES (1);
SAVEPOINT savep;
XA END 'a';
SELECT * FROM t1;
INSERT INTO t1 VALUES (2);
SAVEPOINT savep;
SET @a=(SELECT * FROM t1);
XA PREPARE 'a';
SELECT * FROM t1;
INSERT INTO t1 VALUES (2);
SAVEPOINT savep;
SET @a=(SELECT * FROM t1);
UPDATE t1 SET a=1 WHERE a=2;
XA COMMIT 'a';
SELECT * FROM t1;
DROP TABLE t1;
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (a INT) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1);
START TRANSACTION;
SELECT a FROM t1 WHERE a=1 FOR SHARE;
XA START 'xid1';
SELECT a FROM t1 WHERE a=1 FOR UPDATE;
SELECT a FROM t1 WHERE a=1 FOR UPDATE;
reap;
XA COMMIT 'xid1';
COMMIT;
XA START 'xid1';
XA END 'xid1';
XA PREPARE 'xid1';
XA ROLLBACK 'xid1';
DROP TABLE t1;
xa start 0xABCDEF1234567890, 0x01, 0x02 ;
xa end 0xABCDEF1234567890, 0x01, 0x02 ;
xa prepare 0xABCDEF1234567890, 0x01, 0x02 ;
xa recover convert xid;
xa rollback 0xABCDEF1234567890, 0x01, 0x02 ;
xa start 0x4142434445, 0x46, 0x02 ;
xa end 0x4142434445, 0x46, 0x02 ;
xa prepare 0x4142434445, 0x46, 0x02 ;
xa recover;
xa rollback 0x4142434445, 0x46, 0x02 ;
call mtr.add_suppression("Found 1 prepared XA transactions");
CREATE TABLE t1 (a INT) ENGINE=INNODB;
XA START 'xid1';
INSERT INTO t1 VALUES (1);
XA END 'xid1';
show session status;
SELECT * FROM t1;
DROP TABLE t1;
SET SESSION autocommit=0;
START TRANSACTION;
XA START 'xid1';
COMMIT;
show session status;
XA START 'xid1' RESUME;
XA START 'xid1';
XA END 'xid1';
XA START 'xid1' RESUME;
XA END 'xid1';
show session status;
XA START 'xid1';
XA END 'xid1';
XA START 'xid2' RESUME;
show session status;
XA START 'xid1';
XA END 'xid1' SUSPEND;
XA END 'xid1';
show session status;
XA START 'xid1';
XA END 'xid2';
XA END 'xid1';
show session status;
XA START 'xid1';
XA ROLLBACK 'xid1';
XA END 'xid1';
show session status;
XA START 'xid1';
XA END 'xid1';
XA PREPARE 'xid2';
show session status;
XA START 'xid1';
XA END 'xid1';
XA PREPARE 'xid1';
XA ROLLBACK 'xid2';
XA ROLLBACK 'xid1';
XA START '1', 0x01, 18446744073709551615;
set session lock_wait_timeout=1;
create table asd (a int);
xa start 'test1';
insert into asd values(1);
xa end 'test1';
flush table with read lock;
xa prepare 'test1';
show errors;
unlock tables;
xa start 'test1';
insert into asd values(1);
xa end 'test1';
xa prepare 'test1';
flush tables with read lock;
xa rollback 'test1';
show errors;
xa recover;
xa commit 'test1';
show errors;
xa recover;
unlock tables;
xa rollback 'test1';
xa recover;
drop table asd;
show session status;
XA RECOVER;
CREATE USER u1;
GRANT XA_RECOVER_ADMIN ON *.* TO u1;
CREATE USER u2;
XA START 'xid1';
XA END 'xid1';
XA PREPARE 'xid1';
XA RECOVER;
XA RECOVER;
SHOW WARNINGS;
show session status;
XA RECOVER;
XA COMMIT 'xid1';
XA START 'xid2';
XA END 'xid2';
XA PREPARE 'xid2';
XA RECOVER;
SHOW WARNINGS;
XA COMMIT 'xid2';
show session status;
DROP USER u1, u2;
CREATE USER u1;
GRANT SUPER ON *.* TO u1;
SHOW GRANTS FOR u1;
XA START 'xid1';
XA END 'xid1';
XA PREPARE 'xid1';
XA RECOVER;
XA COMMIT 'xid1';
show session status;
DROP USER u1;
XA START 'xid1';
XA END 'xid1';
XA PREPARE 'xid1';
show session status;
SET autocommit = 0;
XA RECOVER;
XA COMMIT 'xid1';
XA START 'xid1';
XA END 'xid1';
XA PREPARE 'xid1';
show session status;
SET autocommit = 0;
XA RECOVER;
XA ROLLBACK 'xid1';
CREATE TABLE t1 (a INT) ENGINE=INNODB;
XA START X'1A2B3C4D5E6F',X'F6E5D4C3B2A1',12345;
INSERT INTO t1 VALUES (1);
XA END X'1A2B3C4D5E6F',X'F6E5D4C3B2A1',12345;
XA PREPARE X'1A2B3C4D5E6F',X'F6E5D4C3B2A1',12345;
show session status;
XA ROLLBACK X'1A2B3C4D5E6F',X'F6E5D4C3B2A1',2;
XA RECOVER CONVERT XID;
XA ROLLBACK X'1A2B3C4D5E6F',X'F6E5D4C3B2A1',12345;
DROP TABLE t1;
show session status;
