UPDATE performance_schema.setup_instruments SET ENABLED=1 WHERE name='wait/lock/metadata/sql/mdl';
CREATE TABLE t1 (a INT);
SELECT * FROM t1;
XA START 'test';
INSERT INTO t1 VALUES (10);
XA END 'test';
XA PREPARE 'test';
show session status;
SELECT * FROM t1;
SELECT object_type, object_schema, object_name, lock_type, lock_duration, lock_status FROM performance_schema.metadata_locks WHERE object_schema = 'test';
SHOW TABLES;
XA RECOVER;
XA COMMIT 'test';
SELECT object_type, object_schema, object_name, lock_type, lock_duration, lock_status FROM performance_schema.metadata_locks WHERE object_schema = 'test';
XA RECOVER;
SELECT * FROM t1;
DROP TABLE t1;
CREATE TABLE t1 (a INT);
SELECT * FROM t1;
XA START 'test';
INSERT INTO t1 VALUES (10);
XA END 'test';
XA PREPARE 'test';
show session status;
SELECT * FROM t1;
SELECT object_type, object_schema, object_name, lock_type, lock_duration, lock_status FROM performance_schema.metadata_locks WHERE object_schema = 'test';
SHOW TABLES;
XA RECOVER;
XA ROLLBACK 'test';
SELECT object_type, object_schema, object_name, lock_type, lock_duration, lock_status FROM performance_schema.metadata_locks WHERE object_schema = 'test';
XA RECOVER;
SELECT * FROM t1;
DROP TABLE t1;
CREATE TABLE t1 (a INT);
SELECT * FROM t1;
XA START 'test';
INSERT INTO t1 VALUES (10);
XA END 'test';
XA PREPARE 'test';
SELECT * FROM t1;
DROP TABLE t1;
show session status;
SELECT object_type, object_schema, object_name, lock_type, lock_duration, lock_status FROM performance_schema.metadata_locks WHERE object_schema = 'test';
SHOW TABLES;
XA RECOVER;
XA COMMIT 'test';
SELECT object_type, object_schema, object_name, lock_type, lock_duration, lock_status FROM performance_schema.metadata_locks WHERE object_schema = 'test';
XA RECOVER;
reap;
show session status;
CREATE TABLE t1 (a INT);
XA START 'test';
INSERT INTO t1 VALUES (10);
XA END 'test';
XA PREPARE 'test';
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
SELECT * FROM t1;
SELECT object_type, object_schema, object_name, lock_type, lock_duration, lock_status FROM performance_schema.metadata_locks WHERE object_schema = 'test';
SHOW TABLES;
XA RECOVER;
XA COMMIT 'test';
SELECT object_type, object_schema, object_name, lock_type, lock_duration, lock_status FROM performance_schema.metadata_locks WHERE object_schema = 'test';
XA RECOVER;
SELECT * FROM t1;
DROP TABLE t1;
CREATE TABLE t1 (a INT);
