SET @xml='<a aa1="aa1" aa2="aa2">a1<b ba1="ba1">b1<c>c1</c>b2</b>a2</a>';
SET @xml='<a>a11<b ba="ba11" ba="ba12">b11</b><b ba="ba21" ba="ba22">b21<c>c1</c>b22</b>a12</a>';
SET @xml='<a><b>b</b><c>c</c></a>';
SET @xml='<a><b>b1</b><c>c1</c><b>b2</b><c>c2</c></a>';
SET @xml='<a><b x="xb1" x="xb2"/><c x="xc1" x="xc2"/></a>';
SET @xml='<a><b>b1</b><b>b2</b><c><b>c1b1</b><b>c1b2</b></c><c><b>c2b1</c></b></a>';
SET @xml='<a><b>b1</b><b>b2</b></a>';
SET @xml='<a><b>b11<c>c11</c></b><b>b21<c>c21</c></b></a>';
SET @xml='<a><b c="c11">b11</b><b c="c21">b21</b></a>';
SET @xml='<a>a1<b c="c11">b11<d>d11</d></b><b c="c21">b21<d>d21</d></b></a>';
SET @xml='<a>ab<b c="c" c="e">b1</b><b c="d">b2</b><b c="f" c="e">b3</b></a>';
SET @xml='<a><b c="c" d="d">b1</b><b d="d" e="e">b2</b></a>';
SET @xml='<a><b c="c">b1</b><b>b2</b></a>';
SET @xml='<a b="11" b="12" b="21" b="22">ab</a>';
SET @xml='<a><b>b1</b><b>b2</b></a>';
SET @xml='<a b="b11" b="b12" b="b21" b="22"/>';
SET @xml='<a>a1<b>b1<c>c1</c>b2</b>a2</a>';
SET @xml='<a><b>bb</b></a>';
SET @xml='<a aa1="aa1" aa2="aa2"><b bb1="bb1" bb2="bb2">bb</b></a>';
SET @xml= '<order><clerk>lesser wombat</clerk></order>';
set names latin1;
set names utf8mb4;
set names utf8;
DROP PROCEDURE IF EXISTS p2;
CREATE PROCEDURE p2 () BEGIN DECLARE p LONGTEXT CHARACTER SET UTF8 DEFAULT '<Ñ><r>A</r></Ñ>'; SELECT EXTRACTVALUE(p,'/Ñ/r'); END;
CALL p2();
DROP PROCEDURE p2;
set @xml= "<entry><id>pt10</id><pt>10</pt></entry><entry><id>pt50</id><pt>50</pt></entry>";
SET sql_mode = 'NO_ENGINE_SUBSTITUTION';
set @i=1;
set @i=2;
set @i=NULL;
CREATE PROCEDURE spxml(xml VARCHAR(128)) BEGIN DECLARE c INT; DECLARE i INT DEFAULT 1; SET c= ExtractValue(xml,'count(/a/b)'); SET @i= c; WHILE i <= c DO BEGIN SELECT i, @i, ExtractValue(xml,'/a/b[$i]'), ExtractValue(xml,'/a/b[$@i]'); SET i= i + 1; SET @i= @i - 1; END; END WHILE; END;
call spxml('<a><b>b1</b><b>b2</b><b>b3</b></a>');
drop procedure spxml;
SET @i='1';
SET @i='1 and string';
SET @i='string and 1';
SET @i='string';
CREATE PROCEDURE spxml(xml VARCHAR(128), i CHAR(16)) BEGIN SELECT ExtractValue(xml,'/a/b[$i]'); END;
CALL spxml('<a><b>b1</b><b>b2</b></a>', '1');
CALL spxml('<a><b>b1</b><b>b2</b></a>', '1 and string');
CALL spxml('<a><b>b1</b><b>b2</b></a>', 'string and 1');
CALL spxml('<a><b>b1</b><b>b2</b></a>', 'string');
DROP PROCEDURE spxml;
SET sql_mode = default;
CREATE TABLE t1(a INT NOT NULL);
INSERT INTO t1 VALUES (0), (0);
DROP TABLE t1;
SET @xml= '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> <html>   <head>   <title> Title - document with document declaration</title>  </head>    <body> Hi, Im a webpage with document a declaration </body>  </html>';
set @x=10;
CREATE TABLE IF NOT EXISTS t1 ( id int(10) unsigned NOT NULL AUTO_INCREMENT, xml text, PRIMARY KEY (id) );
INSERT INTO t1 (id, xml) VALUES (15, '<?xml version="1.0"?><bla name="blubb"></bla>'), (14, '<xml version="kaputt">');
DROP TABLE t1;
SET NAMES utf8;
SET NAMES latin1;
set names utf8;
do weight_string(extractvalue('','/*/a'));
do char((weight_string(extractvalue((''),('tX')))) using cp852);
set names default;
set @x = '<MESSAGE><DATA1>HOLA</DATA1></MESSAGE>';
set @y = 'Default Value';
