USE test;
RESET MASTER;
RESET REPLICA ALL FOR CHANNEL '';
USE test;
RESET MASTER;
RESET REPLICA ALL FOR CHANNEL '';
CHANGE REPLICATION SOURCE TO SOURCE_HOST = '127.0.0.1', SOURCE_PORT = 13000, SOURCE_USER = 'root', SOURCE_AUTO_POSITION = 0, PRIVILEGE_CHECKS_USER = NULL, REQUIRE_ROW_FORMAT = 0, GTID_ONLY = 0, SOURCE_CONNECT_RETRY = 1 FOR CHANNEL '';
START REPLICA ;
SELECT ATTR_NAME, ATTR_VALUE FROM performance_schema.session_connect_attrs WHERE PROCESSLIST_ID = 12 AND ATTR_NAME IN ('program_name', '_client_replication_channel_name', '_client_role');
STOP REPLICA ;
KILL 12;
SELECT ATTR_NAME, ATTR_VALUE FROM performance_schema.session_connect_attrs WHERE PROCESSLIST_ID = 15 AND ATTR_NAME IN ('program_name', '_client_replication_channel_name', '_client_role');
KILL 15;
SELECT asynchronous_connection_failover_reset();
SELECT asynchronous_connection_failover_reset();
