call mtr.add_suppression("\\[Warning\\] \\[[^]]*\\] Server shutdown in progress");
CREATE USER user1;
SELECT host,user,plugin FROM mysql.user WHERE USER='user1';
CREATE USER user3@%;
CREATE USER user3@localhost BY 'auth_string' WITH 'sha_256_password';
CREATE USER "user2"@'%';
SELECT host,user,plugin FROM mysql.user WHERE USER='user2';
CREATE USER user9@localhost IDENTIFIED WITH 'mysql_native_password' AS 'auth_string';
CREATE USER user10@localhost IDENTIFIED WITH 'caching_sha2_password' AS '$A$005$ABCDEFGHIJKLMNOPQRSTabcdefgh01234567ijklmnop89012345ABCDEFGH678';
CREATE USER u1@localhost;
SELECT User,plugin FROM mysql.user WHERE USER='u1';
CREATE USER u2@localhost IDENTIFIED BY 'auth_string';
SELECT User,plugin FROM mysql.user WHERE USER='u2';
CREATE USER user5@localhost IDENTIFIED  AS 'auth_string';
CREATE USER u3@localhost IDENTIFIED WITH 'sha256_password';
SELECT User,plugin FROM mysql.user WHERE USER='u3';
CREATE USER u4@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string';
SELECT User,plugin FROM mysql.user WHERE USER='u4';
SELECT USER();
CREATE USER user4@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string';
SELECT User,plugin FROM mysql.user WHERE USER='user4';
CREATE USER user6@localhost IDENTIFIED WITH 'mysql_native_password';
SELECT User,plugin FROM mysql.user WHERE USER='user6';
CREATE USER user7@localhost IDENTIFIED WITH 'mysql_native_password' BY 'auth_string#%y';
SELECT User,plugin FROM mysql.user WHERE USER='user7';
SELECT USER();
CREATE USER user8@localhost IDENTIFIED WITH 'mysql_native_password'             AS '*67092806AE91BFB6BE72DE6C7BE2B7CCA8CFA9DF'             PASSWORD EXPIRE NEVER;
SELECT User,plugin,password_expired, password_lifetime FROM mysql.user WHERE USER='user8';
SELECT USER();
CREATE USER tu1@localhost IDENTIFIED WITH 'test_plugin_server';
SELECT User,plugin,password_expired, password_expired FROM mysql.user WHERE USER='tu1';
CREATE USER tu2@localhost IDENTIFIED WITH 'test_plugin_server'             BY 'auth_@13*' PASSWORD EXPIRE;
SELECT User,plugin,password_expired FROM mysql.user WHERE USER='tu2';
CREATE USER tu3@localhost IDENTIFIED WITH 'test_plugin_server' AS '%auth_O0s-tring';
SELECT User,plugin,password_expired FROM mysql.user WHERE USER='tu3';
CREATE USER u5@localhost REQUIRE SSL;
SELECT User,plugin,ssl_type FROM mysql.user WHERE USER='u5';
CREATE USER u6@localhost IDENTIFIED BY 'auth_string' REQUIRE X509;
SELECT User,plugin,ssl_type FROM mysql.user WHERE USER='u6';
CREATE USER tu4@localhost IDENTIFIED WITH 'test_plugin_server' BY 'djgsj743$'                           REQUIRE SSL;
SELECT User,plugin,ssl_type FROM mysql.user WHERE USER='tu4';
CREATE USER tu5@localhost IDENTIFIED WITH 'test_plugin_server' AS 'dwh@#ghd$!'                           REQUIRE X509;
SELECT User,plugin,ssl_type FROM mysql.user WHERE USER='tu5';
CREATE USER u7@localhost IDENTIFIED WITH 'sha256_password' REQUIRE CIPHER 'cipher';
SELECT User,plugin,ssl_type,ssl_cipher, x509_issuer,x509_subject FROM mysql.user WHERE USER='u7';
CREATE USER u8@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string' REQUIRE ISSUER '/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA' PASSWORD EXPIRE NEVER;
SELECT User,plugin,ssl_type,ssl_cipher,x509_issuer, x509_subject,password_expired,password_lifetime FROM mysql.user WHERE USER='u8';
SELECT USER();
CREATE USER u9@localhost REQUIRE SUBJECT 'sub';
SELECT User,plugin,ssl_type,ssl_cipher, x509_issuer,x509_subject FROM mysql.user WHERE USER='u9';
CREATE USER u10@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string#y' REQUIRE CIPHER "DHE-RSA-AES256-SHA" AND SUBJECT "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client" ISSUER "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA" PASSWORD EXPIRE DEFAULT;
SELECT User,plugin,ssl_type,ssl_cipher,x509_issuer, x509_subject,password_expired,password_lifetime FROM mysql.user WHERE USER='u10';
SELECT USER();
CREATE USER tu6@localhost IDENTIFIED WITH 'test_plugin_server' AS '#hGrt0O6' REQUIRE CIPHER "DHE-RSA-AES256-SHA" AND SUBJECT "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client" ISSUER "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA" WITH MAX_QUERIES_PER_HOUR 2 MAX_USER_CONNECTIONS 2;
SELECT User,plugin,ssl_type,ssl_cipher,x509_issuer, x509_subject,max_questions,max_user_connections FROM mysql.user WHERE USER='tu6';
CREATE USER u11@localhost WITH MAX_QUERIES_PER_HOUR 2;
SELECT User,plugin,max_questions FROM mysql.user WHERE USER='u11';
CREATE USER u12@localhost IDENTIFIED BY 'auth_string'                           WITH MAX_QUERIES_PER_HOUR 2 PASSWORD EXPIRE NEVER;
SELECT User,plugin,max_questions, password_expired,password_lifetime FROM mysql.user WHERE USER='u12';
CREATE USER u13@localhost IDENTIFIED WITH 'sha256_password'                           WITH MAX_CONNECTIONS_PER_HOUR 2;
SELECT User,plugin,max_connections FROM mysql.user WHERE USER='u13';
CREATE USER u14@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string'                           WITH MAX_USER_CONNECTIONS 2  PASSWORD EXPIRE INTERVAL 999 DAY;
SELECT User,plugin,max_user_connections, password_expired,password_lifetime FROM mysql.user WHERE USER='u14';
CREATE USER u15@localhost, u16@localhost IDENTIFIED BY 'auth_string', u17@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string';
SELECT User,ssl_type,ssl_cipher,x509_issuer,x509_subject, plugin,password_expired,password_lifetime FROM mysql.user WHERE USER='u15';
SELECT User,ssl_type,ssl_cipher,x509_issuer,x509_subject, plugin,password_expired,password_lifetime FROM mysql.user WHERE USER='u16';
SELECT User,ssl_type,ssl_cipher,x509_issuer,x509_subject, plugin,password_expired,password_lifetime FROM mysql.user WHERE USER='u17';
CREATE USER u18@localhost, u19@localhost IDENTIFIED BY 'auth_string', u20@localhost IDENTIFIED WITH 'sha256_password', u21@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string', u22@localhost IDENTIFIED WITH 'test_plugin_server', u23@localhost IDENTIFIED WITH 'mysql_native_password' BY 'auth_&string'             REQUIRE SUBJECT '/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client'             WITH MAX_QUERIES_PER_HOUR 2 MAX_USER_CONNECTIONS 2;
SELECT User,plugin,ssl_type,ssl_cipher, x509_issuer,x509_subject,max_questions,max_user_connections,password_expired, password_lifetime FROM mysql.user WHERE USER='u18';
SELECT User,plugin,ssl_type,ssl_cipher, x509_issuer,x509_subject,max_questions,max_user_connections,password_expired, password_lifetime FROM mysql.user WHERE USER='u19';
SELECT User,plugin,ssl_type,ssl_cipher, x509_issuer,x509_subject,max_questions,max_user_connections,password_expired, password_lifetime FROM mysql.user WHERE USER='u20';
SELECT User,plugin,ssl_type,ssl_cipher, x509_issuer,x509_subject,max_questions,max_user_connections,password_expired, password_lifetime FROM mysql.user WHERE USER='u21';
SELECT User,plugin,ssl_type,ssl_cipher, x509_issuer,x509_subject,max_questions,max_user_connections,password_expired, password_lifetime FROM mysql.user WHERE USER='u22';
SELECT User,plugin,ssl_type,ssl_cipher, x509_issuer,x509_subject,max_questions,max_user_connections,password_expired, password_lifetime FROM mysql.user WHERE USER='u23';
DROP USER tu1@localhost,tu2@localhost,tu3@localhost,tu4@localhost,tu5@localhost, tu6@localhost,user1@'%',user2@'%',user4@localhost,user6@localhost, user7@localhost,user8@localhost,user10@localhost,u1@localhost,u2@localhost, u3@localhost,u4@localhost,u5@localhost,u6@localhost,u7@localhost,u8@localhost, u9@localhost,u10@localhost,u11@localhost,u12@localhost,u13@localhost, u14@localhost,u15@localhost,u16@localhost,u17@localhost,u18@localhost, u19@localhost,u20@localhost,u21@localhost,u22@localhost,u23@localhost;
CREATE USER u1@localhost;
SELECT User,ssl_type,ssl_cipher,x509_issuer,x509_subject, plugin,password_expired, password_last_changed,password_lifetime FROM mysql.user WHERE USER='u1';
ALTER USER u1@localhost;
SELECT User,ssl_type,ssl_cipher,x509_issuer,x509_subject, plugin,password_expired, password_last_changed,password_lifetime FROM mysql.user WHERE USER='u1';
CREATE USER u2@localhost IDENTIFIED WITH 'mysql_native_password';
SELECT User,ssl_type,ssl_cipher,x509_issuer,x509_subject, plugin,password_expired, password_last_changed,password_lifetime FROM mysql.user WHERE USER='u2';
ALTER USER u2@localhost IDENTIFIED WITH 'mysql_native_password' PASSWORD EXPIRE NEVER;
