call mtr.add_suppression("\\[Warning\\] \\[[^]]*\\] Server shutdown in progress");
CREATE USER u1@localhost;
CREATE USER u2@localhost IDENTIFIED BY 'auth_string';
CREATE USER u3@localhost IDENTIFIED WITH 'sha256_password';
CREATE USER u4@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string';
SELECT USER();
SELECT USER();
SELECT USER();
CREATE USER tu1@localhost IDENTIFIED WITH 'test_plugin_server';
CREATE USER tu2@localhost IDENTIFIED WITH 'test_plugin_server'             BY 'auth_@13*' PASSWORD EXPIRE;
CREATE USER tu3@localhost IDENTIFIED WITH 'test_plugin_server' AS '%auth_O0s-tring';
CREATE USER u5@localhost REQUIRE SSL;
CREATE USER u6@localhost IDENTIFIED BY 'auth_string' REQUIRE X509;
CREATE USER tu4@localhost IDENTIFIED WITH 'test_plugin_server' BY 'djgsj743$'                           REQUIRE SSL;
CREATE USER tu5@localhost IDENTIFIED WITH 'test_plugin_server' AS 'dwh@#ghd$!'                           REQUIRE X509;
CREATE USER u7@localhost IDENTIFIED WITH 'sha256_password' REQUIRE CIPHER 'cipher';
CREATE USER u8@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string' REQUIRE ISSUER '/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA' PASSWORD EXPIRE NEVER;
SELECT USER();
CREATE USER u9@localhost REQUIRE SUBJECT 'sub';
CREATE USER u10@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string#y' REQUIRE CIPHER "DHE-RSA-AES256-SHA" AND SUBJECT "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client" ISSUER "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA" PASSWORD EXPIRE DEFAULT;
SELECT USER();
CREATE USER tu6@localhost IDENTIFIED WITH 'test_plugin_server' AS '#hGrt0O6' REQUIRE CIPHER "DHE-RSA-AES256-SHA" AND SUBJECT "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client" ISSUER "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA" WITH MAX_QUERIES_PER_HOUR 2 MAX_USER_CONNECTIONS 2;
CREATE USER u11@localhost WITH MAX_QUERIES_PER_HOUR 2;
CREATE USER u12@localhost IDENTIFIED BY 'auth_string'                           WITH MAX_QUERIES_PER_HOUR 2 PASSWORD EXPIRE NEVER;
CREATE USER u13@localhost IDENTIFIED WITH 'sha256_password'                           WITH MAX_CONNECTIONS_PER_HOUR 2;
CREATE USER u14@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string'                           WITH MAX_USER_CONNECTIONS 2  PASSWORD EXPIRE INTERVAL 999 DAY;
CREATE USER u15@localhost, u16@localhost IDENTIFIED BY 'auth_string', u17@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string';
CREATE USER u18@localhost, u19@localhost IDENTIFIED BY 'auth_string', u20@localhost IDENTIFIED WITH 'sha256_password', u21@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string', u22@localhost IDENTIFIED WITH 'test_plugin_server', u23@localhost IDENTIFIED WITH 'mysql_native_password' BY 'auth_&string'             REQUIRE SUBJECT '/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client'             WITH MAX_QUERIES_PER_HOUR 2 MAX_USER_CONNECTIONS 2;
CREATE USER u1@localhost;
ALTER USER u1@localhost;
CREATE USER u2@localhost IDENTIFIED WITH 'mysql_native_password';
ALTER USER u2@localhost IDENTIFIED WITH 'mysql_native_password' PASSWORD EXPIRE NEVER;
SELECT USER();
ALTER USER USER() IDENTIFIED BY 'abc';
CREATE USER u3@localhost IDENTIFIED WITH 'sha256_password';
ALTER USER u3@localhost IDENTIFIED WITH 'mysql_native_password'                         AS '*67092806AE91BFB6BE72DE6C7BE2B7CCA8CFA9DF';
SELECT USER();
ALTER USER u3@localhost IDENTIFIED WITH 'test_plugin_server' BY 'auth_string';
ALTER USER u3@localhost REQUIRE SUBJECT '/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client'            WITH MAX_QUERIES_PER_HOUR 2 MAX_USER_CONNECTIONS 2 PASSWORD EXPIRE NEVER;
CREATE USER u4@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string';
ALTER USER u4@localhost IDENTIFIED WITH 'mysql_native_password' BY 'auth_string';
CREATE USER u5@localhost REQUIRE SSL;
ALTER USER u5@localhost IDENTIFIED WITH 'sha256_password';
SET PASSWORD='new_auth_string';
SELECT USER();
CREATE USER u6@localhost IDENTIFIED BY 'auth_string' REQUIRE X509;
ALTER USER u6@localhost IDENTIFIED WITH 'test_plugin_server'                         AS 'new_auth_string' REQUIRE SSL;
CREATE USER u7@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string'                          REQUIRE CIPHER 'DHE-RSA-AES256-SHA';
ALTER USER u7@localhost IDENTIFIED WITH 'sha256_password' BY 'new_auth_string'                         REQUIRE ISSUER '/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA';
SELECT USER();
CREATE USER u8@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string'                          REQUIRE ISSUER '/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA';
ALTER USER u8@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string'                         REQUIRE CIPHER "DHE-RSA-AES256-SHA";
SELECT USER();
CREATE USER tu1@localhost IDENTIFIED WITH 'mysql_native_password'                           BY 'auth_string' REQUIRE ISSUER 'issuer';
ALTER USER tu1@localhost IDENTIFIED WITH 'sha256_password'                          REQUIRE CIPHER "DHE-RSA-AES256-SHA";
CREATE USER u9@localhost REQUIRE SUBJECT 'sub';
ALTER USER u9@localhost REQUIRE ISSUER "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA";
ALTER USER u9@localhost IDENTIFIED WITH 'test_plugin_server' BY 'auth_string77hg'                         REQUIRE ISSUER "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA";
CREATE USER u10@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string'                           REQUIRE CIPHER "DHE-RSA-AES256-SHA" AND SUBJECT "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client"                           ISSUER "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA";
ALTER USER u10@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string'                          REQUIRE SSL;
SELECT USER();
CREATE USER u11@localhost WITH MAX_QUERIES_PER_HOUR 2;
ALTER USER u11@localhost WITH MAX_QUERIES_PER_HOUR 6;
CREATE USER u12@localhost IDENTIFIED BY 'auth_string'                           WITH MAX_QUERIES_PER_HOUR 2;
ALTER USER u12@localhost IDENTIFIED WITH 'sha256_password'                          WITH MAX_QUERIES_PER_HOUR 8;
ALTER USER u12@localhost IDENTIFIED WITH 'test_plugin_server'                          WITH MAX_QUERIES_PER_HOUR 1000;
CREATE USER u13@localhost IDENTIFIED WITH 'sha256_password'                           WITH MAX_CONNECTIONS_PER_HOUR 2;
ALTER USER u13@localhost PASSWORD EXPIRE;
SELECT USER();
ALTER USER USER() IDENTIFIED BY 'new_pwd_string';
SELECT USER();
CREATE USER u14@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string'                           WITH MAX_USER_CONNECTIONS 2;
ALTER USER u14@localhost WITH MAX_USER_CONNECTIONS 12 PASSWORD EXPIRE INTERVAL 365 DAY;
CREATE USER tu2@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string'                           WITH MAX_USER_CONNECTIONS 2 ;
ALTER USER tu2@localhost WITH MAX_USER_CONNECTIONS 12 MAX_QUERIES_PER_HOUR 543 PASSWORD EXPIRE INTERVAL 365 DAY;
SELECT USER();
CREATE USER u15@localhost, u16@localhost IDENTIFIED WITH 'sha256_password', u17@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string';
ALTER USER u15@localhost IDENTIFIED WITH 'sha256_password', u16@localhost, u17@localhost IDENTIFIED BY 'new_auth_string'                          PASSWORD EXPIRE DEFAULT;
CREATE USER u18@localhost, u19@localhost IDENTIFIED BY 'auth_string', u20@localhost IDENTIFIED WITH 'sha256_password', u21@localhost IDENTIFIED WITH 'sha256_password' BY '!Y_TOdh6)', u22@localhost IDENTIFIED WITH 'sha256_password', u23@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_&string'             REQUIRE SUBJECT '/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client'             WITH MAX_QUERIES_PER_HOUR 2 MAX_USER_CONNECTIONS 2;
ALTER USER u18@localhost, u19@localhost, u20@localhost, u21@localhost, u22@localhost, u23@localhost REQUIRE SUBJECT '/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client'            WITH MAX_QUERIES_PER_HOUR 2 MAX_USER_CONNECTIONS 2 PASSWORD EXPIRE NEVER;
DROP USER tu1@localhost,tu2@localhost,u1@localhost, u2@localhost, u3@localhost, u4@localhost, u5@localhost,u6@localhost, u7@localhost, u8@localhost, u9@localhost, u10@localhost,u11@localhost, u12@localhost, u13@localhost, u14@localhost,u15@localhost, u16@localhost, u17@localhost, u18@localhost, u19@localhost, u20@localhost, u21@localhost,u22@localhost,u23@localhost;
CREATE USER u1@localhost IDENTIFIED BY 'abc';
SELECT USER();
ALTER USER u1@localhost PASSWORD EXPIRE;
SELECT USER();
SET PASSWORD = 'def';
SELECT USER();
ALTER USER u1@localhost PASSWORD EXPIRE;
SELECT USER();
ALTER USER IDENTIFIED BY 'npwd';
ALTER USER USER() IDENTIFIED BY 'abc';
SELECT USER();
ALTER USER u1@localhost PASSWORD EXPIRE;
SELECT USER();
ALTER USER u1@localhost IDENTIFIED BY 'def';
SELECT USER();
DROP USER u1@localhost;
CREATE USER u1@localhost, u2@localhost IDENTIFIED BY 'abc';
GRANT ALL ON *.* TO u2@localhost;
ALTER USER USER() IDENTIFIED WITH 'sha256_password';
ALTER USER USER() IDENTIFIED BY 'def', u2@localhost PASSWORD EXPIRE;
ALTER USER USER() IDENTIFIED BY 'def' PASSWORD EXPIRE;
ALTER USER ;
ALTER USER u2@localhost IDENTIFIED BY 'auth_string'                         PASSWORD EXPIRE INTERVAL 45 DAY;
DROP USER u1@localhost, u2@localhost;
CREATE USER u1@localhost;
SHOW CREATE USER u1@localhost;
CREATE USER u2@localhost IDENTIFIED BY 'auth_string';
SHOW CREATE USER u2@localhost;
DROP USER u2@localhost;
CREATE USER 'u2'@'localhost' IDENTIFIED WITH 'mysql_native_password'                              AS '*67092806AE91BFB6BE72DE6C7BE2B7CCA8CFA9DF'                              REQUIRE NONE;
SELECT USER();
CREATE USER u3@localhost IDENTIFIED WITH 'sha256_password';
SHOW CREATE USER u3@localhost;
ALTER USER u3@localhost IDENTIFIED BY 'auth_string';
SHOW CREATE USER u3@localhost;
CREATE USER u4@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string';
SHOW CREATE USER u4@localhost;
CREATE USER u5@localhost REQUIRE SSL;
SHOW CREATE USER u5@localhost;
ALTER USER u5@localhost REQUIRE X509;
SHOW CREATE USER u5@localhost;
CREATE USER u6@localhost IDENTIFIED BY 'auth_string'                          REQUIRE X509 PASSWORD EXPIRE INTERVAL 5 DAY;
SHOW CREATE USER u6@localhost;
ALTER USER u6@localhost IDENTIFIED BY 'auth_string'                         REQUIRE X509 PASSWORD EXPIRE INTERVAL 19 DAY;
SHOW CREATE USER u6@localhost;
DROP USER u6@localhost;
CREATE USER 'u6'@'localhost' IDENTIFIED WITH 'mysql_native_password'                              AS '*67092806AE91BFB6BE72DE6C7BE2B7CCA8CFA9DF'                              REQUIRE X509 PASSWORD EXPIRE INTERVAL 19 DAY;
CREATE USER u7@localhost IDENTIFIED WITH 'sha256_password'                          REQUIRE CIPHER 'cipher';
SHOW CREATE USER u7@localhost;
CREATE USER u8@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string'                          REQUIRE ISSUER 'issuer';
SHOW CREATE USER u8@localhost;
CREATE USER u9@localhost REQUIRE SUBJECT 'sub';
SHOW CREATE USER u9@localhost;
CREATE USER u10@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string'             REQUIRE CIPHER "DHE-RSA-AES256-SHA" AND SUBJECT "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client"             ISSUER "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA";
SHOW CREATE USER u10@localhost;
ALTER USER u10@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string'            REQUIRE CIPHER "DHE-RSA-AES256-SHA" AND SUBJECT "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client"            ISSUER "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA"            WITH MAX_CONNECTIONS_PER_HOUR 1000 MAX_USER_CONNECTIONS 20 MAX_QUERIES_PER_HOUR 60 MAX_UPDATES_PER_HOUR 100;
SHOW CREATE USER u10@localhost;
CREATE USER u11@localhost WITH MAX_QUERIES_PER_HOUR 2;
SHOW CREATE USER u11@localhost;
CREATE USER u12@localhost IDENTIFIED BY 'auth_string'                           WITH MAX_QUERIES_PER_HOUR 2;
SHOW CREATE USER u12@localhost;
CREATE USER u13@localhost IDENTIFIED WITH 'sha256_password'                           WITH MAX_CONNECTIONS_PER_HOUR 2;
SHOW CREATE USER u13@localhost;
CREATE USER u14@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string'                           WITH MAX_USER_CONNECTIONS 2;
SHOW CREATE USER u14@localhost;
CREATE USER u15@localhost IDENTIFIED WITH 'sha256_password' BY 'auth_string'             REQUIRE SUBJECT '/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client'             ISSUER "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA"             CIPHER 'cipher' WITH MAX_QUERIES_PER_HOUR 2 MAX_USER_CONNECTIONS 2;
SHOW CREATE USER u15@localhost;
ALTER USER u15@localhost IDENTIFIED WITH 'mysql_native_password' BY 'auth_string'                          WITH MAX_CONNECTIONS_PER_HOUR 1000 MAX_USER_CONNECTIONS 20 MAX_QUERIES_PER_HOUR 60 MAX_UPDATES_PER_HOUR 100;
SHOW CREATE USER u15@localhost;
DROP USER u15@localhost;
CREATE USER 'u15'@'localhost' IDENTIFIED WITH 'mysql_native_password'             AS '*67092806AE91BFB6BE72DE6C7BE2B7CCA8CFA9DF'             REQUIRE SUBJECT '/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client'             ISSUER '/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA'             CIPHER 'cipher'             WITH MAX_QUERIES_PER_HOUR 60 MAX_UPDATES_PER_HOUR 100 MAX_CONNECTIONS_PER_HOUR 1000 MAX_USER_CONNECTIONS 20 PASSWORD EXPIRE DEFAULT;
SELECT USER();
SET PASSWORD='auth_xyz';
SELECT USER();
SELECT USER();
SELECT USER();
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
SHOW GLOBAL VARIABLES LIKE 'log_bin';
reset master;
CREATE USER u1 IDENTIFIED WITH 'mysql_native_password' BY 'azundris1';
CREATE USER u2@localhost IDENTIFIED BY 'meow';
CREATE USER u10@localhost IDENTIFIED WITH 'sha256_password'                           REQUIRE CIPHER "DHE-RSA-AES256-SHA" AND SUBJECT "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client"                           ISSUER "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA"                           WITH MAX_QUERIES_PER_HOUR 2 MAX_USER_CONNECTIONS 2;
ALTER USER u10@localhost IDENTIFIED WITH 'mysql_native_password' BY 'auth_string'                          REQUIRE SSL;
SELECT USER();
ALTER USER USER() IDENTIFIED BY 'new-auth';
TRUNCATE TABLE mysql.general_log;
SET @old_log_output=    @@global.log_output;
SET @old_general_log=         @@global.general_log;
SET @old_general_log_file=    @@global.general_log_file;
SET GLOBAL log_output =       'FILE,TABLE';
SET GLOBAL general_log=       'ON';
CREATE USER u1 IDENTIFIED WITH 'mysql_native_password' BY 'azundris1';
CREATE USER u2@localhost IDENTIFIED BY 'meow';
CREATE USER u10@localhost IDENTIFIED WITH 'sha256_password'             REQUIRE CIPHER "DHE-RSA-AES256-SHA" AND SUBJECT "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=Client"             ISSUER "/C=SE/ST=Stockholm/L=Stockholm/O=Oracle/OU=MySQL/CN=CA"             WITH MAX_QUERIES_PER_HOUR 2 MAX_USER_CONNECTIONS 2;
ALTER USER u10@localhost IDENTIFIED WITH 'mysql_native_password' BY 'auth_string'                          REQUIRE SSL;
SELECT USER();
ALTER USER USER() IDENTIFIED BY 'new-auth';
SELECT argument FROM mysql.general_log WHERE argument LIKE 'CREATE USER %' AND command_type NOT LIKE 'Prepare';
SELECT argument FROM mysql.general_log WHERE argument LIKE 'ALTER USER %' AND command_type NOT LIKE 'Prepare';
SELECT argument FROM mysql.general_log WHERE argument LIKE 'SET PASSWORD %';
SELECT argument FROM mysql.general_log WHERE argument LIKE 'GRANT %'AND command_type NOT LIKE 'Prepare';
SET GLOBAL general_log_file=  @old_general_log_file;
SET GLOBAL general_log=       @old_general_log;
SET GLOBAL log_output=        @old_log_output;
TRUNCATE TABLE mysql.general_log;
CREATE USER u1;
ALTER USER u1 IDENTIFIED WITH 'invalid_plugin';
ALTER USER u1 IDENTIFIED WITH 'invalid_plugin' BY 'secret';
ALTER USER u1 IDENTIFIED WITH 'invalid_plugin' AS 'secret';
DROP USER u1;
CREATE USER bug20364862_dest@localhost IDENTIFIED BY 'dest_password';
CREATE DATABASE db1;
GRANT ALL PRIVILEGES ON db1.* TO bug20364862_dest@localhost WITH GRANT OPTION;
GRANT UPDATE ON mysql.* TO bug20364862_dest@localhost;
FLUSH PRIVILEGES;
REVOKE UPDATE ON mysql.* FROM bug20364862_dest@localhost;
GRANT CREATE USER ON *.* TO bug20364862_dest@localhost;
FLUSH PRIVILEGES;
DROP DATABASE db1;
DROP USER bug20364862_dest@localhost;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
SELECT USER(), CURRENT_USER();
SELECT USER(), CURRENT_USER();
SELECT USER(), CURRENT_USER();
SELECT USER(), CURRENT_USER();
CREATE USER bug20625566_dest@localhost IDENTIFIED BY 'dest_password';
SELECT USER(), CURRENT_USER();
SHOW CREATE USER bug20625566_dest@localhost;
