CALL mtr.add_suppression("Failed to set up SSL because of the following *");
CALL mtr.add_suppression("One can only use the --user switch.*");
SET PERSIST auto_increment_increment=10;
SET @@persist.event_scheduler=0;
SET PERSIST replica_compressed_protocol=1;
SET GLOBAL PERSIST replica_compressed_protocol=1;
SET PERSIST @@global.replica_compressed_protocol=1;
SET PERSIST @@session.replica_compressed_protocol=1;
SET @@persist.@@replica_compressed_protocol=1;
SET SESSION auto_increment_increment=3;
SELECT VARIABLE_NAME, VARIABLE_SOURCE FROM performance_schema.variables_info WHERE VARIABLE_NAME = 'auto_increment_increment';
SET PERSIST innodb_checksum_algorithm=strict_crc32, PERSIST innodb_default_row_format=COMPACT, PERSIST sql_mode=ANSI_QUOTES,PERSIST innodb_fast_shutdown=0;
SET PERSIST innodb_flush_log_at_trx_commit=0,join_buffer_size=262144;
SET PERSIST innodb_thread_concurrency=32, PERSIST innodb_write_io_threads=32, PERSIST innodb_read_io_threads=invalid_val;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
SELECT @@global.innodb_fast_shutdown;
SELECT @@global.innodb_default_row_format;
SELECT @@global.sql_mode;
SELECT @@global.innodb_flush_log_at_trx_commit;
SELECT @@global.join_buffer_size;
SELECT @@global.innodb_checksum_algorithm;
SELECT VARIABLE_NAME, VARIABLE_SOURCE FROM performance_schema.variables_info WHERE VARIABLE_SOURCE = 'PERSISTED'   ORDER BY VARIABLE_NAME;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
show session status;
SELECT @@global.innodb_fast_shutdown;
SELECT @@global.innodb_default_row_format;
SELECT @@global.sql_mode;
SELECT @@global.innodb_checksum_algorithm;
SELECT @@global.innodb_flush_log_at_trx_commit;
SELECT @@global.max_digest_length;
SELECT @@global.join_buffer_size;
SELECT @@global.sort_buffer_size;
SELECT VARIABLE_NAME,VARIABLE_SOURCE,MIN_VALUE,MAX_VALUE FROM performance_schema.variables_info WHERE VARIABLE_NAME IN ('innodb_fast_shutdown','sql_mode', 'innodb_default_row_format','max_digest_length', 'innodb_flush_log_at_trx_commit', 'disconnect_on_expired_password', 'innodb_checksum_algorithm') ORDER BY VARIABLE_NAME;
reset master;
SET PERSIST max_connections=500;
SET PERSIST autocommit=OFF;
SELECT VARIABLE_NAME, VARIABLE_SOURCE FROM performance_schema.variables_info WHERE VARIABLE_NAME = 'max_connections';
SET GLOBAL max_connections=DEFAULT;
SELECT VARIABLE_NAME, VARIABLE_SOURCE FROM performance_schema.variables_info WHERE VARIABLE_NAME IN ('max_connections','autocommit');
CREATE TABLE t1 (col1 INT);
DROP TABLE t1;
SET PERSIST log_bin_trust_function_creators=1;
SET PERSIST block_encryption_mode= 'aes-128-ecb';
SET PERSIST ft_boolean_syntax= '+ -><()~*:""&|', PERSIST log_error_services=DEFAULT;
SET PERSIST innodb_max_dirty_pages_pct=80.99;
SET PERSIST slow_query_log=ON;
SET PERSIST slow_query_log_file='/data/yu/Squirrel_DBMS_Fuzzing/MySQL_source/mysql-server-inst/bld/mysql-test/var/log/slow_query_on.log;';
show session status;
show session status;
show session status;
show session status;
show session status;
