drop table if exists t1,t2;
create table t1(n int);
insert into t1 values (1);
update t1 set n = 2 and get_lock('mysqltest_lock', 100);
update low_priority t1 set n = 4;
reap;
reap;
reap;
drop table t1;
create table t1(n int);
insert into t1 values (1);
update low_priority t1 set n = 4;
reap;
reap;
drop table t1;
create table t1 (a int, b int);
create table t2 (c int, d int);
insert into t1 values(1,1);
insert into t1 values(2,2);
insert into t2 values(1,2);
update t1,t2 set c=a where b=d;
reap;
update t1,t2 set c=a where b=d;;
reap;
reap;
lock table t1 read;
update t1,t2 set c=a where b=d;;
unlock tables;
reap;
lock table t2 read;
update t1,t2 set c=a where b=d;;
unlock tables;
reap;
lock table t1 read;
lock tables t1 read, t2 write;
update t1,t2 set c=a where b=d;
unlock tables;
unlock tables;
drop table t1;
drop table t2;
create table t1 (a int);
create table t2 (a int);
lock table t1 write, t2 write;
insert t1 select * from t2;
drop table t2;
unlock tables;
reap;
drop table t1;
create table t1 (a int);
create table t2 (a int);
lock table t1 write, t2 write, t1 as t1_2 write, t2 as t2_2 write;
insert t1 select * from t2;
drop table t2;
unlock tables;
reap;
drop table t1;
create table t1(a int);
lock tables t1 write;
show columns from t1;
unlock tables;
drop table t1;
INSERT IGNORE INTO mysql.user (host, user) VALUES ('localhost','');
