#ifndef __DEFINE_SQLRIGHTIR_H__
#define __DEFINE_SQLRIGHTIR_H__

#define ALLTYPE(V)                                                             \
  /* New one here!!! */                                                        \
  V(TypeUnknown)                                                               \
  V(TypeRoot)                                                                  \
  V(TypeStmtList)                                                              \
  V(TypeStmt)                                                                  \
  V(TypeIdentifier)                                                            \
  V(TypeAlterChangeFeed)                                                       \
  V(TypeAlterChangefeedCmds)                                                   \
  V(TypeAlterChangefeedAddTarget)                                              \
  V(TypeChangefeedTargets)                                                     \
  V(TypeKVOptions)                                                             \
  V(TypeKVOption)                                                              \
  V(TypeAlterChangefeedDropTarget)                                             \
  V(TypeAlterChangefeedSetOptions)                                             \
  V(TypeAlterChangefeedUnsetOptions)                                           \
  V(TypeNameList)                                                              \
  V(TypeAlterBackup)                                                           \
  V(TypeAlterBackupCmds)                                                       \
  V(TypeAlterBackupKMS)                                                        \
  V(TypeBackupKMS)                                                             \
  V(TypeStringOrPlaceholderOptList)                                            \
  V(TypeAlterBackupSchedule)                                                   \
  V(TypeAlterBackupScheduleCmds)                                               \
  V(TypeAlterBackupScheduleSetLabel)                                           \
  V(TypeAlterBackupScheduleSetInto)                                            \
  V(TypeAlterBackupScheduleSetWith)                                            \
  V(TypeAlterBackupScheduleSetRecurring)                                       \
  V(TypeAlterBackupScheduleSetFullBackup)                                      \
  V(TypeAlterBackupScheduleSetScheduleOption)                                  \
  V(TypeOptIfExists)                                                           \
  V(TypeOptIfNotExists)                                                        \
  V(TypeAlterIndex)                                                            \
  V(TypeAlterIndexCmds)                                                        \
  V(TypeAlterIndexPartitionBy)                                                 \
  V(TypeAlterIndexVisible)                                                     \
  V(TypeAlterDatabaseOwner)                                                    \
  V(TypeAlterDatabaseAddRegion)                                                \
  V(TypeAlterDatabaseDropRegion)                                               \
  V(TypeAlterDatabaseSurvivalGoal)                                             \
  V(TypeSurvivalGoal)                                                          \
  V(TypeAlterDatabasePlacement)                                                \
  V(TypeDataPlacement)                                                         \
  V(TypeAlterDatabaseAddSuperRegion)                                           \
  V(TypeAlterDatabaseDropSuperRegion)                                          \
  V(TypeAlterDatabaseAlterSuperRegion)                                         \
  V(TypeAlterDatabaseSecondaryRegion)                                          \
  V(TypeAlterDatabaseDropSecondaryRegion)                                      \
  V(TypeAlterDatabaseSetZoneConfigExtension)                                   \
  V(TypeOptForRole)                                                            \
  V(TypeAlterDefaultPrivileges)                                                \
  V(TypeRoleSpecList)                                                          \
  V(TypeRoleSpec)                                                              \
  V(TypeRoleSpecType)                                                          \
  V(TypeObjectNamePrefixList)                                                  \
  V(TypeObjectNamePrefix)                                                      \
  V(TypeGrantTarget)                                                           \
  V(TypeAbbreviatedGrant)                                                      \
  V(TypeAbbreviatedRevoke)                                                     \
  V(TypeFunctionOptions)                                                       \
  V(TypeFuncObj)                                                               \
  V(TypeFuncArgs)                                                              \
  V(TypeFuncArg)                                                               \
  V(TypeIntegerLiteral)                                                        \
  V(TypeStringLiteral)                                                         \
  V(TypeOptDefaultValue)                                                       \
  V(TypeFunctionNullInputBehavior)                                             \
  V(TypeFunctionVolatility)                                                    \
  V(TypeFunctionLeakproof)                                                     \
  V(TypeFunctionLanguage)                                                      \
  V(TypeFunctionBodyStr)                                                       \
  V(TypeAlterFunctionRename)                                                   \
  V(TypeAlterFunctionSetSchema)                                                \
  V(TypeAlterFunctionDepExtension)                                             \
  V(TypeAlterSchema)                                                           \
  V(TypeAlterSchemaRename)                                                     \
  V(TypeAlterSchemaOwner)                                                      \
  V(TypeAlterTable)                                                            \
  V(TypeAlterTableAddColumn)                                                   \
  V(TypeAlterTableAddConstraint)                                               \
  V(TypeResolvableTypeReference)                                               \
  V(TypeUsingCluster)                                                          \
  V(TypeAlterTableAlterPrimaryKey)                                             \
  V(TypeAlterTableDropColumn)                                                  \
  V(TypeAlterTableDropConstraint)                                              \
  V(TypeAlterTableValidateConstraint)                                          \
  V(TypeAlterTableRenameColumn)                                                \
  V(TypeAlterTableRenameConstraint)                                            \
  V(TypeAlterTableSetDefault)                                                  \
  V(TypeAlterTableSetOnUpdate)                                                 \
  V(TypeOptNot)                                                                \
  V(TypeAlterTableSetNotNull)                                                  \
  V(TypeAlterTableDropNotNull)                                                 \
  V(TypeAlterTableDropStored)                                                  \
  V(TypeAlterTablePartitionByTable)                                            \
  V(TypeAlterTableSetAudit)                                                    \
  V(TypeAuditMode)                                                             \
  V(TypeAlterTableInjectStats)                                                 \
  V(TypeAlterTableSetStorageParams)                                            \
  V(TypeAlterTableResetStorageParams)                                          \
  V(TypeAlterTableLocality)                                                    \
  V(TypeAlterTableSetSchema)                                                   \
  V(TypeAlterTableOwner)                                                       \
  V(TypeLocality)                                                              \
  V(TypeCreateDatabase)                                                        \
  V(TypeIndexElem)                                                             \
  V(TypeDirection)                                                             \
  V(TypeNullsOrder)                                                            \
  V(TypeIndexElemList)                                                         \
  V(TypeOptUnique)                                                             \
  V(TypeOptInverted)                                                           \
  V(TypeOptConcurrently)                                                       \
  V(TypeOptStoring)                                                            \
  V(TypeOptPartitionBy)                                                        \
  V(TypeOptStorageParams)                                                      \
  V(TypeOptPredicate)                                                          \
  V(TypeOptNotVisible)                                                         \
  V(TypeCreateIndex)                                                           \
  V(TypeOptSharded)                                                            \
  V(TypeEnumValue)                                                             \
  V(TypeEnumValueList)                                                         \
  V(TypeCreateType)                                                            \
  V(TypeStorageParams)                                                         \
  V(TypeShardedIndexDef)                                                       \
  V(TypePartitionByTable)                                                      \
  V(TypePartitionBy)                                                           \
  V(TypeListPartition)                                                         \
  V(TypeExprs)                                                                 \
  V(TypeRangePartition)                                                        \
  V(TypeTableDefs)                                                             \
  V(TypeNullability)                                                           \
  V(TypePrimaryKey)                                                            \
  V(TypeOptWithoutIndex)                                                       \
  V(TypeDefaultExpr)                                                           \
  V(TypeOnUpdateExpr)                                                          \
  V(TypeGeneratedIdentity)                                                     \
  V(TypeReferenceCluster)                                                      \
  V(TypeColumnTableDef)                                                        \
  V(TypeIndexTableDef)                                                         \
  V(TypeUniqueConstraintTableDef)                                              \
  V(TypeOptTableDefs)                                                          \
  V(TypeCreateTable)                                                           \
  V(TypeCreateSchema)                                                          \
  V(TypeCreateSequence)                                                        \
  V(TypeSequenceOption)                                                        \
  V(TypeColumnItemVal)                                                         \
  V(TypeLikeTableDef)                                                          \
  V(TypeLikeTableOption)                                                       \
  V(TypeCreateRole)                                                            \
  V(TypeOptOrReplace)                                                          \
  V(TypeOptTemporary)                                                          \
  V(TypeOptMaterialized)                                                       \
  V(TypeCreateView)                                                            \
  V(TypeRefreshMaterializedView)                                               \
  V(TypeCreateStats)                                                           \
  V(TypeFloatLiteral)                                                          \
  V(TypeCreateStatsOptions)                                                    \
  V(TypeCreateExtension)                                                       \
  V(TypeCreateExternalConnection)                                              \
  V(TypeLabelSpec)                                                             \
  V(TypeRecurrence)                                                            \
  V(TypeScheduledBackup)                                                       \
  V(TypeBackup)                                                                \
  V(TypeRestore)                                                               \
  V(TypeBackupOptions)                                                         \
  V(TypeRestoreOptions)                                                        \
  V(TypeBackupTargetList)                                                      \
  V(TypeAsOfClause)                                                            \
  V(TypeTenantID)                                                              \
  V(TypeTablePatterns)                                                         \
  V(TypeAllTablesSelector)                                                     \
  V(TypeUnresolvedName)                                                        \
  V(TypeTenantAllOrID)                                                         \
  V(TypeAlterTenantSetClusterSetting)                                          \
  V(TypeShowTenantClusterSetting)                                              \
  V(TypeShowTenantClusterSettingList)                                          \
  V(TypeSetVar)                                                                \
  V(TypeSetClusterSetting)                                                     \
  V(TypeSetTransaction)                                                        \
  V(TypeSetSessionAuthorizationDefault)                                        \
  V(TypeSetSessionCharacteristics)                                             \
  V(TypeSetTracing)                                                            \
  V(TypeOptIsolationLevel)                                                     \
  V(TypeUserPriority)                                                          \
  V(TypeReadWriteMode)                                                         \
  V(TypeDeferrable)                                                            \
  V(TypeTransactionModes)                                                      \
  V(TypeBeginTransaction)                                                      \
  V(TypeCommitTransaction)                                                     \
  V(TypeRollbackTransaction)                                                   \
  V(TypeSavepoint)                                                             \
  V(TypeReleaseSavepoint)                                                      \
  V(TypeRollbackToSavepoint)                                                   \
  V(TypeShowVar)                                                               \
  V(TypeShowClusterSetting)                                                    \
  V(TypeShowClusterSettingList)                                                \
  V(TypeShowBackup)                                                            \
  V(TypeShowColumns)                                                           \
  V(TypeShowDatabases)                                                         \
  V(TypeShowEnums)                                                             \
  V(TypeShowTypes)                                                             \
  V(TypeShowTraceForSession)                                                   \
  V(TypeShowIndexes)                                                           \
  V(TypeShowDatabaseIndexes)                                                   \
  V(TypeShowQueries)                                                           \
  V(TypeShowJobs)                                                              \
  V(TypeShowChangefeedJobs)                                                    \
  V(TypeShowSurvivalGoal)                                                      \
  V(TypeShowRegions)                                                           \
  V(TypeShowSessions)                                                          \
  V(TypeShowSchemas)                                                           \
  V(TypeShowSequences)                                                         \
  V(TypeShowTables)                                                            \
  V(TypeShowTransactions)                                                      \
  V(TypeShowConstraints)                                                       \
  V(TypeShowGrants)                                                            \
  V(TypeShowRoleGrants)                                                        \
  V(TypeShowCreate)                                                            \
  V(TypeShowCreateAllSchemas)                                                  \
  V(TypeShowCreateAllTables)                                                   \
  V(TypeShowCreateAllTypes)                                                    \
  V(TypeShowCreateSchedules)                                                   \
  V(TypeShowSyntax)                                                            \
  V(TypeShowTransactionStatus)                                                 \
  V(TypeShowLastQueryStatistics)                                               \
  V(TypeShowFullTableScans)                                                    \
  V(TypeShowSavepointStatus)                                                   \
  V(TypeShowUsers)                                                             \
  V(TypeShowRoles)                                                             \
  V(TypeShowRanges)                                                            \
  V(TypeShowRangeForRow)                                                       \
  V(TypeShowFingerprints)                                                      \
  V(TypeShowTableStats)                                                        \
  V(TypeShowHistogram)                                                         \
  V(TypeShowPartitions)                                                        \
  V(TypeScheduleState)                                                         \
  V(TypeShowSchedules)                                                         \
  V(TypeShowDefaultPrivileges)                                                 \
  V(TypeShowTransferState)                                                     \
  V(TypeShowCompletions)                                                       \
  V(TypeShowCreateFunction)                                                    \
  V(TypeShowCreateExternalConnections)                                         \
  V(TypeGrantTargetList)                                                       \
  V(TypeGrant)                                                                 \
  V(TypeGrantRole)                                                             \
  V(TypeFuncObjs)                                                              \
  V(TypeIndexedVar)                                                            \
  V(TypeOptExists)                                                             \
  V(TypeTypedDummy)                                                            \
  V(TypeUnqualifiedStar)                                                       \
  V(TypeAllColumnsSelector)                                                    \
  V(TypeTupleStar)                                                             \
  V(TypeColumnItem)                                                            \
  V(TypeAndExpr)                                                               \
  V(TypeOrExpr)                                                                \
  V(TypeNotExpr)                                                               \
  V(TypeIsNullExpr)                                                            \
  V(TypeIsNotNullExpr)                                                         \
  V(TypeParenExpr)                                                             \
  V(TypeExprFmtWithParen)                                                      \
  V(TypeBinExprFmtWithParenAndSubOp)                                           \
  V(TypeBinExprFmtWithParen)                                                   \
  V(TypeComparisonExpr)                                                        \
  V(TypeOptSymmetric)                                                          \
  V(TypeRangeCond)                                                             \
  V(TypeIsOfTypeExpr)                                                          \
  V(TypeIfErrExpr)                                                             \
  V(TypeIfExpr)                                                                \
  V(TypeNullIfExpr)                                                            \
  V(TypeCoalesceExpr)                                                          \
  V(TypeDefaultVal)                                                            \
  V(TypePartitionMaxVal)                                                       \
  V(TypePartitionMinVal)                                                       \
  V(TypePlaceholder)                                                           \
  V(TypeTuple)                                                                 \
  V(TypeArray)                                                                 \
  V(TypeArrayFlatten)                                                          \
  V(TypeBinaryExpr)                                                            \
  V(TypeUnaryExpr)                                                             \
  V(TypeFuncExpr)                                                              \
  V(TypeCaseExpr)                                                              \
  V(TypeWhen)                                                                  \
  V(TypeCastExpr)                                                              \
  V(TypeIndirectionExpr)                                                       \
  V(TypeAnnotateTypeExpr)                                                      \
  V(TypeCollateExpr)                                                           \
  V(TypeColumnAccessExpr)                                                      \
  V(TypeSelect)                                                                \
  V(TypeParenSelect)                                                           \
  V(TypeSelectClause)                                                          \
  V(TypeOptDistinct)                                                           \
  V(TypeSelectExprs)                                                           \
  V(TypeSelectExpr)                                                            \
  V(TypeAliasClause)                                                           \
  V(TypeColumnDef)                                                             \
  V(TypeColumnDefList)                                                         \
  V(TypeFrom)                                                                  \
  V(TypeTableExprs)                                                            \
  V(TypeStatementSource)                                                       \
  V(TypeIndexFlags)                                                            \
  V(TypeIndexFlag)                                                             \
  V(TypeOptLiteral)                                                            \
  V(TypeAliasedTableExpr)                                                      \
  V(TypeParenTableExpr)                                                        \
  V(TypeJoinType)                                                              \
  V(TypeJoinHint)                                                              \
  V(TypeJoinTableExpr)                                                         \
  V(TypeNaturalJoinCond)                                                       \
  V(TypeOnJoinCond)                                                            \
  V(TypeUsingJoinCond)                                                         \
  V(TypeWhere)                                                                 \
  V(TypeGroupBy)                                                               \
  V(TypeDistinctOn)                                                            \
  V(TypeOrderBy)                                                               \
  V(TypeOrder)                                                                 \
  V(TypeLimitCluster)                                                          \
  V(TypeOffsetCluster)                                                         \
  V(TypeLimit)                                                                 \
  V(TypeRowsFromExpr)                                                          \
  V(TypeWindow)                                                                \
  V(TypeWindowDef)                                                             \
  V(TypeWindowFrameBound)                                                      \
  V(TypeWindowFrameMode)                                                       \
  V(TypeWindowFrameExclusion)                                                  \
  V(TypeWindowFrame)                                                           \
  V(TypeLockingClause)                                                         \
  V(TypeTableNames)                                                            \
  V(TypeWaitPolicy)                                                            \
  V(TypeLockingItem)                                                           \
  V(TypeLockingStrength)                                                       \
  V(TypeLockingWaitPolicy)                                                     \
  V(TypeWith)                                                                  \
  V(TypeOptRecursive)                                                          \
  V(TypeCTECluster)                                                            \
  V(TypeAlterType)                                                             \
  V(TypeAlterTypeAddValue)                                                     \
  V(TypeAlterTypeRenameValue)                                                  \
  V(TypeAlterTypeDropValue)                                                    \
  V(TypeAlterTypeRename)                                                       \
  V(TypeAlterTypeSetSchema)                                                    \
  V(TypeAlterTypeOwner)                                                        \
  V(TypeAlterRole)                                                             \
  V(TypeAlterRoleSet)                                                          \
  V(TypeAlterSequence)                                                         \
  V(TypeAnalyze)                                                               \
  V(TypeControlJobs)                                                           \
  V(TypeCancelQueries)                                                         \
  V(TypeCancelSessions)                                                        \
  V(TypeControlSchedules)                                                      \
  V(TypeControlJobsOfType)                                                     \
  V(TypeControlJobsForSchedules)                                               \
  V(TypePrepare)                                                               \
  V(TypeCannedOptPlan)                                                         \
  V(TypeOptDiscardRows)                                                        \
  V(TypeExecute)                                                               \
  V(TypeDeallocate)                                                            \
  V(TypeOptBinary)                                                             \
  V(TypeOptSensitivity)                                                        \
  V(TypeOptScroll)                                                             \
  V(TypeDeclareCursor)                                                         \
  V(TypeOptFetchType)                                                          \
  V(TypeCursorStmt)                                                            \
  V(TypeFetchCursor)                                                           \
  V(TypeMoveCursor)                                                            \
  V(TypeCloseCursor)                                                           \
  V(TypeCommentOnColumn)                                                       \
  V(TypeCommentOnConstraint)                                                   \
  V(TypeCommentOnDatabase)                                                     \
  V(TypeCommentOnSchema)                                                       \
  V(TypeCommentOnIndex)                                                        \
  V(TypeCommentOnTable)                                                        \
  V(TypeTableIndexName)                                                        \
  V(TypeTableIndexNames)                                                       \
  V(TypeOptStdin)                                                              \
  V(TypeCopyFrom)                                                              \
  V(TypeCopyFormat)                                                            \
  V(TypeCopyOptions)                                                           \
  V(TypeCreateChangefeed)                                                      \
  V(TypeChangefeedTarget)                                                      \
  V(TypeCreateFunction)                                                        \
  V(TypeRoutineReturn)                                                         \
  V(TypeDelete)                                                                \
  V(TypeReturningExprs)                                                        \
  V(TypeReturningNothing)                                                      \
  V(TypeNoReturningClause)                                                     \
  V(TypeDropBehavior)                                                          \
  V(TypeDropDatabase)                                                          \
  V(TypeDropIndex)                                                             \
  V(TypeDropTable)                                                             \
  V(TypeDropView)                                                              \
  V(TypeDropSequence)                                                          \
  V(TypeDropRole)                                                              \
  V(TypeDropType)                                                              \
  V(TypeDropSchema)                                                            \
  V(TypeDropFunction)                                                          \
  V(TypeDropExternalConnection)                                                \
  V(TypeDropOwnedBy)                                                           \
  V(TypeReassignOwnedBy)                                                       \
  V(TypeFileFormat)                                                            \
  V(TypeExport)                                                                \
  V(TypeExplainMode)                                                           \
  V(TypeExplainFlag)                                                           \
  V(TypeExplain)                                                               \
  V(TypeExplainAnalyze)                                                        \
  V(TypeSplit)                                                                 \
  V(TypeUnsplit)                                                               \
  V(TypeRelocate)                                                              \
  V(TypeScatter)                                                               \
  V(TypeRelocateSubject)                                                       \
  V(TypeRelocateRange)                                                         \
  V(TypeRenameDatabase)                                                        \
  V(TypeReparentDatabase)                                                      \
  V(TypeRenameTable)                                                           \
  V(TypeRenameIndex)                                                           \
  V(TypeRenameColumn)                                                          \
  V(TypePrivilege)                                                             \
  V(TypeRevoke)                                                                \
  V(TypeRevokeRole)                                                            \
  V(TypeScrub)                                                                 \
  V(TypeScrubOptions)                                                          \
  V(TypeScrubOptionIndex)                                                      \
  V(TypeScrubOptionPhysical)                                                   \
  V(TypeScrubOptionConstraint)                                                 \
  V(TypeZoneSpecifier)                                                         \
  V(TypeShowZoneConfig)                                                        \
  V(TypeSetZoneConfig)                                                         \
  V(TypeZoneConfigSettings)                                                    \
  V(TypeStreamIngestion)                                                       \
  V(TypeTruncate)                                                              \
  V(TypeUnionClause)                                                           \
  V(TypeInsert)                                                                \
  V(TypeImport)                                                                \
  V(TypeValuesClause)                                                          \
  V(TypeLiteralValuesClause)                                                   \
  V(TypeUpdate)                                                                \
  V(TypeUpdateExprs)                                                           \
  V(TypeUpdateExpr)                                                            \
  V(TypeReferenceActions)                                                      \
  V(TypeForeignKeyConstraintTableDef)                                          \
  V(TypeMatching)                                                              \
  V(TypeCheckConstraintTableDef)                                               \
  V(TypeFamilyTableDef)                                                        \
  V(TypeDArray)                                                                \
  V(TypedNull)                                                                 \
  V(TypeDTuple)                                                                \
  V(TypeDBool)                                                                 \
  V(TypeArraySubscripts)                                                       \
  V(TypeArraySubscript)                                                        \
  V(TypeDCollatedString)                                                       \
  V(TypeDiscard)                                                               \
  V(TypeUnlisten)                                                              \
  V(TypeTableRef)                                                              \
  V(TypeHaving)                                                                \
  V(TypeConstraintCluster)

#define ALLDATATYPE(V)                                                         \
  V(DataNone)                                                                  \
  V(DataUnknownType)                                                           \
  V(DataChangeFeed)                                                            \
  V(DataDatabaseName)                                                          \
  V(DataSuperRegion)                                                           \
  V(DataRoleName)                                                              \
  V(DataCatalogName)                                                           \
  V(DataSchemaName)                                                            \
  V(DataFunctionName)                                                          \
  V(DataExtensionName)                                                         \
  V(DataCollationName)                                                         \
  V(DataColumnName)                                                            \
  V(DataConstraintName)                                                        \
  V(DataViewName)                                                              \
  V(DataSequenceName)                                                          \
  V(DataTableName)                                                             \
  V(DataRegionName)                                                            \
  V(DataTemplateName)                                                          \
  V(DataEncodingName)                                                          \
  V(DataCTypeName)                                                             \
  V(DataIndexName)                                                             \
  V(DataTypeName)                                                              \
  V(DataPartitionName)                                                         \
  V(DataRangeName)                                                             \
  V(DataFamilyName)                                                            \
  V(DataStatsName)                                                             \
  V(DataSettingName)                                                           \
  V(DataSavePointName)                                                         \
  V(DataPrivilege)                                                             \
  V(DataWindowName)                                                            \
  V(DataStatementPreparedName)                                                 \
  V(DataCursorName)                                                            \
  V(DataZoneName)                                                              \
  V(DataChannelName)                                                           \
  V(DataTableAliasName)                                                        \
  V(DataColumnAliasName)                                                       \
  V(DataLiteral)

#define ALLCONTEXTFLAGS(V)                                                     \
  V(ContextUnknown)                                                            \
  V(ContextDefine)                                                             \
  V(ContextUse)                                                                \
  V(ContextUndefine)                                                           \
  V(ContextReplaceDefine)                                                      \
  V(ContextReplaceUndefine)                                                    \
  V(ContextNoModi)                                                             \
  V(ContextUseFollow)

#define ALLFUNCTIONTYPES(V)                                                    \
  V(FUNCAGGR)                                                                  \
  V(FUNCWINDOW)                                                                \
  V(FUNCUNKNOWN)

#define ALLDATAAFFINITY(V)                                                     \
  /* New one here!!! */                                                        \
  V(AFFIUNKNOWN)                                                               \
  V(AFFIBIT)                                                                   \
  V(AFFIBOOL)                                                                  \
  V(AFFIBYTES)                                                                 \
  V(AFFICOLLATE)                                                               \
  V(AFFIDATE)                                                                  \
  V(AFFIENUM)                                                                  \
  V(AFFIDECIMAL)                                                               \
  V(AFFIFLOAT)                                                                 \
  V(AFFIINET)                                                                  \
  V(AFFIINT)                                                                   \
  V(AFFIINTERVAL)                                                              \
  V(AFFIJSONB)                                                                 \
  V(AFFIOID)                                                                   \
  V(AFFISERIAL)                                                                \
  V(AFFISTRING)                                                                \
  V(AFFITIME)                                                                  \
  V(AFFITIMETZ)                                                                \
  V(AFFITIMESTAMP)                                                             \
  V(AFFITIMESTAMPTZ)                                                           \
  V(AFFIUUID)                                                                  \
  V(AFFIGEOGRAPHY)                                                             \
  V(AFFIGEOMETRY)                                                              \
  V(AFFIBOX2D)                                                                 \
  V(AFFIVOID)                                                                  \
  V(AFFIPOINT)                                                                 \
  V(AFFILINESTRING)                                                            \
  V(AFFIPOLYGON)                                                               \
  V(AFFIMULTIPOINT)                                                            \
  V(AFFIMULTILINESTRING)                                                       \
  V(AFFIMULTIPOLYGON)                                                          \
  V(AFFIGEOMETRYCOLLECTION)                                                    \
  V(AFFIOIDWRAPPER)                                                            \
  V(AFFIWHOLESTMT)                                                             \
  V(AFFIONOFF)                                                                 \
  V(AFFIONOFFAUTO)                                                             \
  V(AFFIARRAY)                                                                 \
  V(AFFIARRAYUNKNOWN)                                                          \
  V(AFFIARRAYBIT)                                                              \
  V(AFFIARRAYBOOL)                                                             \
  V(AFFIARRAYBYTES)                                                            \
  V(AFFIARRAYCOLLATE)                                                          \
  V(AFFIARRAYDATE)                                                             \
  V(AFFIARRAYENUM)                                                             \
  V(AFFIARRAYDECIMAL)                                                          \
  V(AFFIARRAYFLOAT)                                                            \
  V(AFFIARRAYINET)                                                             \
  V(AFFIARRAYINT)                                                              \
  V(AFFIARRAYINTERVAL)                                                         \
  V(AFFIARRAYJSONB)                                                            \
  V(AFFIARRAYOID)                                                              \
  V(AFFIARRAYSERIAL)                                                           \
  V(AFFIARRAYSTRING)                                                           \
  V(AFFIARRAYTIME)                                                             \
  V(AFFIARRAYTIMETZ)                                                           \
  V(AFFIARRAYTIMESTAMP)                                                        \
  V(AFFIARRAYTIMESTAMPTZ)                                                      \
  V(AFFIARRAYUUID)                                                             \
  V(AFFIARRAYGEOGRAPHY)                                                        \
  V(AFFIARRAYGEOMETRY)                                                         \
  V(AFFIARRAYBOX2D)                                                            \
  V(AFFIARRAYVOID)                                                             \
  V(AFFIARRAYPOINT)                                                            \
  V(AFFIARRAYLINESTRING)                                                       \
  V(AFFIARRAYPOLYGON)                                                          \
  V(AFFIARRAYMULTIPOINT)                                                       \
  V(AFFIARRAYMULTILINESTRING)                                                  \
  V(AFFIARRAYMULTIPOLYGON)                                                     \
  V(AFFIARRAYGEOMETRYCOLLECTION)                                               \
  V(AFFIARRAYOIDWRAPPER)                                                       \
  V(AFFIARRAYWHOLESTMT)                                                        \
  V(AFFIARRAYONOFF)                                                            \
  V(AFFIARRAYONOFFAUTO)

#define ALLCOLLATIONS(V)                                                       \
  V(defaultcollation)                                                          \
  V(und)                                                                       \
  V(aa)                                                                        \
  V(af)                                                                        \
  V(ar)                                                                        \
  V(as)                                                                        \
  V(az)                                                                        \
  V(be)                                                                        \
  V(bg)                                                                        \
  V(bn)                                                                        \
  V(bs)                                                                        \
  V(ca)                                                                        \
  V(cs)                                                                        \
  V(cy)                                                                        \
  V(da)                                                                        \
  V(de)                                                                        \
  V(dz)                                                                        \
  V(ee)                                                                        \
  V(el)                                                                        \
  V(en)                                                                        \
  V(eo)                                                                        \
  V(es)                                                                        \
  V(et)                                                                        \
  V(fa)                                                                        \
  V(fi)                                                                        \
  V(fil)                                                                       \
  V(fo)                                                                        \
  V(fr)                                                                        \
  V(gu)                                                                        \
  V(ha)                                                                        \
  V(haw)                                                                       \
  V(he)                                                                        \
  V(hi)                                                                        \
  V(hr)                                                                        \
  V(hu)                                                                        \
  V(hy)                                                                        \
  V(ig)                                                                        \
  V(is)                                                                        \
  V(ja)                                                                        \
  V(kk)                                                                        \
  V(kl)                                                                        \
  V(km)                                                                        \
  V(kn)                                                                        \
  V(ko)                                                                        \
  V(kok)                                                                       \
  V(ln)                                                                        \
  V(lt)                                                                        \
  V(lv)                                                                        \
  V(mk)                                                                        \
  V(ml)                                                                        \
  V(mr)                                                                        \
  V(mt)                                                                        \
  V(my)                                                                        \
  V(nb)                                                                        \
  V(nn)                                                                        \
  V(nso)                                                                       \
  V(om)                                                                        \
  V(pa)                                                                        \
  V(pl)                                                                        \
  V(ps)                                                                        \
  V(ro)                                                                        \
  V(ru)                                                                        \
  V(se)                                                                        \
  V(si)                                                                        \
  V(sk)                                                                        \
  V(sl)                                                                        \
  V(sq)                                                                        \
  V(sr)                                                                        \
  V(ssy)                                                                       \
  V(sv)                                                                        \
  V(ta)                                                                        \
  V(te)                                                                        \
  V(th)                                                                        \
  V(tn)                                                                        \
  V(to)                                                                        \
  V(tr)                                                                        \
  V(uk)                                                                        \
  V(ur)                                                                        \
  V(vi)                                                                        \
  V(wae)                                                                       \
  V(yo)                                                                        \
  V(zh)

#define SAFEDELETE(a)                                                          \
  if (a != NULL)                                                               \
  a->deep_delete()

#define SAFEDELETELIST(a)                                                      \
  for (auto _i : a)                                                            \
  SAFEDELETE(_i)

#define OP1(a) new IROperator(a)

#define OP2(a, b) new IROperator(a, b)

#define OP3(a, b, c) new IROperator(a, b, c)

#define OPSTART(a) new IROperator(a)

#define OPMID(a) new IROperator("", a, "")

#define OPEND(a) new IROperator("", "", a)

#define OP0() new IROperator()

#define MUTATESTART                                                            \
  IR *res = NULL;                                                              \
  auto randint = get_rand_int(3);                                              \
  switch (randint) {

#define DOLEFT case 0: {

#define DORIGHT                                                                \
  break;                                                                       \
  }                                                                            \
                                                                               \
  case 1: {

#define DOBOTH                                                                 \
  break;                                                                       \
  }                                                                            \
  case 2: {

#define MUTATEEND                                                              \
  }                                                                            \
  }                                                                            \
                                                                               \
  return res;

#endif // __DEFINE_SQLRIGHTIR_H__
