CREATE TABLE public.t ( a INT8 NOT NULL, b INT8 NOT NULL, k INT8 NOT NULL AS (a + b) VIRTUAL, CONSTRAINT t_pkey PRIMARY KEY (b ASC, k ASC), UNIQUE INDEX t_k_key (k ASC), UNIQUE INDEX t_a_key (a ASC), INDEX t_idx_b_k (b ASC, k ASC) );
CREATE TABLE t ( x INT PRIMARY KEY, y INT NOT NULL, z INT, INDEX i1 (z) USING HASH WITH (bucket_count=5), FAMILY (x, y, z) );
INSERT INTO t VALUES (1, 2, 3);
ALTER TABLE t ALTER PRIMARY KEY USING COLUMNS (y) USING HASH WITH (bucket_count=10);
ALTER TABLE t ALTER PRIMARY KEY USING COLUMNS (x);
INSERT INTO t VALUES (1, 2, 3);
