CREATE TABLE t (s STRING, sl STRING(5), t TIME, ts TIMESTAMP);
CREATE TABLE t1 (a INT PRIMARY KEY, b STRING, FAMILY "primary" (a, b));
SET TIME ZONE 'Europe/Amsterdam';
INSERT INTO t VALUES ('some string', 'short', TIME '20:16:27', '2018-05-23 20:16:27.658082');
CREATE INDEX idx ON t1 (b);
INSERT INTO t VALUES (1, '01'), (2, '002'), (3, '0003');
ALTER TABLE t ADD COLUMN i INT as (b::INT) STORED;
ALTER TABLE t ALTER COLUMN i DROP STORED, DROP COLUMN b CASCADE;
SELECT * from t ORDER BY b DESC;
