CREATE TABLE table8 (col1 TIME, col2 BYTES, col4 OID, col6 NAME, col9 TIMESTAMP, PRIMARY KEY (col1));
CREATE TABLE table5 (col0 TIME NULL, col1 OID, col3 INET, PRIMARY KEY (col1 ASC));
INSERT INTO table8 (col1, col2, col4, col6) VALUES ('19:06:18.321589', NULL, NULL, NULL) UNION ALL (SELECT NULL, NULL, NULL, NULL FROM table5 AS tab_8);
