CREATE TABLE t (a INT PRIMARY KEY, b INT);
INSERT INTO t VALUES (1, 99), (2, 98), (3, 97);
CREATE VIEW v1 AS SELECT a, b FROM t;
CREATE VIEW IF NOT EXISTS v1 AS SELECT b, a FROM v1;
CREATE VIEW v7 (x, y) AS SELECT a, b FROM v1 ORDER BY a DESC LIMIT 2;
SELECT * FROM v1 AS v1 INNER JOIN v2 AS v2 ON v1.a = v2.x;
